//! The frontmatter field table: names, types, which fields `update` may set.
//!
//! Generated by `#[derive(TicketSchema)]` (T-0028):
//! one declaration drives `ticket update` validation, the docs table and the
//! generic get/set used by events and the fold.

use std::fmt::Write as _;
use std::sync::LazyLock;

pub use gob_macros::TicketSchema;
pub use inventory;
pub use schemars::Schema as SchemaDocument;

use crate::id::TicketId;
use crate::model::{
    Acceptance, Category, Link, Outcome, Points, Priority, Stamp, Ticket, TicketType,
};

/// How a field's value is typed and parsed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldKind {
    /// Free text.
    Text,
    /// One of a closed set of spellings.
    Choice(&'static [&'static str]),
    /// Story points (Fibonacci 1..13).
    Points,
    /// A list of strings.
    List,
    /// A ticket id.
    TicketRef,
    /// An RFC 3339 instant.
    Instant,
    /// A list of objects (links, acceptance); never set through `update`.
    Objects,
}

/// Description of one frontmatter field, as the commands use it.
#[derive(Debug, Clone, Copy)]
pub struct FieldDescription {
    /// Key in the frontmatter and in `field` events.
    pub name: &'static str,
    /// Value type.
    pub kind: FieldKind,
    /// True when the field may be absent.
    pub optional: bool,
    /// True when `ticket update --set` may change it.
    pub settable: bool,
    /// One-line description.
    pub doc: &'static str,
}

/// Broad shape of a frontmatter field, as declared with `#[ticket(kind = ..)]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TicketFieldKind {
    /// A single value (text, id, number, instant).
    Scalar,
    /// One of a closed set of spellings.
    Enum,
    /// A list of strings.
    List,
    /// A list of tables (objects).
    Table,
}

/// One field of a [`TicketSchema`], generated by `#[derive(TicketSchema)]`.
#[derive(Debug, Clone, Copy)]
pub struct TicketFieldDescription {
    /// Key in the TOML frontmatter.
    pub key: &'static str,
    /// Description from the field's doc comment.
    pub doc: &'static str,
    /// The Rust type as written, without spaces (`Option<String>`).
    pub type_name: &'static str,
    /// Broad shape of the value.
    pub kind: TicketFieldKind,
    /// True when the key must be present.
    pub required: bool,
    /// True when `ticket update --set` may change it.
    pub settable: bool,
    /// The default as TOML text, when one is declared.
    pub default_toml: Option<&'static str>,
    /// First version that has the field, when declared.
    pub since: Option<&'static str>,
}

impl TicketFieldDescription {
    /// The type name with one `Option<..>` layer removed.
    pub fn inner_type(&self) -> &'static str {
        self.type_name
            .strip_prefix("Option<")
            .and_then(|t| t.strip_suffix('>'))
            .unwrap_or(self.type_name)
    }

    fn json_schema_fragment(&self) -> serde_json::Value {
        let scalar = |ty: &str| match ty {
            "Points" | "u8" | "u16" | "u32" | "u64" | "i32" | "i64" | "usize" => "integer",
            "bool" => "boolean",
            _ => "string",
        };
        let mut prop = match self.kind {
            TicketFieldKind::List => {
                serde_json::json!({ "type": "array", "items": { "type": "string" } })
            }
            TicketFieldKind::Table => {
                serde_json::json!({ "type": "array", "items": { "type": "object" } })
            }
            TicketFieldKind::Scalar | TicketFieldKind::Enum => {
                serde_json::json!({ "type": scalar(self.inner_type()) })
            }
        };
        prop["description"] = self.doc.into();
        if let Some(d) = self.default_toml {
            prop["x-default-toml"] = d.into();
        }
        if let Some(v) = self.since {
            prop["x-since"] = v.into();
        }
        prop
    }
}

/// The description of one ticket document type, generated by `#[derive(TicketSchema)]`.
#[derive(Debug, Clone, Copy)]
pub struct TicketSchemaDescription {
    /// The Rust name of the declaring struct.
    pub name: &'static str,
    /// Description from the struct's doc comment.
    pub doc: &'static str,
    /// Fields in declaration (file) order.
    pub fields: &'static [TicketFieldDescription],
}

impl TicketSchemaDescription {
    /// The JSON schema (an object schema) built from the fields at runtime.
    pub fn json_schema(&self) -> SchemaDocument {
        let mut props = serde_json::Map::new();
        let mut required = Vec::new();
        for f in self.fields {
            props.insert(f.key.to_owned(), f.json_schema_fragment());
            if f.required {
                required.push(f.key);
            }
        }
        let value = serde_json::json!({
            "title": self.name,
            "description": self.doc,
            "type": "object",
            "properties": props,
            "required": required,
            "additionalProperties": false,
        });
        SchemaDocument::try_from(value).unwrap_or_else(|_| unreachable!("an object is a schema"))
    }

    /// A markdown table of the fields (key, type, required, default, since, description).
    pub fn docs_table(&self) -> String {
        let mut out = String::from(
            "| Field | Type | Required | Default | Since | Description |\n|---|---|---|---|---|---|\n",
        );
        for f in self.fields {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} | {} | {} |",
                f.key,
                f.type_name.replace('|', "\\|"),
                if f.required { "yes" } else { "no" },
                f.default_toml
                    .map_or_else(String::new, |d| format!("`{d}`")),
                f.since.unwrap_or_default(),
                f.doc
            );
        }
        out
    }
}

/// A type whose frontmatter is described by `#[derive(TicketSchema)]`.
pub trait TicketSchema {
    /// The static description of this type.
    fn describe() -> &'static TicketSchemaDescription;
}

/// An inventory record of one schema, submitted by `#[derive(TicketSchema)]`.
///
/// A generator lists [`all_schemas`] and renders each description with
/// [`TicketSchemaDescription::docs_table`] or [`TicketSchemaDescription::json_schema`].
#[derive(Debug)]
pub struct TicketSchemaEntry {
    describe: fn() -> &'static TicketSchemaDescription,
}

impl TicketSchemaEntry {
    /// Wrap a type's `describe` function for registration.
    pub const fn new(describe: fn() -> &'static TicketSchemaDescription) -> Self {
        Self { describe }
    }

    /// The registered description.
    pub fn description(&self) -> &'static TicketSchemaDescription {
        (self.describe)()
    }
}

inventory::collect!(TicketSchemaEntry);

/// Every ticket schema linked into the binary, sorted by name.
pub fn all_schemas() -> Vec<&'static TicketSchemaDescription> {
    let mut all: Vec<_> = inventory::iter::<TicketSchemaEntry>()
        .map(TicketSchemaEntry::description)
        .collect();
    all.sort_by_key(|d| d.name);
    all
}

/// The frontmatter declaration the commands read: the single source of the field table.
///
/// This mirrors [`crate::model::Frontmatter`] (which holds the serde
/// derives and lives in `model.rs`); a test keeps the two key sets equal.
/// `body` is the text after the frontmatter, listed here because `update`
/// treats it as a field. The derive should move onto the real struct.
#[derive(TicketSchema)]
#[allow(dead_code)]
#[ticket(crate = "crate")]
pub struct FrontmatterSchema {
    /// ULID of the ticket; also its directory name
    #[ticket(required, since = "2.0.0")]
    id: TicketId,
    /// One-line title
    #[ticket(required, settable, since = "2.0.0")]
    title: String,
    /// Ticket type
    #[ticket(required, settable, kind = "enum", key = "type", since = "2.0.0")]
    ty: TicketType,
    /// Free-form flavour such as `user_story`
    #[ticket(settable)]
    flavour: Option<String>,
    /// Workflow category; changed by transitions only
    #[ticket(required, kind = "enum")]
    category: Category,
    /// Why the ticket is done; set by close and drop
    #[ticket(kind = "enum")]
    outcome: Option<Outcome>,
    /// low, medium, high or critical
    #[ticket(required, settable, kind = "enum")]
    priority: Priority,
    /// Story points: 1, 2, 3, 5, 8 or 13
    #[ticket(settable)]
    points: Option<Points>,
    /// Parent ticket
    #[ticket(settable)]
    parent: Option<TicketId>,
    /// Who filed the ticket
    #[ticket(required)]
    reporter: String,
    /// Who owns the ticket
    #[ticket(settable)]
    assignee: Option<String>,
    /// Creation time
    #[ticket(required)]
    created: Stamp,
    /// Time of the latest event
    #[ticket(required)]
    updated: Stamp,
    /// Story persona
    #[ticket(settable)]
    persona: Option<String>,
    /// Story capability
    #[ticket(settable)]
    capability: Option<String>,
    /// Story outcome (so that ...)
    #[ticket(settable)]
    outcome_text: Option<String>,
    /// Key that deduplicated ticket new
    idempotency_key: Option<String>,
    /// Ids from other systems, such as v1 T-0042
    #[ticket(settable, default = [])]
    aliases: Vec<String>,
    /// Labels
    #[ticket(settable, default = [])]
    labels: Vec<String>,
    /// Write-scope globs
    #[ticket(settable, default = [])]
    scope: Vec<String>,
    /// Typed links; changed by link and unlink
    #[ticket(kind = "table", default = [])]
    links: Vec<Link>,
    /// Acceptance criteria
    #[ticket(kind = "table", default = [])]
    acceptance: Vec<Acceptance>,
    /// Markdown body (the text after the frontmatter)
    #[ticket(settable)]
    body: String,
}

/// Every frontmatter field, in file order, derived from [`FrontmatterSchema`].
pub static FIELDS: LazyLock<Vec<FieldDescription>> = LazyLock::new(|| {
    FrontmatterSchema::describe()
        .fields
        .iter()
        .map(|f| FieldDescription {
            name: f.key,
            kind: field_kind(f),
            optional: !f.required,
            settable: f.settable,
            doc: f.doc,
        })
        .collect()
});

fn field_kind(f: &TicketFieldDescription) -> FieldKind {
    match f.kind {
        TicketFieldKind::List => FieldKind::List,
        TicketFieldKind::Table => FieldKind::Objects,
        TicketFieldKind::Enum => FieldKind::Choice(match f.inner_type() {
            "TicketType" => TicketType::NAMES,
            "Category" => Category::NAMES,
            "Outcome" => Outcome::NAMES,
            "Priority" => Priority::NAMES,
            other => unreachable!("enum field of unknown type {other}"),
        }),
        TicketFieldKind::Scalar => match f.inner_type() {
            "Points" => FieldKind::Points,
            "TicketId" => FieldKind::TicketRef,
            "Stamp" => FieldKind::Instant,
            _ => FieldKind::Text,
        },
    }
}

/// The description of `name`, if it is a field.
pub fn field(name: &str) -> Option<&'static FieldDescription> {
    FIELDS.iter().find(|d| d.name == name)
}

/// The names `ticket update --set` accepts.
pub fn settable_names() -> Vec<&'static str> {
    FIELDS
        .iter()
        .filter(|d| d.settable)
        .map(|d| d.name)
        .collect()
}

/// A markdown table of the fields, for generated documentation.
pub fn docs_table() -> String {
    let mut out = String::from(
        "| Field | Type | Required | Settable | Description |\n|---|---|---|---|---|\n",
    );
    for d in FIELDS.iter() {
        let ty = match d.kind {
            FieldKind::Text => "text".to_owned(),
            FieldKind::Choice(names) => names.join(" \\| "),
            FieldKind::Points => "points".to_owned(),
            FieldKind::List => "list".to_owned(),
            FieldKind::TicketRef => "ticket id".to_owned(),
            FieldKind::Instant => "RFC 3339".to_owned(),
            FieldKind::Objects => "objects".to_owned(),
        };
        let _ = writeln!(
            out,
            "| `{}` | {ty} | {} | {} | {} |",
            d.name,
            if d.optional { "no" } else { "yes" },
            if d.settable { "yes" } else { "no" },
            d.doc
        );
    }
    out
}

fn strings(v: &[String]) -> toml::Value {
    toml::Value::Array(v.iter().cloned().map(toml::Value::String).collect())
}

fn opt_text(v: Option<&String>) -> Option<toml::Value> {
    v.cloned().map(toml::Value::String)
}

/// The current value of a settable field of `t`, as a TOML value (`None` when unset).
pub fn get_field(t: &Ticket, name: &str) -> Option<toml::Value> {
    let fm = &t.front;
    let list = |v: &Vec<String>| (!v.is_empty()).then(|| strings(v));
    match name {
        "title" => Some(toml::Value::String(fm.title.clone())),
        "type" => Some(toml::Value::String(fm.ty.to_string())),
        "flavour" => opt_text(fm.flavour.as_ref()),
        "priority" => Some(toml::Value::String(fm.priority.to_string())),
        "points" => fm.points.map(|p| toml::Value::Integer(i64::from(p.get()))),
        "parent" => fm.parent.map(|p| toml::Value::String(p.to_string())),
        "assignee" => opt_text(fm.assignee.as_ref()),
        "persona" => opt_text(fm.persona.as_ref()),
        "capability" => opt_text(fm.capability.as_ref()),
        "outcome_text" => opt_text(fm.outcome_text.as_ref()),
        "aliases" => list(&fm.aliases),
        "labels" => list(&fm.labels),
        "scope" => list(&fm.scope),
        "body" => (!t.body.is_empty()).then(|| toml::Value::String(t.body.clone())),
        _ => None,
    }
}

fn want_text(name: &str, v: &toml::Value) -> Result<String, String> {
    v.as_str()
        .map(str::to_owned)
        .ok_or_else(|| format!("field `{name}` expects text"))
}

fn want_list(name: &str, v: &toml::Value) -> Result<Vec<String>, String> {
    let arr = v
        .as_array()
        .ok_or_else(|| format!("field `{name}` expects a list of text"))?;
    arr.iter().map(|x| want_text(name, x)).collect()
}

/// Set a settable field of `t` from a TOML value (`None` unsets an optional field).
///
/// # Errors
///
/// A message when the field is unknown, not settable here, required but unset,
/// or the value has the wrong type or spelling.
pub fn set_field(t: &mut Ticket, name: &str, value: Option<&toml::Value>) -> Result<(), String> {
    let desc = field(name).ok_or_else(|| format!("unknown field `{name}`"))?;
    if !desc.settable {
        return Err(format!("field `{name}` cannot be set directly"));
    }
    let Some(v) = value else {
        if !desc.optional {
            return Err(format!("field `{name}` is required and cannot be unset"));
        }
        unset(t, name);
        return Ok(());
    };
    let fm = &mut t.front;
    match name {
        "title" => fm.title = want_text(name, v)?,
        "type" => {
            fm.ty = want_text(name, v)?
                .parse()
                .map_err(|e: crate::model::ParseEnumError| e.to_string())?;
        }
        "flavour" => fm.flavour = Some(want_text(name, v)?),
        "priority" => {
            fm.priority = want_text(name, v)?
                .parse()
                .map_err(|e: crate::model::ParseEnumError| e.to_string())?;
        }
        "points" => {
            let n = v
                .as_integer()
                .ok_or_else(|| "field `points` expects an integer".to_owned())?;
            let n = u8::try_from(n)
                .map_err(|_| format!("points must be one of 1, 2, 3, 5, 8, 13 (got {n})"))?;
            fm.points = Some(Points::new(n).map_err(|e| e.to_string())?);
        }
        "parent" => {
            fm.parent = Some(
                want_text(name, v)?
                    .parse::<TicketId>()
                    .map_err(|e| e.to_string())?,
            );
        }
        "assignee" => fm.assignee = Some(want_text(name, v)?),
        "persona" => fm.persona = Some(want_text(name, v)?),
        "capability" => fm.capability = Some(want_text(name, v)?),
        "outcome_text" => fm.outcome_text = Some(want_text(name, v)?),
        "aliases" => fm.aliases = want_list(name, v)?,
        "labels" => fm.labels = want_list(name, v)?,
        "scope" => fm.scope = want_list(name, v)?,
        "body" => t.body = crate::model::normalize_body(&want_text(name, v)?),
        other => return Err(format!("field `{other}` cannot be set directly")),
    }
    Ok(())
}

fn unset(t: &mut Ticket, name: &str) {
    let fm = &mut t.front;
    match name {
        "flavour" => fm.flavour = None,
        "points" => fm.points = None,
        "parent" => fm.parent = None,
        "assignee" => fm.assignee = None,
        "persona" => fm.persona = None,
        "capability" => fm.capability = None,
        "outcome_text" => fm.outcome_text = None,
        "aliases" => fm.aliases.clear(),
        "labels" => fm.labels.clear(),
        "scope" => fm.scope.clear(),
        "body" => t.body.clear(),
        _ => {}
    }
}

/// Parse command-line text for field `name` into a TOML value (`None` for empty text on optional fields).
///
/// Lists split on commas; choices and points are validated here so the
/// message names the accepted spellings.
///
/// # Errors
///
/// A message when the field is unknown or not settable, or the text does not parse.
pub fn parse_text_value(name: &str, text: &str) -> Result<Option<toml::Value>, String> {
    let desc = field(name).ok_or_else(|| {
        format!(
            "unknown field `{name}`; settable fields: {}",
            settable_names().join(", ")
        )
    })?;
    if !desc.settable {
        return Err(format!(
            "field `{name}` cannot be set with update; settable fields: {}",
            settable_names().join(", ")
        ));
    }
    if text.is_empty() && desc.optional {
        return Ok(None);
    }
    let v = match desc.kind {
        FieldKind::Text | FieldKind::TicketRef => toml::Value::String(text.to_owned()),
        FieldKind::Choice(names) => {
            if !names.contains(&text) {
                return Err(format!(
                    "`{text}` is not valid for `{name}`; expected one of: {}",
                    names.join(", ")
                ));
            }
            toml::Value::String(text.to_owned())
        }
        FieldKind::Points => toml::Value::Integer(i64::from(
            text.parse::<Points>().map_err(|e| e.to_string())?.get(),
        )),
        FieldKind::List => strings(
            &text
                .split(',')
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(str::to_owned)
                .collect::<Vec<_>>(),
        ),
        FieldKind::Instant | FieldKind::Objects => {
            return Err(format!("field `{name}` cannot be set with update"));
        }
    };
    Ok(Some(v))
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::model::{Frontmatter, LinkKind};

    fn full_frontmatter() -> Frontmatter {
        let id = TicketId::mint();
        let stamp: Stamp = "2026-10-02T14:03:11Z".parse().expect("stamp");
        let s = || Some("x".to_owned());
        let v = || vec!["x".to_owned()];
        Frontmatter {
            id,
            title: "t".into(),
            ty: TicketType::NAMES[0].parse().expect("type"),
            flavour: s(),
            category: Category::NAMES[0].parse().expect("category"),
            outcome: Some(Outcome::NAMES[0].parse().expect("outcome")),
            priority: Priority::NAMES[0].parse().expect("priority"),
            points: Some(Points::new(1).expect("points")),
            parent: Some(id),
            reporter: "r".into(),
            assignee: s(),
            created: stamp,
            updated: stamp,
            persona: s(),
            capability: s(),
            outcome_text: s(),
            idempotency_key: s(),
            aliases: v(),
            labels: v(),
            scope: v(),
            links: vec![Link {
                kind: LinkKind::NAMES[0].parse().expect("link kind"),
                target: id,
            }],
            acceptance: vec![Acceptance {
                text: "a".into(),
                bound: false,
            }],
        }
    }

    #[test]
    fn mirror_keys_equal_serialized_frontmatter_keys() {
        let value = toml::Value::try_from(full_frontmatter()).expect("serialize");
        let real: BTreeSet<String> = value.as_table().expect("table").keys().cloned().collect();
        let mirror: BTreeSet<String> = FrontmatterSchema::describe()
            .fields
            .iter()
            .filter(|f| f.key != "body")
            .map(|f| f.key.to_owned())
            .collect();
        assert_eq!(real, mirror);
    }

    #[test]
    fn description_lists_every_field_with_doc_and_default() {
        let d = FrontmatterSchema::describe();
        assert_eq!(d.name, "FrontmatterSchema");
        assert!(!d.doc.is_empty());
        assert_eq!(d.fields.len(), 23);
        assert!(d.fields.iter().all(|f| !f.doc.is_empty()));
        let labels = d.fields.iter().find(|f| f.key == "labels").expect("labels");
        assert_eq!(labels.default_toml, Some("[]"));
        assert_eq!(labels.type_name, "Vec<String>");
        let id = d.fields.iter().find(|f| f.key == "id").expect("id");
        assert!(id.required);
        assert_eq!(id.since, Some("2.0.0"));
        assert!(d.fields.iter().any(|f| f.key == "type"));
    }

    #[test]
    fn json_schema_has_one_property_per_field() {
        let schema = FrontmatterSchema::json_schema();
        let props = schema
            .get("properties")
            .and_then(|p| p.as_object())
            .expect("properties");
        assert_eq!(props.len(), FrontmatterSchema::describe().fields.len());
        let required = schema
            .get("required")
            .and_then(|r| r.as_array())
            .expect("required");
        assert!(required.iter().any(|r| r == "title"));
    }

    #[test]
    fn registry_lists_the_schema() {
        assert!(all_schemas().iter().any(|d| d.name == "FrontmatterSchema"));
    }

    #[test]
    fn docs_table_has_a_row_per_field() {
        let table = FrontmatterSchema::describe().docs_table();
        assert_eq!(table.lines().count(), 2 + 23);
    }

    #[test]
    fn field_table_marks_settable_names() {
        assert!(settable_names().contains(&"title"));
        assert!(!settable_names().contains(&"id"));
        assert!(matches!(
            field("type").map(|f| f.kind),
            Some(FieldKind::Choice(_))
        ));
    }
}
