//! SPIKE (~9R52NCF, epic ~AYNV7BN): the compile-time story of D107 on one TODO001-shaped rule.
//!
//! Additive and self-contained: the capability matrix ([`caps`], a re-export of
//! `gob-caps`), [`RuleDef`], the [`FileRule`] host-trait form, and one example rule
//! (`todo001`) declared with the `#[rule]` attribute. Nothing here is used by production code;
//! the old `#[derive(Rule)]` is untouched. Do not build on this module: the migration tickets
//! replace it.

pub mod caps;
mod todo001;

use std::marker::PhantomData;

pub use gob_macros::rule_spike as rule;
pub use todo001::{Todo001, todo001_demo_host};

/// Finding severity (spike copy; production uses `crate::Severity`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Severity {
    /// Fails the gate.
    Error,
    /// Reported.
    Warn,
    /// Informational.
    Advisory,
}

/// Polarity class of a rule (spike copy).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Polarity {
    /// P+.
    Pplus,
    /// P-.
    Pminus,
    /// P0.
    P0,
    /// Pn.
    Pn,
    /// Pc.
    Pc,
}

/// Whether a rule judges one file or the repository (spike copy).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope {
    /// One file at a time: implement [`FileRule`].
    File,
    /// The whole repository: implement [`RepoRule`].
    Repo,
}

/// What kind of fix a rule offers (spike copy).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Fix {
    /// A human fixes it.
    Manual,
    /// A deterministic edit.
    Deterministic,
    /// An edit verified by a commit-time command.
    VerifyCommit,
    /// A fix-it suggestion.
    FixIt,
}

/// Which files a rule applies to; maps 1:1 onto GRL `lang *`, `lang [..]`, `lang -`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Applies {
    /// Every language that supplies the capabilities.
    Universal {
        /// Capabilities the rule reads.
        needs: &'static [caps::Capability],
        /// Lowest fidelity the rule accepts.
        min_fidelity: caps::Fidelity,
    },
    /// Only the named languages.
    Languages {
        /// The languages.
        langs: &'static [caps::Lang],
        /// Capabilities the rule reads.
        needs: &'static [caps::Capability],
        /// Lowest fidelity the rule accepts.
        min_fidelity: caps::Fidelity,
    },
    /// Not about files in a language (ledger, release, config).
    Project,
}

/// The declared, static description of one rule, generated by `#[rule]`.
#[derive(Debug)]
pub struct RuleDef {
    /// Rule id, `FAMILY` plus three digits.
    pub id: &'static str,
    /// Lowercase kebab-case slug.
    pub slug: &'static str,
    /// Default severity.
    pub severity: Severity,
    /// Polarity class.
    pub polarity: Polarity,
    /// Whether the rule must account for the subjects it measured.
    pub must_measure: bool,
    /// File or repo scope.
    pub scope: Scope,
    /// Fix kind.
    pub fix: Fix,
    /// Applicability declaration.
    pub applies: Applies,
    /// Cache version.
    pub version: u32,
    /// First release carrying the rule.
    pub since: &'static str,
    /// The colocated `.md` page, `include_str!`d by the macro.
    pub doc: &'static str,
}

impl RuleDef {
    /// Placeholder the macro emits after reporting an error, so one mistake is one diagnostic.
    #[doc(hidden)]
    pub const POISONED: RuleDef = RuleDef {
        id: "POISONED",
        slug: "poisoned",
        severity: Severity::Advisory,
        polarity: Polarity::P0,
        must_measure: false,
        scope: Scope::File,
        fix: Fix::Manual,
        applies: Applies::Project,
        version: 0,
        since: "0.0.0",
        doc: "",
    };
}

/// A declared rule; implemented by `#[rule]` only.
pub trait Rule {
    /// The static description of this rule.
    const DEF: &'static RuleDef;
}

/// A finding emitted through [`Out`] (spike shape).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SpikeFinding {
    /// The id stamped by [`Out`], never chosen by the rule body.
    pub rule: &'static str,
    /// Byte offset of the finding.
    pub offset: usize,
    /// Message.
    pub message: String,
}

/// Typed sink that stamps `R`'s id on every finding, so a rule cannot emit another rule's id.
pub struct Out<'a, R> {
    sink: &'a mut Vec<SpikeFinding>,
    rule: PhantomData<R>,
}

impl<'a, R: Rule> Out<'a, R> {
    /// A sink appending to `sink`.
    pub fn new(sink: &'a mut Vec<SpikeFinding>) -> Self {
        Self {
            sink,
            rule: PhantomData,
        }
    }

    /// Record a finding at `offset`, stamped with `R`'s id.
    pub fn fire(&mut self, offset: usize, message: impl Into<String>) {
        self.sink.push(SpikeFinding {
            rule: R::DEF.id,
            offset,
            message: message.into(),
        });
    }
}

/// The per-file context a [`FileRule`] reads, generic over the product host `P`.
pub struct FileCx<'a, P: ?Sized> {
    /// The product host that supplies facts.
    pub host: &'a P,
    /// File text.
    pub text: &'a str,
}

/// A rule judging one file against host `P`; chosen by `scope = File`.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is declared `scope = File` but does not implement `FileRule<{P}>`",
    note = "write `impl<P: ?Sized + YourHost> FileRule<P> for {Self}`, where `host = YourHost` in `#[rule(..)]`"
)]
pub trait FileRule<P: ?Sized>: Rule {
    /// Examine one file, emitting findings through `out`.
    fn check(&self, cx: &FileCx<'_, P>, out: &mut Out<'_, Self>)
    where
        Self: Sized;
}

/// A rule judging the whole repository against host `P`; chosen by `scope = Repo`.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is declared `scope = Repo` but does not implement `RepoRule<{P}>`"
)]
pub trait RepoRule<P: ?Sized>: Rule {
    /// Examine the repository, emitting findings through `out`.
    fn check(&self, host: &P, out: &mut Out<'_, Self>)
    where
        Self: Sized;
}

/// Subject accounting a `must_measure = true` rule must provide.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is declared `must_measure = true` but does not implement `Measured<{P}>`"
)]
pub trait Measured<P: ?Sized>: RepoRule<P> {
    /// How many subjects the rule examined.
    fn subjects(&self, host: &P) -> usize;
}

/// The product-side bind: instantiating this for a rule and a host is the "does this product
/// host that rule" check (an unsatisfied bound is a compile error at the product's list).
pub fn run_file<R: FileRule<P> + Rule, P: ?Sized>(
    rule: &R,
    host: &P,
    text: &str,
) -> Vec<SpikeFinding> {
    let mut found = Vec::new();
    rule.check(&FileCx { host, text }, &mut Out::new(&mut found));
    found
}

/// The host trait the example rule evaluates against (stands in for `ObligationHost`).
pub trait ObligationHost {
    /// Byte offsets and text of every comment in `text`.
    fn comments<'t>(&self, text: &'t str) -> Vec<(usize, &'t str)>;
    /// True when the comment at `offset` is owned by a `frob:todo` directive.
    fn owned_by_todo(&self, text: &str, offset: usize) -> bool;
}
