//! Renderers: one module per generated kind, all pure functions of inventories.

pub mod artifacts;
pub mod cli;
pub mod config;
pub mod directives;
pub mod rules;
pub mod schemas;

/// Header comment of every generated markdown file.
pub fn md_header(kind: &str) -> String {
    format!("<!-- generated by cargo dev gen {kind}; do not edit -->\n")
}

/// Escape a markdown table cell: pipes escaped, line breaks flattened.
pub fn cell(text: &str) -> String {
    text.trim().replace('|', "\\|").replace(['\r', '\n'], " ")
}

/// Pretty JSON with a `$comment` header field and a trailing newline.
pub fn json_file(kind: &str, mut value: serde_json::Value) -> String {
    if let Some(obj) = value.as_object_mut() {
        obj.insert(
            "$comment".to_owned(),
            format!("generated by cargo dev gen {kind}; do not edit").into(),
        );
    }
    let mut text = serde_json::to_string_pretty(&value)
        .unwrap_or_else(|_| unreachable!("a serde_json Value always serializes"));
    text.push('\n');
    text
}
