"""`ctest --show-only=json-v1` collection, one already-configured build
directory per discovered `CMakeLists.txt` project (T-0587) -- split out of
`frob.testing._collect` (T-1074) as its own self-contained per-language
collector; `_collect.py` re-imports every name here so `from
frob.testing._collect import ...` call sites (tests, `frob.testing.__init__`)
keep resolving unchanged."""
# frob:ticket T-1074
# frob:ticket T-0587
# frob:ticket T-0886
# frob:waive INV006 reason="T-0585 INV006 first-turn-on pool: this file's exclusivity- \
# vocabulary hit is source-level design-rationale/scope-cut prose (a docstring \
# describing already-implemented internal behavior, verifiable by reading the code it \
# annotates) rather than a separate cross-module contract needing its own tracked \
# invariant; carried verbatim from the pre-split src/frob/testing/_collect.py waiver \
# (T-1074) rather than re-derived"

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
from pathlib import Path

from typani import Err, Ok
from typani.result import Result

from frob.excludes import load_exclude_globs
from frob.gitio import run_argv
from frob.logging import get_logger
from frob.testing._collect_shared import (
    _COLLECT_TIMEOUT_S,
    _CTEST_CACHE_REL,
    _load_cache,
    _prune_dirnames,
    _store_cache,
)
from frob.testing._models import CollectedTests
from frob.testing._runners import TestingError

_log = get_logger(__name__)

_CTEST_BUILD_DIRNAME = "build"

# `add_test(<name> "<command>" ...)`, the canonical positional form ctest
# ALWAYS normalizes both the `add_test(NAME ... COMMAND ...)` keyword form
# and the legacy positional form down to in a generated `CTestTestfile.cmake`
# (verified empirically: CMake 3.22 emits this exact shape for both input
# spellings) -- one regex is enough to cover both source conventions.
_ADD_TEST_RE = re.compile(r'add_test\(([^\s()]+)\s+"([^"]+)"')

# `gtest_discover_tests()` (CMake's bundled GoogleTest module) does not
# write its per-case `add_test()` calls into `CTestTestfile.cmake` directly
# -- it writes a small bootstrap that `include()`s a sibling
# `<target>_tests.cmake` file (regenerated by a POST_BUILD custom command
# after the test binary is built), which DOES hold one real
# `add_test(<TestSuite.TestCase> "<path/to/binary>" ...)` line per
# discovered gtest case. Following one level of `include("...")` is enough
# to reach that generated file without hand-rolling a cmake interpreter.
_INCLUDE_RE = re.compile(r'include\("([^"]+)"\)')

# The object-file path convention CMake's Makefiles AND Ninja generators
# both use (`CMakeFiles/<target>.dir/<relative-source-path>.o`), the only
# generators this repo's own build (see `Makefile`'s `make core`) or a
# typical CI runner uses -- present in `compile_commands.json`'s `command`
# field (`output` on newer CMake, not relied upon since it is absent before
# CMake 3.20). An unrecognized generator's differently-shaped object path
# simply never matches, degrading to "no source mapping" for that entry
# rather than a wrong guess.
_OBJECT_TARGET_RE = re.compile(r"CMakeFiles/([^/]+)\.dir/")


def _find_cmake_projects(root: Path) -> list[Path]:
    """Directories holding a `CMakeLists.txt`, exclusions pruned (mirrors
    `frob.testing._collect_rust._find_crates`'s Cargo.toml walk). A `build/`
    directory (a previous cmake configure's output, which typically nests a
    COPY of its parent's `CMakeLists.txt`) is never descended into as a
    project root of its own -- it is only inspected later, via
    `_ctest_build_dir`, as the conventional build directory belonging to
    the project that owns it."""
    exclude_globs = load_exclude_globs(root)
    found: list[Path] = []
    # frob:waive WALK001 reason="needs per-directory build/ pruning the file-only iter_files/walk_pruned API cannot express; already prunes via _prune_dirnames using frob.excludes primitives"  # noqa: E501
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = _prune_dirnames(Path(dirpath), root, dirnames, exclude_globs)
        dir_path = Path(dirpath)
        if dir_path.name == _CTEST_BUILD_DIRNAME:
            dirnames[:] = []
            continue
        if "CMakeLists.txt" in filenames:
            found.append(dir_path)
    return sorted(found)


def _ctest_build_dir(project_dir: Path) -> Path | None:
    """The conventional `build/` directory for `project_dir` if it already
    holds a generated `CTestTestfile.cmake`, else `None`. Collection
    deliberately never runs `cmake` itself to configure a fresh build dir
    (too heavy and too project-specific for a collection pass, unlike
    `cargo test --list` which builds implicitly) -- it only lists a build
    that has already been configured (T-0587)."""
    candidate = project_dir / _CTEST_BUILD_DIRNAME / "CTestTestfile.cmake"
    return candidate.parent if candidate.exists() else None


def _find_ctest_dirs(root: Path) -> list[Path]:
    """Every already-configured ctest build directory discovered under `root`."""
    build_dirs: list[Path] = []
    for project_dir in _find_cmake_projects(root):
        build_dir = _ctest_build_dir(project_dir)
        if build_dir is not None:
            build_dirs.append(build_dir)
    return sorted(build_dirs)


# frob:waive EXHAUST003 reason="T-1402: EXHAUST001 narrowed to fire for an own \
# ambiguous bare re-raise; this leaked Unknown traces to an unresolved callee instead \
# (the demoted case). T-1062: leaked Unknown traces to _INCLUDE_RE.findall/ \
# _ADD_TEST_RE.findall, compiled-regex scans over already-caught read_text() output; \
# regex operations over an already-decoded str cannot raise"
def _parse_ctest_command_map(build_dir: Path) -> dict[str, str]:
    """`test name -> raw command path` for every `add_test()` ctest can see
    in `build_dir`, scanning `CTestTestfile.cmake` and any file it
    `include()`s one level deep (the `gtest_discover_tests()` generated-file
    idiom, see `_INCLUDE_RE`). A best-effort regex scan, not a cmake
    interpreter -- returns a partial (or empty) map on anything it cannot
    confidently parse, never raises; callers treat a missing name as "no
    source mapping available for this test", never a hard failure."""
    mapping: dict[str, str] = {}
    testfile = build_dir / "CTestTestfile.cmake"
    try:
        content = testfile.read_text()
    except OSError:
        return mapping
    to_scan = [content]
    for inc in _INCLUDE_RE.findall(content):
        inc_path = Path(inc)
        if not inc_path.is_absolute():
            inc_path = build_dir / inc_path
        try:
            to_scan.append(inc_path.read_text())
        except OSError:
            continue
    for text in to_scan:
        for name, cmd in _ADD_TEST_RE.findall(text):
            mapping.setdefault(name, cmd)
    return mapping


def _cpp_target_sources(root: Path, build_dir: Path) -> dict[str, frozenset[str]]:
    """`cmake target name -> its compiled source file(s)` (root-relative
    posix paths), parsed from `compile_commands.json`
    (`CMAKE_EXPORT_COMPILE_COMMANDS=ON`) if the project was configured with
    it. Empty when the file is missing, unparseable, or the generator's
    object-path convention does not match `_OBJECT_TARGET_RE` -- callers
    treat an empty/absent mapping the same as "cannot be source-accurate
    for this target", never an error (most projects do not turn this cmake
    option on, and that must not fail collection)."""
    cc_path = build_dir / "compile_commands.json"
    try:
        entries = json.loads(cc_path.read_text())
    except Exception:
        return {}
    if not isinstance(entries, list):
        return {}
    result: dict[str, set[str]] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        file_field = entry.get("file")
        if not isinstance(file_field, str):
            continue
        haystack = entry.get("output")
        if not isinstance(haystack, str):
            haystack = entry.get("command", "")
        if not isinstance(haystack, str):
            continue
        match = _OBJECT_TARGET_RE.search(haystack)
        if match is None:
            continue
        target = match.group(1)
        file_path = Path(file_field)
        if not file_path.is_absolute():
            directory = entry.get("directory", str(build_dir))
            file_path = Path(directory) / file_path
        try:
            rel = file_path.resolve().relative_to(root.resolve()).as_posix()
        except (OSError, ValueError):
            continue
        result.setdefault(target, set()).add(rel)
    return {target: frozenset(files) for target, files in result.items()}


def _cpp_test_source(
    name: str,
    command_map: dict[str, str],
    target_sources: dict[str, frozenset[str]],
) -> str | None:
    """The single real source file `name` (a ctest test name) can be traced
    to, or `None` when the mapping is missing or ambiguous. Source-accurate
    ONLY when the test's registered executable resolves (by target-name
    stem) to EXACTLY ONE compiled source file -- a binary built from
    multiple `.cpp` files cannot be attributed to one of them without
    per-case symbol/line information this function deliberately does not
    attempt (that would risk a wrong guess; `None` here means the caller
    falls back to the build-dir anchor instead, loudly)."""
    command = command_map.get(name)
    if command is None:
        return None
    target = Path(command).stem
    sources = target_sources.get(target)
    if sources is None or len(sources) != 1:
        return None
    return next(iter(sources))


def _cpp_node_id(source: str, name: str) -> str:
    """`source::name` with `name`'s dots (a gtest `TestSuite.TestCase` name)
    normalized to `::`, mirroring `frob.gates._symref_to_nodeid`'s own
    dot-to-`::` qualname transform on the `frob:tests` directive side --
    without this, a directive written `path::TestSuite::TestCase` could
    never match a collected id that still spelled it `TestSuite.TestCase`."""
    return f"{source}::{name.replace('.', '::')}"


def _ctest_content_key(root: Path, build_dirs: list[Path]) -> str:
    """Sha256 over every discovered build dir's `CTestTestfile.cmake` AND
    `compile_commands.json` content (T-0886 added the latter as a real
    collection input, once the source-accurate mapping started reading it)
    -- hashing both is sufficient to invalidate the cache on any test-set
    OR source-mapping change (a reconfigure, an added/removed `add_test()`,
    a source file added to/removed from a target) without needing to hash
    the whole source tree."""
    hasher = hashlib.sha256()
    testfiles = sorted(
        f
        for d in build_dirs
        for f in (d / "CTestTestfile.cmake", d / "compile_commands.json")
    )
    for path in testfiles:
        try:
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
        except OSError as exc:
            _log.warning("collect_cpp_tests: could not read %s: %s", path, exc)
            continue
        rel = path.relative_to(root).as_posix()
        hasher.update(f"{rel}:{digest}\n".encode())
    return hasher.hexdigest()


def _parse_ctest_json(stdout: str, build_dir: Path) -> Result[list[str], TestingError]:
    """Every registered test `name` from a `ctest --show-only=json-v1`
    payload (the documented CMake json-v1 schema: `{"tests": [{"name":
    ...}, ...]}`). An unparseable payload is a genuine `Err`, not a silent
    empty list -- unlike a missing tool, a malformed payload from an
    installed ctest means something is actually broken."""
    try:
        doc = json.loads(stdout)
    except ValueError as exc:
        _log.error(
            "collect_cpp_tests: unparseable ctest json in %s: %s", build_dir, exc
        )
        return Err(TestingError.CollectFailed)
    names = [t["name"] for t in doc.get("tests", []) if isinstance(t.get("name"), str)]
    return Ok(names)


# frob:waive ARCH103 reason="T-0977: ctest-availability-guarded subprocess wrapper -- \
# the missing-tool degrade-with-warning IS the honest-vacuous- pass behavior T-0587 \
# documents this function for, not a separate concern"
def _run_ctest_list(build_dir: Path) -> Result[list[str], TestingError]:
    """Spawn `ctest --test-dir <build_dir> --show-only=json-v1`. Degrades to
    an empty, `Ok` result (with a warning, not a hard failure) when `ctest`
    is not on PATH -- a repo with no C/C++ toolchain installed must not
    fail collection for every OTHER language (T-0587)."""
    if shutil.which("ctest") is None:
        _log.warning(
            "collect_cpp_tests: ctest not found on PATH, skipping %s", build_dir
        )
        return Ok([])
    spawned = run_argv(
        ["ctest", "--test-dir", str(build_dir), "--show-only=json-v1"],
        cwd=build_dir,
        timeout_s=_COLLECT_TIMEOUT_S,
    )
    if spawned.is_err:
        _log.error("collect_cpp_tests: ctest failed to spawn in %s", build_dir)
        return Err(TestingError.CollectFailed)
    result = spawned.danger_ok
    if result.returncode != 0:
        _log.error(
            "collect_cpp_tests: ctest --show-only exited %d in %s: %s",
            result.returncode,
            build_dir,
            result.stderr[-500:],
        )
        return Err(TestingError.CollectFailed)
    return _parse_ctest_json(result.stdout, build_dir)


def _collect_cpp_build_dir(
    root: Path, build_dir: Path
) -> Result[set[str], TestingError]:
    """One configured build dir's ctest node ids -- source-mapped where
    `_cpp_test_source` resolves an unambiguous compiled source, loudly
    build-dir-anchored otherwise (T-0886; see `collect_cpp_tests`)."""
    listed = _run_ctest_list(build_dir)
    if listed.is_err:
        return Err(listed.danger_err)
    rel_build = build_dir.relative_to(root).as_posix()
    command_map = _parse_ctest_command_map(build_dir)
    target_sources = _cpp_target_sources(root, build_dir)
    node_ids: set[str] = set()
    mapped = 0
    fell_back = 0
    for name in listed.danger_ok:
        source = _cpp_test_source(name, command_map, target_sources)
        if source is not None:
            node_ids.add(_cpp_node_id(source, name))
            mapped += 1
        else:
            node_ids.add(f"{rel_build}::{name}")
            fell_back += 1
    if fell_back:
        _log.warning(
            "collect_cpp_tests: FALLBACK -- %d/%d test(s) in %s could not "
            "be source-mapped (no unambiguous compiled source found via "
            "compile_commands.json), anchored to the build dir instead of "
            "a real source file",
            fell_back,
            mapped + fell_back,
            build_dir,
        )
    return Ok(node_ids)


# frob:doc docs/modules/testing.md#public-api
def collect_cpp_tests(root: Path) -> Result[CollectedTests, TestingError]:
    """`ctest --test-dir <dir> --show-only=json-v1` node ids for every
    already-configured CMake build directory under `root` (one holding a
    generated `CTestTestfile.cmake`, discovered from a `CMakeLists.txt`
    project root's conventional `build/` subdirectory, T-0587). Collection
    never invokes `cmake` itself to configure a fresh build -- only an
    already-configured one is listed, mirroring `collect_rust_tests`'s
    per-crate shape as closely as ctest's own model allows.

    SOURCE-ACCURATE where it can be, honestly degraded where it cannot
    (T-0886): investigation found `ctest --show-only=json-v1`'s own
    `backtrace` field anchors to the CMake SCRIPT location of the
    `add_test()` call (almost always `CMakeLists.txt` itself, or a
    `gtest_discover_tests()` call site) -- never the real test source file
    -- so it cannot answer the source-accuracy question at all, on any
    CMake version. What DOES work: `CTestTestfile.cmake` (and any
    `gtest_discover_tests()`-generated file it `include()`s, T-0886)
    literally spells out each test's executable path via `add_test(<name>
    "<path>")`; cross-referencing that executable's cmake TARGET NAME
    against `compile_commands.json` (`_cpp_target_sources`) gives the
    target's real compiled source file(s) whenever the project was
    configured with `CMAKE_EXPORT_COMPILE_COMMANDS=ON`. When a target
    compiles from exactly ONE source file -- the common shape for a
    dedicated test binary, including every gtest case
    `gtest_discover_tests()` registers against it -- that source file IS
    the test's real location, and the node id anchors there
    (`_cpp_node_id`) exactly like the python/rust/ts collectors already do
    for their own languages. A test whose executable cannot be resolved to
    exactly one compiled source (no `compile_commands.json`, an unmatched
    generator, or a multi-source binary that would be a guess) falls back
    to the old build-dir anchor (`<build_dir>::<test name>`) -- loudly: one
    `collect_cpp_tests: FALLBACK` warning per build dir naming how many of
    its tests could not be source-mapped, never a silent downgrade. Cached
    on every discovered `CTestTestfile.cmake` + `compile_commands.json`
    content hash. Degrades to an empty, `Ok` result (with a warning, never
    a hard failure) when `ctest` is not on PATH."""
    build_dirs = _find_ctest_dirs(root)
    key = _ctest_content_key(root, build_dirs)
    cache_path = root / _CTEST_CACHE_REL
    cached = _load_cache(cache_path, key)
    if cached is not None:
        _log.debug("collect_cpp_tests: cache hit, %d node id(s)", len(cached))
        return Ok(CollectedTests(node_ids=cached))

    node_ids: set[str] = set()
    for build_dir in build_dirs:
        collected = _collect_cpp_build_dir(root, build_dir)
        if collected.is_err:
            return Err(collected.danger_err)
        node_ids |= collected.danger_ok

    frozen = frozenset(node_ids)
    _store_cache(cache_path, key, frozen)
    _log.info("collect_cpp_tests: collected %d node id(s)", len(frozen))
    return Ok(CollectedTests(node_ids=frozen))


__all__ = [
    "collect_cpp_tests",
]
