//! The whole newcomer loop on a fresh repository: init, ticket, work, edit, check, test, evidence, land.
// frob:ticket 01M4069YW2EF551WF2J7R0EMJ4

use std::path::{Path, PathBuf};
use std::process::Output;
use std::time::Duration;

use gob_exec::{Limits, Outcome, Program, Runner, Spec};
use serde_json::Value;

mod common;

const MANIFEST: &str = "[package]\nname = \"tiny\"\nversion = \"0.1.0\"\nedition = \"2021\"\n";
const LOCK: &str = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n\n[[package]]\nname = \"tiny\"\nversion = \"0.1.0\"\n";
const LIB: &str = "//! A tiny crate.\n\n/// Add two numbers.\npub fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn adds() {\n        assert_eq!(add(1, 2), 3);\n    }\n}\n";
const EDITED: &str = "//! A tiny crate.\n\n/// Add two numbers without overflow panics.\npub fn add(a: i32, b: i32) -> i32 {\n    a.wrapping_add(b)\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn adds() {\n        assert_eq!(add(1, 2), 3);\n    }\n}\n";

/// Run git in `dir`, returning trimmed stdout; a failure is a test bug.
fn git(dir: &Path, args: &[&str]) -> String {
    let spec = Spec {
        program: Program::Git,
        args: args.iter().map(|a| (*a).to_owned()).collect(),
        cwd: Some(dir.to_path_buf()),
        env: Vec::new(),
        timeout: Duration::from_secs(30),
        capture: true,
    };
    let out = Runner::new(Limits { jobs: 1 }).run(&spec).expect("run git");
    assert_eq!(
        out.status,
        Outcome::Exited(0),
        "git {args:?}: {}",
        out.stderr
    );
    out.stdout.trim().to_owned()
}

fn json(out: &Output) -> Value {
    serde_json::from_slice(&out.stdout)
        .unwrap_or_else(|e| panic!("not JSON ({e}): {}", String::from_utf8_lossy(&out.stdout)))
}

fn code(out: &Output) -> i32 {
    out.status.code().expect("exit code")
}

/// A fresh repository with one commit on `branch`, a tiny crate and no remote; worktrees land beside it inside the same temp dir.
struct Fresh {
    _tmp: tempfile::TempDir,
    root: PathBuf,
}

impl Fresh {
    fn new(branch: &str) -> Self {
        let tmp = tempfile::tempdir().expect("tempdir");
        let root = tmp.path().join("repo");
        std::fs::create_dir_all(root.join("src")).expect("mkdir");
        git(&root, &["init", "-q"]);
        git(
            &root,
            &["symbolic-ref", "HEAD", &format!("refs/heads/{branch}")],
        );
        git(&root, &["config", "user.name", "Test User"]);
        git(&root, &["config", "user.email", "test@example.com"]);
        git(&root, &["config", "core.autocrlf", "false"]);
        std::fs::write(root.join("Cargo.toml"), MANIFEST).expect("write");
        std::fs::write(root.join("Cargo.lock"), LOCK).expect("write");
        std::fs::write(root.join("src/lib.rs"), LIB).expect("write");
        std::fs::write(root.join(".gitignore"), "target/\n").expect("write");
        git(&root, &["add", "-A"]);
        git(&root, &["commit", "-q", "-m", "initial"]);
        Self { _tmp: tmp, root }
    }

    /// Run frob in `dir` with the nextest environment of the outer run scrubbed.
    fn run_in(dir: &Path, args: &[&str]) -> Output {
        let mut cmd = common::frob_command();
        cmd.current_dir(dir).env_remove("FROB_LOG");
        for (k, _) in std::env::vars() {
            if k.starts_with("NEXTEST") || k == "CARGO_TARGET_DIR" {
                cmd.env_remove(k);
            }
        }
        cmd.args(args).output().expect("run frob")
    }

    fn frob(dir: &Path, args: &[&str]) -> Output {
        let mut a = vec!["--json"];
        a.extend_from_slice(args);
        Self::run_in(dir, &a)
    }

    /// Run frob in `dir`, assert exit 0 and `ok: true`, and return the envelope.
    fn ok(dir: &Path, args: &[&str]) -> Value {
        let out = Self::frob(dir, args);
        let env = json(&out);
        assert_eq!(
            code(&out),
            0,
            "{args:?}: {}",
            String::from_utf8_lossy(&out.stdout)
        );
        assert_eq!(env["ok"], true, "{args:?}: {env}");
        assert_eq!(env["error"], Value::Null, "{args:?}: {env}");
        env
    }

    /// `frob init` (the ledger ref follows the checked-out branch), then init again and commit.
    fn init_committed(&self) {
        let env = Self::ok(&self.root, &["init"]);
        assert_eq!(env["verb"], "init");
        assert_eq!(env["data"]["config"]["created"], true);
        assert_eq!(env["data"]["gitignore"]["changed"], true);
        assert_eq!(env["data"]["gitattributes"]["changed"], true);
        assert_eq!(env["data"]["merge_driver"]["changed"], true);
        let again = Self::ok(&self.root, &["init"]);
        assert_eq!(again["data"]["config"]["created"], false, "init repeats");
        assert!(self.root.join("frob.toml").is_file());
        common::set_done_requires(&self.root, &["no_open_children"]);
        git(&self.root, &["add", "-A"]);
        git(&self.root, &["commit", "-q", "-m", "chore: frob init"]);
    }
}

/// The full loop on a repository whose default branch is `branch`.
fn full_loop(branch: &str) {
    full_loop_in(branch, false);
}

/// Switch `root` to the orphan ticket branch: `ref_mode = "orphan"`, the branch created, the config committed.
fn use_orphan_ledger(root: &Path) {
    let path = root.join("frob.toml");
    let text = std::fs::read_to_string(&path).expect("read frob.toml");
    let edited = text.replace("ref_mode = \"trunk\"", "ref_mode = \"orphan\"");
    assert_ne!(text, edited, "init materializes ref_mode = trunk");
    std::fs::write(&path, edited).expect("write frob.toml");
    Fresh::ok(root, &["ticket", "branch", "init"]);
    git(root, &["add", "-A"]);
    git(root, &["commit", "-q", "-m", "chore: ticket branch"]);
}

/// The full loop; with `orphan` the ledger lives on `frob-tickets` and the code branch stays code-only.
fn full_loop_in(branch: &str, orphan: bool) {
    let repo = Fresh::new(branch);
    let root = repo.root.as_path();
    repo.init_committed();
    if orphan {
        use_orphan_ledger(root);
    }
    let commits_before = git(root, &["rev-list", "--count", branch]);

    // ticket new
    let new = Fresh::ok(
        root,
        &[
            "ticket",
            "new",
            "--title",
            "Make add overflow-safe",
            "--acceptance",
            "Given two large numbers, when add runs, then it does not panic",
            "--scope",
            "src/**",
        ],
    );
    assert_eq!(new["verb"], "ticket.new");
    let handle = new["data"]["handle"].as_str().expect("handle").to_owned();
    let id = new["data"]["id"].as_str().expect("id").to_owned();
    assert!(handle.starts_with('~'), "handle {handle}");
    assert_eq!(new["data"]["category"], "todo");

    // work
    let work = Fresh::ok(root, &["work", &handle]);
    assert_eq!(work["verb"], "work");
    assert_eq!(work["data"]["created_worktree"], true);
    assert_eq!(work["data"]["branch"], format!("ticket/{}", &handle[1..]));
    assert_eq!(work["data"]["lease"]["scope"][0], "src/**");
    let wt = PathBuf::from(work["data"]["path"].as_str().expect("path"));
    assert!(wt.join("src/lib.rs").is_file(), "worktree has the crate");

    // edit inside the scope
    std::fs::write(wt.join("src/lib.rs"), EDITED).expect("edit");

    // check --ticket
    let check = Fresh::ok(&wt, &["check", "--ticket", &handle]);
    assert_eq!(check["verb"], "check");
    assert_eq!(check["data"]["counts"]["error"], 0);
    assert_eq!(
        check["data"]["fidelity"]["languages"]["rust"]["fidelity"],
        "F3"
    );

    // test --base <branch>
    let test = Fresh::ok(&wt, &["test", "--base", branch]);
    assert_eq!(test["verb"], "test");
    assert_eq!(test["data"]["passed"], true);
    assert_eq!(test["data"]["base"], branch);
    assert_eq!(test["data"]["executed"][0], "tests::adds");
    assert_eq!(test["data"]["touched"]["symbols"][0], "src/lib.rs::add");
    assert_eq!(test["data"]["evidence"]["ticket"], handle.as_str());

    // ticket evidence add
    let ev = Fresh::ok(
        &wt,
        &[
            "ticket",
            "evidence",
            "add",
            &handle,
            "--accepts",
            "1",
            "--provider",
            "command",
            "--ref",
            "cargo test",
        ],
    );
    assert_eq!(ev["verb"], "ticket.evidence.add");
    let rec = &ev["data"]["record"];
    assert_eq!(rec["status"], "measured");
    assert_eq!(rec["passed"], true);
    assert_eq!(rec["accepts"][0], 1);
    assert_eq!(rec["provider"], "command");

    // land: commit the work first, as the land refusal teaches
    let refused = Fresh::frob(&wt, &["land"]);
    if git(&wt, &["status", "--porcelain"]).is_empty() {
        assert_eq!(code(&refused), 0);
    } else {
        assert_eq!(code(&refused), 3, "dirty worktree refuses");
        assert_eq!(json(&refused)["error"]["code"], "E-LAND-DIRTY");
        git(&wt, &["add", "-A"]);
        git(&wt, &["commit", "-q", "-m", "feat: overflow-safe add"]);
    }
    let land = Fresh::ok(&wt, &["land"]);
    assert_eq!(land["verb"], "land");
    let land_warnings = land["warnings"].to_string();

    // base branch holds the change
    let lib = git(root, &["show", &format!("{branch}:src/lib.rs")]);
    assert!(lib.contains("wrapping_add"), "base holds the change: {lib}");
    assert_eq!(git(root, &["rev-parse", "--abbrev-ref", "HEAD"]), branch);
    assert!(
        std::fs::read_to_string(root.join("src/lib.rs"))
            .expect("read")
            .contains("wrapping_add"),
        "the primary checkout carries the change"
    );

    // ticket closed done, criterion bound
    let show = Fresh::ok(root, &["ticket", "show", &handle]);
    let fields = &show["data"]["fields"];
    assert_eq!(fields["category"], "done");
    assert_eq!(fields["outcome"], "done");
    assert_eq!(fields["acceptance"][0]["bound"], true);
    assert_eq!(show["data"]["summary"]["id"], id.as_str());

    // worktree and branch removed
    assert!(
        !wt.exists(),
        "worktree removed: {} (land warnings: {land_warnings})",
        wt.display()
    );
    let branches = git(root, &["branch", "--list", "ticket/*"]);
    assert!(branches.is_empty(), "ticket branch removed: {branches}");

    if orphan {
        // the ledger commits (new, work, evidence, close) never touched the code branch
        let commits = git(root, &["rev-list", "--count", branch]);
        let before: u32 = commits_before.parse().expect("count");
        assert_eq!(commits, (before + 1).to_string(), "only the feature commit");
        let on_code = git(root, &["ls-tree", "-r", "--name-only", branch]);
        assert!(
            !on_code.lines().any(|l| l.starts_with("tickets/")),
            "{on_code}"
        );
        let on_branch = git(root, &["ls-tree", "-r", "--name-only", "frob-tickets"]);
        assert!(
            on_branch.contains("_unfiled/make-add-overflow-safe.md"),
            "{on_branch}"
        );
        assert!(on_branch.contains(&format!(".events/{id}/")), "{on_branch}");
    }

    // ledger healthy
    let doctor = Fresh::ok(root, &["ticket", "doctor"]);
    assert_eq!(doctor["data"]["ok"], true);
    assert_eq!(doctor["data"]["issues"], Value::Array(Vec::new()));
}

#[test]
fn loop_on_main() {
    full_loop("main");
}

#[test]
fn loop_on_trunk() {
    full_loop("trunk");
}

/// Ticket-branch mode: work builds the worktree from the code branch and land succeeds with the ledger on the orphan branch.
// frob:ticket 01M4CTTSAZC93K94KNXH3WVSYM
// frob:tests crates/frob-worktree/src/work.rs::base_branch
#[test]
fn loop_with_the_ledger_on_the_orphan_branch() {
    full_loop_in("main", true);
}

/// frob:ticket 01M4069YW2EF551WF2J7R0EMJ4
/// frob:ticket 01M40FXTW5FYKQWG82PD8STDJR
/// `frob init` points `[tickets] ref` at the checked-out branch.
#[test]
fn init_points_the_ledger_ref_at_the_current_branch() {
    let repo = Fresh::new("trunk");
    Fresh::ok(&repo.root, &["init"]);
    let text = std::fs::read_to_string(repo.root.join("frob.toml")).expect("read");
    assert!(
        text.contains("ref = \"refs/heads/trunk\""),
        "init must point the ledger ref at refs/heads/trunk"
    );
}

/// `frob check` before `frob init` refuses and names `frob init` (diagnostics.md section 5, ~ANDZXZ4).
// frob:ticket 01M40FXV09GYGBH9YZZANDZXZ4
#[test]
fn check_before_init_says_to_run_init() {
    let repo = Fresh::new("main");
    let out = Fresh::run_in(&repo.root, &["--text", "check"]);
    let all = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        code(&out) != 0 && all.contains("frob init") && !all.contains("DRIFT001"),
        "~ANDZXZ4: check without frob.toml must refuse and name `frob init`, exit {} output: {all}",
        code(&out)
    );
}

/// A fresh initialized repository passes `frob check`: REF001 and TODO002 have nothing to judge (~VA936C5).
// frob:ticket 01M4069Z0HH5RV8TNPFVA936C5
#[test]
fn check_after_init_on_a_fresh_repository_passes() {
    let repo = Fresh::new("main");
    repo.init_committed();
    let out = Fresh::frob(&repo.root, &["check"]);
    assert_eq!(
        code(&out),
        0,
        "~VA936C5: {}",
        json(&out)["error"]["message"]
    );
}

/// A usage error for missing required arguments names each of them and carries a usage line.
// frob:ticket 01M40FXV4AB47ASH79KJNF3JFH
#[test]
fn usage_error_names_the_missing_arguments() {
    let repo = Fresh::new("main");
    // `ticket evidence add` takes `--ref` only for non-attestation providers (checked after parsing), so two clap-required arguments come from `milestone new`.
    let out = Fresh::frob(&repo.root, &["milestone", "new"]);
    let error = json(&out)["error"].clone();
    let msg = error["message"].as_str().expect("message").to_owned();
    assert!(
        msg.contains("--goal") && msg.contains("<VERSION>"),
        "usage error message is `{msg}`"
    );
    let remedy = error["remedy"].as_str().expect("remedy");
    assert!(remedy.contains("usage:"), "remedy is `{remedy}`");
}
