//! `release cut` end to end on temporary repositories with a ledger and a milestone.
// frob:ticket 01M4069X6S9RJWRXX3YBZ9EG10

mod common;

use std::path::Path;
use std::process::Output;
use std::time::Duration;

use gob_exec::{Limits, Outcome, Program, Runner, Spec};
use serde_json::Value;

/// A trunk-mode repository with `frob init` run and one commit.
struct Repo {
    dir: tempfile::TempDir,
}

fn git(dir: &Path, args: &[&str]) {
    let spec = Spec {
        program: Program::Git,
        args: args.iter().map(|a| (*a).to_owned()).collect(),
        cwd: Some(dir.to_path_buf()),
        env: Vec::new(),
        timeout: Duration::from_secs(30),
        capture: true,
    };
    let out = Runner::new(Limits { jobs: 1 }).run(&spec).expect("run git");
    assert_eq!(
        out.status,
        Outcome::Exited(0),
        "git {args:?}: {}",
        out.stderr
    );
}

impl Repo {
    fn new() -> Self {
        let dir = tempfile::tempdir().expect("tempdir");
        git(dir.path(), &["init", "-q"]);
        git(dir.path(), &["symbolic-ref", "HEAD", "refs/heads/main"]);
        git(dir.path(), &["config", "user.name", "Test User"]);
        git(dir.path(), &["config", "user.email", "test@example.com"]);
        git(dir.path(), &["config", "core.autocrlf", "false"]);
        let repo = Self { dir };
        assert_eq!(code(&repo.run(&["--json", "init"])), 0);
        let toml = repo.dir.path().join("frob.toml");
        let text = std::fs::read_to_string(&toml).expect("frob.toml");
        std::fs::write(
            &toml,
            text.replace("require_ci = true", "require_ci = false")
                .replace("tag = \"v{version}\"", "tag = \"{product}-v{version}\"")
                .replace("products = []", "products = [\"frob\", \"grimble\"]"),
        )
        .expect("write frob.toml");
        git(repo.dir.path(), &["add", "-A"]);
        git(repo.dir.path(), &["commit", "-q", "-m", "base"]);
        repo
    }

    fn run(&self, args: &[&str]) -> Output {
        common::frob_command()
            .current_dir(self.dir.path())
            .env_remove("FROB_LOG")
            .args(args)
            .output()
            .expect("run frob")
    }

    fn frob(&self, args: &[&str]) -> Output {
        let mut a = vec!["--json"];
        a.extend_from_slice(args);
        self.run(&a)
    }

    fn ok(&self, args: &[&str]) -> Value {
        let out = self.frob(args);
        assert_eq!(
            code(&out),
            0,
            "{args:?}: {}",
            String::from_utf8_lossy(&out.stdout)
        );
        json(&out)
    }

    fn ticket(&self, ty: &str) -> String {
        self.titled(ty, "t")
    }

    fn titled(&self, ty: &str, title: &str) -> String {
        self.ok(&["ticket", "new", "--title", title, "--type", ty])["data"]["id"]
            .as_str()
            .expect("id")
            .to_owned()
    }
}

fn json(out: &Output) -> Value {
    serde_json::from_slice(&out.stdout)
        .unwrap_or_else(|e| panic!("not JSON ({e}): {}", String::from_utf8_lossy(&out.stdout)))
}

fn code(out: &Output) -> i32 {
    out.status.code().expect("exit code")
}

const ROOT: &str = "[workspace]\nmembers = [\"crates/*\"]\n\n[workspace.package]\nversion = \"0.0.0\"\nedition = \"2024\"\n";
const A: &str = "[package]\nname = \"a\"\nversion = \"0.0.0\"\nedition = \"2024\"\n";
const LOCK: &str = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"a\"\nversion = \"0.0.0\"\n";

fn git_out(dir: &Path, args: &[&str]) -> String {
    let spec = Spec {
        program: Program::Git,
        args: args.iter().map(|a| (*a).to_owned()).collect(),
        cwd: Some(dir.to_path_buf()),
        env: Vec::new(),
        timeout: Duration::from_secs(30),
        capture: true,
    };
    let out = Runner::new(Limits { jobs: 1 }).run(&spec).expect("run git");
    assert_eq!(
        out.status,
        Outcome::Exited(0),
        "git {args:?}: {}",
        out.stderr
    );
    out.stdout.trim().to_owned()
}

fn write(repo: &Repo, rel: &str, text: &str) {
    let p = repo.dir.path().join(rel);
    std::fs::create_dir_all(p.parent().expect("parent")).expect("mkdir");
    std::fs::write(p, text).expect("write");
}

/// A workspace, a milestone with one criterion (bound unless `bound` is false) and one changelog fragment, all committed.
fn releasable(bound: bool) -> Repo {
    let repo = Repo::new();
    write(&repo, "Cargo.toml", ROOT);
    write(&repo, "crates/a/Cargo.toml", A);
    write(&repo, "crates/a/src/lib.rs", "");
    write(&repo, "Cargo.lock", LOCK);
    write(&repo, "proof.txt", "proof");
    repo.ok(&[
        "milestone",
        "new",
        "0.532.0",
        "--goal",
        "Ship",
        "--criterion",
        "only",
    ]);
    if bound {
        repo.ok(&[
            "milestone",
            "evidence",
            "add",
            "0.532.0",
            "--provider",
            "file",
            "--ref",
            "proof.txt",
            "--accepts",
            "1",
        ]);
    }
    let t = repo.ticket("task");
    write(
        &repo,
        &format!("changelog.d/{t}.added.md"),
        "frob: Added the cut.\n",
    );
    git(repo.dir.path(), &["add", "-A"]);
    git(repo.dir.path(), &["commit", "-q", "-m", "release inputs"]);
    repo
}

/// Every milestone event file concatenated.
fn milestone_events(repo: &Repo) -> String {
    let mut all = String::new();
    let mut stack = vec![repo.dir.path().join("tickets/_milestones")];
    while let Some(d) = stack.pop() {
        for e in std::fs::read_dir(&d).expect("readdir").flatten() {
            let p = e.path();
            if p.is_dir() {
                stack.push(p);
            } else {
                all.push_str(&std::fs::read_to_string(&p).expect("read"));
                all.push('\n');
            }
        }
    }
    all
}

#[test]
fn a_ready_milestone_is_cut_into_one_commit_with_tags_and_a_ledger_record() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    // frob:tests crates/frob-release/src/cut.rs::cut
    let repo = releasable(true);
    let d = repo.dir.path();
    let before = git_out(d, &["rev-parse", "main"]);
    let v = repo.ok(&["release", "cut", "0.532.0"]);
    let commit = v["data"]["commit"].as_str().expect("commit").to_owned();
    assert_eq!(
        git_out(d, &["rev-parse", &format!("{commit}^")]),
        before,
        "one commit on the old base"
    );
    let files = git_out(d, &["show", "--name-only", "--format=", &commit]);
    let files: Vec<&str> = files.lines().collect();
    assert_eq!(files.len(), 5, "{files:?}");
    assert!(
        files.contains(&"CHANGELOG.md")
            && files.contains(&"Cargo.toml")
            && files.contains(&"Cargo.lock")
    );
    assert!(
        files.iter().any(|f| f.starts_with("changelog.d/")),
        "the fragment removal is in the commit"
    );
    assert!(
        !d.join("changelog.d")
            .read_dir()
            .is_ok_and(|mut r| r.next().is_some()),
        "fragments gone"
    );
    assert!(
        std::fs::read_to_string(d.join("CHANGELOG.md"))
            .expect("changelog")
            .contains("Added the cut.")
    );
    for tag in ["frob-v0.532.0", "grimble-v0.532.0"] {
        assert_eq!(
            git_out(d, &["rev-parse", &format!("{tag}^{{commit}}")]),
            commit,
            "{tag}"
        );
        assert_eq!(git_out(d, &["cat-file", "-t", tag]), "tag", "annotated");
    }
    assert_eq!(v["data"]["tags"].as_array().expect("tags").len(), 2);
    assert_eq!(v["data"]["pushed"], false);
    let events = milestone_events(&repo);
    assert!(
        events.contains("kind = \"cut\"") && events.contains(&commit),
        "{events}"
    );
    assert!(events.contains("to = \"released\""), "{events}");
    let shown = repo.ok(&["milestone", "show", "0.532.0"]);
    assert_eq!(shown["data"]["milestone"]["state"], "released", "{shown}");
    assert_eq!(
        code(&repo.frob(&["release", "cut", "0.532.0"])),
        3,
        "a recorded cut is not repeated"
    );
}

#[test]
fn not_ready_without_override_exits_3_with_the_remedy() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    let repo = releasable(false);
    let before = git_out(repo.dir.path(), &["rev-parse", "main"]);
    let out = repo.frob(&["release", "cut", "0.532.0"]);
    assert_eq!(code(&out), 3);
    let text = String::from_utf8_lossy(&out.stdout).into_owned();
    assert!(
        text.contains("E-CUT-NOT-READY") && text.contains("--override --reason"),
        "{text}"
    );
    assert_eq!(git_out(repo.dir.path(), &["rev-parse", "main"]), before);
    assert!(git_out(repo.dir.path(), &["tag", "-l"]).is_empty());
    assert_eq!(
        code(&repo.frob(&["release", "cut", "0.532.0", "--override"])),
        2,
        "override needs a reason"
    );
}

#[test]
fn override_records_the_reason_on_the_milestone() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    let repo = releasable(false);
    let v = repo.ok(&[
        "release",
        "cut",
        "0.532.0",
        "--override",
        "--reason",
        "owner approved the gap",
    ]);
    assert_eq!(v["data"]["override_reason"], "owner approved the gap");
    let events = milestone_events(&repo);
    assert!(
        events.contains("kind = \"override\"") && events.contains("owner approved the gap"),
        "{events}"
    );
    assert!(git_out(repo.dir.path(), &["tag", "-l"]).contains("frob-v0.532.0"));
}

#[test]
fn a_dirty_tree_is_refused() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    let repo = releasable(true);
    write(&repo, "stray.txt", "x");
    let out = repo.frob(&["release", "cut", "0.532.0"]);
    assert_eq!(code(&out), 3);
    assert!(String::from_utf8_lossy(&out.stdout).contains("E-CUT-DIRTY"));
    assert!(git_out(repo.dir.path(), &["tag", "-l"]).is_empty());
}

#[test]
fn an_existing_tag_is_refused() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    let repo = releasable(true);
    git(repo.dir.path(), &["tag", "frob-v0.532.0"]);
    let before = git_out(repo.dir.path(), &["rev-parse", "main"]);
    let out = repo.frob(&["release", "cut", "0.532.0"]);
    assert_eq!(code(&out), 3);
    assert!(String::from_utf8_lossy(&out.stdout).contains("E-CUT-TAG-EXISTS"));
    assert_eq!(git_out(repo.dir.path(), &["rev-parse", "main"]), before);
}

#[test]
fn a_cut_that_fails_between_the_tags_resumes_with_no_second_commit() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    // frob:tests crates/frob-release/src/cut.rs::cut
    let repo = releasable(true);
    let d = repo.dir.path();
    // A ref below the grimble tag name makes that tag impossible to create, after the frob tag exists.
    git(d, &["tag", "grimble-v0.532.0/blocker"]);
    let out = repo.frob(&["release", "cut", "0.532.0"]);
    assert_ne!(code(&out), 0, "{}", String::from_utf8_lossy(&out.stdout));
    let commit = git_out(d, &["rev-parse", "frob-v0.532.0^{commit}"]);
    assert_eq!(
        git_out(d, &["rev-parse", "main"]),
        commit,
        "the commit stands"
    );
    assert!(
        !milestone_events(&repo).contains("kind = \"cut\""),
        "nothing recorded yet"
    );
    git(d, &["tag", "-d", "grimble-v0.532.0/blocker"]);
    let v = repo.ok(&["release", "cut", "0.532.0"]);
    assert_eq!(v["data"]["resumed"], true);
    assert_eq!(v["data"]["commit"], commit.as_str());
    assert_eq!(
        git_out(d, &["rev-parse", "grimble-v0.532.0^{commit}"]),
        commit
    );
    let log = git_out(d, &["log", "--format=%s", "--first-parent"]);
    assert_eq!(
        log.matches("chore(release): cut 0.532.0").count(),
        1,
        "{log}"
    );
    assert!(milestone_events(&repo).contains("kind = \"cut\""));
}

#[test]
fn push_sends_the_branch_and_the_tags_to_origin() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    let repo = releasable(true);
    let d = repo.dir.path();
    let remote = tempfile::tempdir().expect("remote");
    git(remote.path(), &["init", "-q", "--bare"]);
    git(
        d,
        &["remote", "add", "origin", &remote.path().to_string_lossy()],
    );
    let v = repo.ok(&["release", "cut", "0.532.0", "--push"]);
    assert_eq!(v["data"]["pushed"], true);
    let refs = git_out(remote.path(), &["for-each-ref", "--format=%(refname)"]);
    assert!(
        refs.contains("refs/tags/frob-v0.532.0") && refs.contains("refs/tags/grimble-v0.532.0"),
        "{refs}"
    );
}

/// Run frob with `path` as the whole PATH (a fake or absent `gh`).
#[cfg(unix)]
fn run_with_path(repo: &Repo, path: &Path, args: &[&str]) -> Output {
    common::frob_command()
        .current_dir(repo.dir.path())
        .env_remove("FROB_LOG")
        .env("PATH", path)
        .args(args)
        .output()
        .expect("run frob")
}

#[cfg(unix)]
/// A directory with a stub `gh` printing one failing check run (and an empty status).
fn red_gh() -> tempfile::TempDir {
    use std::os::unix::fs::PermissionsExt;
    let dir = tempfile::tempdir().expect("tempdir");
    let script = "#!/bin/sh\ncase \"$*\" in\n*check-runs*) echo '{\"check_runs\":[{\"name\":\"lint\",\"status\":\"completed\",\"conclusion\":\"failure\",\"html_url\":\"https://x/lint\"}]}';;\n*) echo '{\"statuses\":[]}';;\nesac\n";
    let path = dir.path().join("gh");
    std::fs::write(&path, script).expect("script");
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).expect("chmod");
    dir
}

#[cfg(unix)]
#[test]
fn a_red_or_unknown_ci_tip_refuses_the_cut_without_override() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseCut.run
    // frob:tests crates/frob/src/release_cmd.rs::ci_facts
    let repo = releasable(true);
    let d = repo.dir.path();
    git(
        d,
        &["remote", "add", "origin", "git@github.com:acme/widget.git"],
    );
    let toml = d.join("frob.toml");
    let text = std::fs::read_to_string(&toml).expect("frob.toml");
    std::fs::write(
        &toml,
        text.replace("require_ci = false", "require_ci = true"),
    )
    .expect("write");
    git(d, &["commit", "-q", "-am", "require ci"]);
    let before = git_out(d, &["rev-parse", "main"]);
    let red = red_gh();
    let missing = tempfile::tempdir().expect("tempdir");
    for (gh, needle) in [(red.path(), "CI is red"), (missing.path(), "CI status of")] {
        let out = run_with_path(&repo, gh, &["--json", "release", "cut", "0.532.0"]);
        assert_eq!(code(&out), 3, "{}", String::from_utf8_lossy(&out.stdout));
        let text = String::from_utf8_lossy(&out.stdout);
        assert!(
            text.contains("E-CUT-NOT-READY") && text.contains(needle),
            "{text}"
        );
        assert_eq!(git_out(d, &["rev-parse", "main"]), before, "nothing cut");
    }
}

// frob:ticket 01M4235FC39ZQYF207H8ANQEZE
/// A repository whose release 0.1.0 was cut by hand: the workspace version committed, an annotated `frob` tag and a lightweight `grimble` tag.
fn hand_cut() -> Repo {
    let repo = Repo::new();
    write(&repo, "Cargo.toml", &ROOT.replace("0.0.0", "0.1.0"));
    write(&repo, "crates/a/Cargo.toml", A);
    write(&repo, "crates/a/src/lib.rs", "");
    git(repo.dir.path(), &["add", "-A"]);
    git(repo.dir.path(), &["commit", "-q", "-m", "release 0.1.0"]);
    git(
        repo.dir.path(),
        &["tag", "-a", "frob-v0.1.0", "-m", "frob 0.1.0"],
    );
    git(repo.dir.path(), &["tag", "grimble-v0.1.0"]);
    repo
}

/// Every REL001 finding line `frob check` reports (the check output lists findings in the error message).
fn rel001(repo: &Repo) -> Vec<String> {
    let out = repo.frob(&["check"]);
    let v = json(&out);
    v["findings"]
        .as_array()
        .map(Vec::as_slice)
        .unwrap_or_default()
        .iter()
        .filter(|f| {
            f["rule"] == "REL001"
                && f["message"]
                    .as_str()
                    .is_some_and(|m| m.contains("REL001: tag"))
        })
        .map(|f| f["message"].to_string())
        .collect()
}

/// Every tag with the object it names, as git reports them.
fn tag_refs(repo: &Repo) -> String {
    git_out(
        repo.dir.path(),
        &[
            "for-each-ref",
            "--format=%(refname) %(objectname)",
            "refs/tags",
        ],
    )
}

#[test]
fn adopt_records_hand_made_tags_as_an_adopted_cut_and_clears_rel001() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseAdopt.run
    // frob:tests crates/frob-release/src/adopt.rs::resolve
    let repo = hand_cut();
    let refs = tag_refs(&repo);
    let head = git_out(repo.dir.path(), &["rev-parse", "HEAD"]);
    let remotes = git_out(repo.dir.path(), &["remote"]);
    assert_eq!(rel001(&repo).len(), 2, "both tags are strays before adopt");

    let v = repo.ok(&[
        "release",
        "adopt",
        "0.1.0",
        "--reason",
        "cut by hand before frob",
    ]);
    assert_eq!(v["already"], false);
    let d = &v["data"];
    assert_eq!(d["version"], "0.1.0");
    assert_eq!(d["milestone_created"], true);
    assert_eq!(d["commit"], head.as_str());
    assert_eq!(d["tags"].as_array().expect("tags").len(), 2);

    let events = milestone_events(&repo);
    assert!(events.contains("kind = \"cut\""), "{events}");
    assert!(events.contains("kind = \"adopt\""), "{events}");
    assert!(events.contains("cut by hand before frob"), "{events}");
    assert!(events.contains("frob-v0.1.0") && events.contains("grimble-v0.1.0"));
    assert!(events.contains("to = \"released\""), "{events}");
    let milestone = repo.ok(&["milestone", "show", "0.1.0"]);
    assert!(milestone.to_string().contains("released"), "{milestone}");

    assert_eq!(tag_refs(&repo), refs, "tags untouched");
    // Only the ledger (tickets/) moved; no source file and no ref other than the branch.
    let changed = git_out(repo.dir.path(), &["diff", "--name-only", &head, "HEAD"]);
    assert!(
        changed.lines().all(|p| p.starts_with("tickets/")),
        "{changed}"
    );
    assert_eq!(
        git_out(repo.dir.path(), &["remote"]),
        remotes,
        "no remote added or used"
    );
    assert!(rel001(&repo).is_empty(), "REL001 is clean after adopt");
}

#[test]
fn a_repeated_adopt_returns_already_and_writes_nothing() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseAdopt.run
    let repo = hand_cut();
    repo.ok(&["release", "adopt", "0.1.0"]);
    let events = milestone_events(&repo);
    let ledger_tip = git_out(
        repo.dir.path(),
        &["for-each-ref", "--format=%(objectname)", "refs/frob"],
    );
    let again = repo.ok(&["release", "adopt", "0.1.0", "--reason", "a second time"]);
    assert_eq!(again["already"], true);
    assert_eq!(milestone_events(&repo), events);
    assert_eq!(
        git_out(
            repo.dir.path(),
            &["for-each-ref", "--format=%(objectname)", "refs/frob"]
        ),
        ledger_tip
    );
}

#[test]
fn adopt_releases_an_existing_milestone_instead_of_creating_one() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseAdopt.run
    let repo = hand_cut();
    repo.ok(&["milestone", "new", "0.1.0", "--goal", "First"]);
    let v = repo.ok(&["release", "adopt", "0.1.0"]);
    assert_eq!(v["data"]["milestone_created"], false);
    let events = milestone_events(&repo);
    assert!(events.contains("kind = \"cut\"") && events.contains("to = \"released\""));
    assert!(rel001(&repo).is_empty());
}

#[test]
fn adopt_without_tags_is_refused_with_a_remedy_and_writes_nothing() {
    // frob:tests crates/frob/src/release_cmd.rs::ReleaseAdopt.run
    let repo = hand_cut();
    let out = repo.frob(&["release", "adopt", "0.2.0"]);
    assert_eq!(code(&out), 3, "{}", String::from_utf8_lossy(&out.stdout));
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(text.contains("E-ADOPT-NO-TAG"), "{text}");
    assert!(
        text.contains("frob-v0.2.0") && text.contains("grimble-v0.2.0"),
        "{text}"
    );
    assert!(
        !repo.dir.path().join("tickets/_milestones").exists()
            || !milestone_events(&repo).contains("0.2.0")
    );
}
