"""CLI parser builders package (T-1076 split of `frob.__main__`).

Re-exports every `_add_*_parser` builder so `frob.__main__` (and any test
that imports a builder directly, e.g. `from frob.__main__ import
_add_test_parser`) sees an unchanged surface.
"""

from __future__ import annotations

from ._check import (
    _add_check_delta_and_verbose_args,
    _add_check_parser,
    _add_check_scope_args,
    _add_check_selection_args,
    _add_check_skip_args,
    _add_check_skip_args_cpp,
    _add_check_skip_args_python,
    _add_check_skip_args_rust_ts,
)
from ._core import (
    _add_agent_parser,
    _add_arch_parser,
    _add_bind_parser,
    _add_cycle_parser,
    _add_docs_parser,
    _add_dup_parser,
    _add_dup_probe_argument,
    _add_exports_parser,
    _add_map_parser,
    _add_outline_parser,
    _add_parse_input_args,
    _add_parse_output_args,
    _add_parse_parser,
    _add_scaffold_parser,
    _add_worktree_parser,
    _add_xref_parser,
)
from ._design import _add_design_parser
from ._explore import _add_explore_parser
from ._misc import (
    _add_claude_parser,
    _add_clean_parser,
    _add_coverage_parser,
    _add_deploy_audit_parser,
    _add_deploy_audit_ssh_and_output_args,
    _add_deploy_generate_parser,
    _add_deploy_parser,
    _add_doctor_parser,
    _add_fmt_parser,
    _add_mutate_parser,
    _add_natives_parser,
    _add_perf_collect_parser,
    _add_perf_heat_parser,
    _add_perf_hot_parser,
    _add_perf_parser,
    _add_perf_profile_parser,
    _add_release_parser,
    _add_serve_parser,
    _add_stats_parser,
    _add_sync_skills_parser,
    _add_sys_doc_and_audit_parsers,
    _add_sys_parser,
    _add_sys_plan_and_export_parsers,
    _add_test_parser,
    _add_vet_parser,
)
from ._ops import _add_ops_parser
from ._quality import _add_quality_parser
from ._reporting import (
    _add_ack_parser,
    _add_debt_parser,
    _add_deprecated_parser,
    _add_fleet_parser,
    _add_gitlog_parser,
    _add_gitlog_range_args,
    _add_graph_parser,
    _add_pool_parser,
    _add_profile_parser,
    _add_registry_parser,
)
from ._ticket import (
    _add_ticket_attach_and_lifecycle_end_parsers,
    _add_ticket_close_parser,
    _add_ticket_closeout_parsers,
    _add_ticket_component_parser,
    _add_ticket_done_report_parser,
    _add_ticket_fail_evidence_archive_parsers,
    _add_ticket_kind_parser,
    _add_ticket_label_parser,
    _add_ticket_land_parser,
    _add_ticket_lifecycle_parsers,
    _add_ticket_merge_driver_parser,
    _add_ticket_new_graph_args,
    _add_ticket_new_identity_args,
    _add_ticket_new_parser,
    _add_ticket_parser,
    _add_ticket_priority_parser,
    _add_ticket_progress_parsers,
    _add_ticket_query_parsers,
    _add_ticket_renumber_parser,
    _add_ticket_reverify_parser,
    _add_ticket_review_parser,
    _add_ticket_scope_ack_parser,
    _add_ticket_scope_parser,
    _add_ticket_sprint_parser,
    _add_ticket_tier_parser,
)
from ._verify import _add_verify_parser

__all__ = [
    "_add_ack_parser",
    "_add_agent_parser",
    "_add_arch_parser",
    "_add_bind_parser",
    "_add_check_delta_and_verbose_args",
    "_add_check_parser",
    "_add_check_scope_args",
    "_add_check_selection_args",
    "_add_check_skip_args",
    "_add_check_skip_args_cpp",
    "_add_check_skip_args_python",
    "_add_check_skip_args_rust_ts",
    "_add_claude_parser",
    "_add_clean_parser",
    "_add_coverage_parser",
    "_add_cycle_parser",
    "_add_debt_parser",
    "_add_deploy_audit_parser",
    "_add_deploy_audit_ssh_and_output_args",
    "_add_deploy_generate_parser",
    "_add_deploy_parser",
    "_add_deprecated_parser",
    "_add_docs_parser",
    "_add_doctor_parser",
    "_add_dup_parser",
    "_add_dup_probe_argument",
    "_add_design_parser",
    "_add_explore_parser",
    "_add_ops_parser",
    "_add_quality_parser",
    "_add_exports_parser",
    "_add_fleet_parser",
    "_add_fmt_parser",
    "_add_gitlog_parser",
    "_add_gitlog_range_args",
    "_add_graph_parser",
    "_add_map_parser",
    "_add_mutate_parser",
    "_add_natives_parser",
    "_add_outline_parser",
    "_add_parse_input_args",
    "_add_parse_output_args",
    "_add_parse_parser",
    "_add_perf_collect_parser",
    "_add_perf_heat_parser",
    "_add_perf_hot_parser",
    "_add_perf_parser",
    "_add_perf_profile_parser",
    "_add_pool_parser",
    "_add_profile_parser",
    "_add_registry_parser",
    "_add_release_parser",
    "_add_scaffold_parser",
    "_add_serve_parser",
    "_add_stats_parser",
    "_add_sync_skills_parser",
    "_add_sys_doc_and_audit_parsers",
    "_add_sys_parser",
    "_add_sys_plan_and_export_parsers",
    "_add_test_parser",
    "_add_ticket_attach_and_lifecycle_end_parsers",
    "_add_ticket_close_parser",
    "_add_ticket_closeout_parsers",
    "_add_ticket_component_parser",
    "_add_ticket_done_report_parser",
    "_add_ticket_fail_evidence_archive_parsers",
    "_add_ticket_kind_parser",
    "_add_ticket_label_parser",
    "_add_ticket_land_parser",
    "_add_ticket_lifecycle_parsers",
    "_add_ticket_merge_driver_parser",
    "_add_ticket_new_graph_args",
    "_add_ticket_new_identity_args",
    "_add_ticket_new_parser",
    "_add_ticket_parser",
    "_add_ticket_priority_parser",
    "_add_ticket_progress_parsers",
    "_add_ticket_query_parsers",
    "_add_ticket_renumber_parser",
    "_add_ticket_reverify_parser",
    "_add_ticket_review_parser",
    "_add_ticket_scope_ack_parser",
    "_add_ticket_scope_parser",
    "_add_ticket_sprint_parser",
    "_add_ticket_tier_parser",
    "_add_verify_parser",
    "_add_vet_parser",
    "_add_worktree_parser",
    "_add_xref_parser",
]
