#!/bin/sh
# Prove an installed frob works in a real repository (releases.md 6, ticket ~NWXQPMM).
# Builds a throwaway git repository holding a tiny Rust crate and one markdown file, then
# runs the whole loop with the installed binaries only: init, ticket new (one criterion),
# work, edit, check, evidence (command provider), changelog fragment, land; asserts the
# ticket closed done and `ticket doctor` is clean. Needs git and cargo on PATH; no
# repository paths, no jq. POSIX sh, so it runs under Git Bash on Windows (frob.exe is
# found through PATH; the sed JSON picks assume the compact one-line envelopes of --json).
# Usage: fixture-loop.sh BIN_DIR [EXPECTED_VERSION]   (BIN_DIR holds frob, and grimble when shipped)
set -eu

bin="${1:?usage: fixture-loop.sh BIN_DIR [EXPECTED_VERSION]}"
want="${2:-}"
bin="$(cd "$bin" && pwd)"
PATH="$bin:$PATH"
export PATH
# A runner may carry a repository-pinned FROB_LOG or cargo target dir; the fixture is isolated.
unset FROB_LOG CARGO_TARGET_DIR RUSTFLAGS

say() { echo "smoke-loop: $*" >&2; }
die() { echo "smoke-loop: FAIL: $*" >&2; exit 1; }

work="$(mktemp -d)"
trap 'cd /; rm -rf "$work"' EXIT
repo="$work/repo"

# Run frob with --json in $PWD, require exit 0 and `"ok":true`, print the envelope.
fj() {
    out="$(frob --json "$@")" || die "frob $* exited non-zero: $out"
    case "$out" in *'"ok":true'*) ;; *) die "frob $* not ok: $out" ;; esac
    printf '%s\n' "$out"
}
# Pick the first string value of key $1 from the envelope on stdin.
pick() { sed -n "s/.*\"$1\":\"\\([^\"]*\\)\".*/\\1/p" | head -n 1; }
# Assert envelope $1 contains literal $2, naming $3 on failure.
has() { case "$1" in *"$2"*) ;; *) die "$3: missing $2 in $1" ;; esac; }

got="$(frob --version | tr -d '\r')"
say "$got"
if [ -n "$want" ] && [ "$got" != "frob $want" ]; then die "expected 'frob $want', got '$got'"; fi
# A standalone archive ships frob alone; the wheel also bundles grimble (smoke.sh requires it).
if [ -x "$bin/grimble" ] || [ -x "$bin/grimble.exe" ]; then grimble --version >/dev/null || die "grimble --version"; fi

# 1. Fixture repository: a tiny crate, one markdown file, one commit on `main`.
mkdir -p "$repo/src"
cd "$repo"
git init -q
git symbolic-ref HEAD refs/heads/main
git config user.name "Smoke Test"
git config user.email "smoke@example.com"
git config core.autocrlf false
cat >Cargo.toml <<'T'
[package]
name = "tiny"
version = "0.1.0"
edition = "2021"
T
cat >Cargo.lock <<'T'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "tiny"
version = "0.1.0"
T
cat >src/lib.rs <<'T'
//! A tiny crate.

/// Add two numbers.
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adds() {
        assert_eq!(add(1, 2), 3);
    }
}
T
printf '# tiny\n\nA fixture crate for the frob artifact smoke.\n' >README.md
printf 'target/\n' >.gitignore
git add -A
git commit -q -m "initial"

# 2. init, then commit its files (land wants a clean base).
env="$(fj init)"; has "$env" '"verb":"init"' init
fj doctor >/dev/null
fj check >/dev/null
git add -A
git commit -q -m "chore: frob init"
say "init ok"

# 3. A ticket with one criterion, scoped to the crate sources and the changelog fragment directory.
env="$(fj ticket new --title "Make add overflow-safe" \
    --acceptance "Given two large numbers, when add runs, then it does not panic" \
    --scope 'src/**' --scope 'changelog.d/**')"
handle="$(printf '%s\n' "$env" | pick handle)"
id="$(printf '%s\n' "$env" | pick id)"
[ -n "$handle" ] && [ -n "$id" ] || die "no handle or id in $env"
say "ticket $handle ($id)"

# 4. work: a worktree on its own branch holding a lease on src/**.
env="$(fj work "$handle")"
wt="$(printf '%s\n' "$env" | pick path)"
[ -f "$wt/src/lib.rs" ] || die "worktree $wt lacks the crate"
cd "$wt"

# 5. The change, inside the scope; check on the ticket.
sed -i.bak -e 's/a + b/a.wrapping_add(b)/' src/lib.rs && rm -f src/lib.rs.bak
grep -q wrapping_add src/lib.rs || die "edit did not apply"
env="$(fj check --ticket "$handle")"; has "$env" '"verb":"check"' check
has "$env" '"error":0' "check error count"
say "check ok"

# 6. Evidence for criterion 1 from the command provider, through the installed frob.
env="$(fj ticket evidence add "$handle" --accepts 1 --provider command --ref "cargo test")"
has "$env" '"passed":true' evidence
say "evidence ok"

# 7. Changelog fragment named with the ticket id, then commit and land.
mkdir -p changelog.d
printf 'tiny: Made add overflow-safe.\n' >"changelog.d/$id.fixed.md"
git add -A
git commit -q -m "fix: overflow-safe add"
fj land >/dev/null
say "land ok"

# 8. The base branch holds the change; the ticket is closed done and the ledger is clean.
cd "$repo"
[ "$(git rev-parse --abbrev-ref HEAD)" = main ] || die "primary checkout left main"
git show main:src/lib.rs | grep -q wrapping_add || die "main lacks the change"
env="$(fj ticket show "$handle")"
has "$env" '"category":"done"' "ticket category"
has "$env" '"outcome":"done"' "ticket outcome"
env="$(fj ticket doctor)"
has "$env" '"issues":[]' "ticket doctor"
[ ! -e "$wt" ] || die "worktree $wt not removed"
say "ok"
