"""
Integration tests for `frob exports --write`: full round-trip from
package source to written __init__.py, and update behavior on re-run.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

FROB = [sys.executable, "-m", "frob"]


def _frob(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(FROB + args, capture_output=True, text=True)


def _make_pkg(tmp_path: Path, files: dict[str, str], pkg_name: str = "mypkg") -> Path:
    pkg = tmp_path / pkg_name
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    for name, src in files.items():
        (pkg / name).write_text(src)
    return pkg


class TestExportsWriteRoundTrip:
    def test_write_creates_valid_init(self, tmp_path):
        pkg = _make_pkg(
            tmp_path,
            {
                "core.py": "def compute(x: int) -> int:\n    return x * 2\n",
            },
        )
        r = _frob(["exports", str(pkg), "--write"])
        assert r.returncode == 0, r.stderr

        init = pkg / "__init__.py"
        content = init.read_text()
        assert "compute" in content
        assert "__all__" in content
        assert "from mypkg.core import" in content

    def test_write_includes_header_comment(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def x(): ...\n"})
        _frob(["exports", str(pkg), "--write"])
        content = (pkg / "__init__.py").read_text()
        assert "generated by" in content.lower() or "frob exports" in content

    def test_write_all_flag_includes_private(self, tmp_path):
        pkg = _make_pkg(
            tmp_path,
            {
                "mod.py": "def public(): ...\ndef _helper(): ...\n",
            },
        )
        _frob(["exports", str(pkg), "--write", "--all"])
        content = (pkg / "__init__.py").read_text()
        assert "public" in content
        assert "_helper" in content

    def test_write_excludes_private_by_default(self, tmp_path):
        pkg = _make_pkg(
            tmp_path,
            {
                "mod.py": "def public(): ...\ndef _hidden(): ...\n",
            },
        )
        _frob(["exports", str(pkg), "--write"])
        content = (pkg / "__init__.py").read_text()
        assert "public" in content
        assert "_hidden" not in content

    def test_write_multiple_modules(self, tmp_path):
        pkg = _make_pkg(
            tmp_path,
            {
                "alpha.py": "def foo(): ...\nclass Alpha:\n    pass\n",
                "beta.py": "def bar(): ...\nclass Beta:\n    pass\n",
            },
        )
        _frob(["exports", str(pkg), "--write"])
        content = (pkg / "__init__.py").read_text()
        assert "foo" in content
        assert "Alpha" in content
        assert "bar" in content
        assert "Beta" in content
        assert "from mypkg.alpha import" in content
        assert "from mypkg.beta import" in content

    def test_all_symbols_in_all_list(self, tmp_path):
        pkg = _make_pkg(
            tmp_path,
            {
                "mod.py": "def one(): ...\ndef two(): ...\ndef three(): ...\n",
            },
        )
        _frob(["exports", str(pkg), "--write"])
        content = (pkg / "__init__.py").read_text()
        assert '"one"' in content or "'one'" in content
        assert '"two"' in content or "'two'" in content
        assert '"three"' in content or "'three'" in content


class TestExportsWriteUpdate:
    def test_rerun_after_adding_symbol(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\n"})
        _frob(["exports", str(pkg), "--write"])

        # Add a new symbol
        (pkg / "mod.py").write_text("def foo(): ...\ndef bar(): ...\n")
        _frob(["exports", str(pkg), "--write"])

        content = (pkg / "__init__.py").read_text()
        assert "foo" in content
        assert "bar" in content

    def test_rerun_after_removing_symbol(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\ndef bar(): ...\n"})
        _frob(["exports", str(pkg), "--write"])

        # Remove bar
        (pkg / "mod.py").write_text("def foo(): ...\n")
        _frob(["exports", str(pkg), "--write"])

        content = (pkg / "__init__.py").read_text()
        assert "foo" in content
        assert "bar" not in content

    def test_rerun_after_adding_module(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"alpha.py": "def foo(): ...\n"})
        _frob(["exports", str(pkg), "--write"])

        # Add a new module
        (pkg / "beta.py").write_text("def bar(): ...\n")
        _frob(["exports", str(pkg), "--write"])

        content = (pkg / "__init__.py").read_text()
        assert "foo" in content
        assert "bar" in content
        assert "from mypkg.beta import" in content

    def test_init_is_importable_python(self, tmp_path):
        pkg = _make_pkg(
            tmp_path,
            {
                "mod.py": "def alpha(): ...\nclass Beta:\n    pass\n",
            },
        )
        _frob(["exports", str(pkg), "--write"])

        # The generated __init__.py should be valid Python
        init = pkg / "__init__.py"
        r = subprocess.run(
            [
                sys.executable,
                "-c",
                f"import ast; ast.parse(open({str(init)!r}).read())",
            ],
            capture_output=True,
            text=True,
        )
        assert r.returncode == 0, (
            f"generated __init__.py is not valid Python: {r.stderr}"
        )


class TestExportsWriteExclude:
    def test_exclude_omits_module_from_init(self, tmp_path):
        pkg = _make_pkg(
            tmp_path,
            {
                "keep.py": "def good(): ...\n",
                "skip.py": "def bad(): ...\n",
            },
        )
        _frob(["exports", str(pkg), "--write", "--exclude", "skip"])
        content = (pkg / "__init__.py").read_text()
        assert "good" in content
        assert "bad" not in content
        assert "skip" not in content
