"""`frob deploy audit --vm <name>`: VirtualBox snapshot-diff harness proving
an artifact-free uninstall, empirically, against a live host (T-0259,
deploy epic T-0254 child 5). NOT run by `make check` -- it is the
expensive, VM-requiring counterpart to the static DEPLOY001/DEPLOY002/
DEPLOY003 gates (`_drift.py`/`_conform.py`), which prove the SCRIPTS are
internally consistent; this module proves the scripts, RUN against a real
host, actually leave the host exactly as declared.

This module holds only the PURE, VM-free half of the audit: state-capture
data shapes, diffing, the four proofs, status-line assertions, and
attestation JSON -- every function here operates on plain data (a
`StateCapture`, a status.sh text blob) and is fully covered by
`tests/unit/deploy/test_audit.py` fixtures with no VirtualBox, no ssh, no
VM involved. The orchestration half -- actually driving VBoxManage,
restoring snapshots, and ssh'ing into the guest to fill in a
`StateCapture` -- lives in `_vm_runner.py`, deliberately kept thin (a
sequence of subprocess calls) so that thin sliver is the ONLY part of
this feature that cannot be exercised in the normal test suite.

The exact sequence this module's `run_audit` (in `_vm_runner.py`) drives,
per the ticket's user-specified spec: restore base snapshot -> CHECK C0
(capture S0 + assert `status.sh` reports NOT-installed) -> `install.sh`
-> CHECK C1 (capture S1 + assert healthy) -> `install.sh` AGAIN -> CHECK
C1' (capture S1' + assert healthy) -> `uninstall.sh` -> CHECK C2 (capture
S2 + assert NOT-installed). A "CHECK" is always both halves together --
capture AND a `status.sh` health assertion -- never capture alone, so a
broken install is caught at the checkpoint it broke, not three steps
later when a diff comes up unexpectedly non-empty.

Four proofs, all diff-based and allowlist-filtered (`ALLOWLIST_PATTERNS`
below, each entry justified in `docs/commands/deploy.md#allowlist`):

- **idempotence**: `diff(S1, S1')` is EMPTY -- installing twice mutates
  nothing the second time.
- **artifact-freeness**: `diff(S0, S2)` is EMPTY -- install then uninstall
  leaves the host byte-for-byte (modulo the allowlist) as it started.
- **install-exactness**: the set of filesystem paths / systemd units /
  service users `diff(S0, S1)` touches is EXACTLY
  `frob.deploy.expected_mutation_surface(model)` -- nothing extra, nothing
  missing (reuses T-0258's manifest-derived expected surface directly,
  never a second independently-maintained expectation).
- the three `status.sh` health assertions at C0/C1/C1'/C2 (module
  docstring) are checked by `assert_not_installed`/`assert_healthy`
  below, called at each checkpoint.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime

from pydantic import BaseModel, ConfigDict

from frob.deploy._conform import MutationTarget
from frob.logging import get_logger

_log = get_logger(__name__)

# frob:doc docs/commands/deploy.md#allowlist
#: Filesystem paths excluded from every diff comparison below, each
#: justified because it changes as an ordinary side effect of the machine
#: being alive/running commands, NEVER because of anything install.sh or
#: uninstall.sh themselves declare:
#: - `/var/log/**`, `/var/log/journal/**`: normal log/journal growth from
#:   the OS and from running install.sh/uninstall.sh/status.sh themselves.
#: - `/etc/machine-id`, `/var/lib/dbus/machine-id`: D-Bus/systemd's
#:   machine identity, regenerated by some cloud-init/first-boot paths
#:   independent of this tool.
#: - `/run/**`, `/proc/**`, `/sys/**`, `/tmp/**`, `/var/tmp/**`: kernel-
#:   backed or ephemeral-by-design; never persisted, never declared by a
#:   `HostManifest`.
#: - `/var/lib/systemd/**`: systemd's own bookkeeping (random-seed,
#:   catalog database) touched by any `systemctl daemon-reload`.
ALLOWLIST_PATTERNS: tuple[str, ...] = (
    r"^/var/log/",
    r"^/etc/machine-id$",
    r"^/var/lib/dbus/machine-id$",
    r"^/run/",
    r"^/proc/",
    r"^/sys/",
    r"^/tmp/",
    r"^/var/tmp/",
    r"^/var/lib/systemd/",
)

_ALLOWLIST_RE = tuple(re.compile(p) for p in ALLOWLIST_PATTERNS)


def _is_allowlisted(path: str) -> bool:
    """`True` when `path` matches any `ALLOWLIST_PATTERNS` entry -- the
    ONE predicate every diff below filters through, so the allowlist can
    never desync between the four proofs."""
    return any(p.search(path) for p in _ALLOWLIST_RE)


# frob:doc docs/commands/deploy.md#state-capture
class FileFact(BaseModel):
    """One filesystem entry's identity for diffing: content hash,
    ownership, and mode -- the exact three facts a `HostManifest` `owns`
    entry declares (path/owner/mode) plus content, so a diff catches a
    wrong owner, a wrong mode, or unexpected content equally."""

    model_config = ConfigDict(frozen=True)

    sha256: str
    owner: str
    group: str
    mode: str


# frob:doc docs/commands/deploy.md#state-capture
class StateCapture(BaseModel):
    """One point-in-time snapshot of guest state (module docstring's S0/
    S1/S1'/S2) -- filesystem manifest, `/etc/passwd`+`/etc/group` text,
    systemd unit file bodies + the enabled-unit set, and the listening-
    socket set. Produced by `_vm_runner.py`'s ssh capture over a live
    guest, or built directly from a fixture dict in
    `tests/unit/deploy/test_audit.py` -- this type has no VM dependency
    itself."""

    model_config = ConfigDict(frozen=True)

    label: str
    filesystem: dict[str, FileFact]
    passwd: tuple[str, ...]
    group: tuple[str, ...]
    unit_files: dict[str, str]
    enabled_units: tuple[str, ...]
    listening_sockets: tuple[str, ...]


# frob:doc docs/commands/deploy.md#state-capture
class StateDiff(BaseModel):
    """The allowlist-filtered delta between two `StateCapture`s: paths
    added/removed/changed on the filesystem, unit files added/removed/
    changed, and passwd/group/enabled-unit/socket set deltas. `is_empty`
    is the single predicate the idempotence and artifact-freeness proofs
    both call -- neither re-derives emptiness its own way."""

    model_config = ConfigDict(frozen=True)

    added_paths: tuple[str, ...]
    removed_paths: tuple[str, ...]
    changed_paths: tuple[str, ...]
    added_units: tuple[str, ...]
    removed_units: tuple[str, ...]
    changed_units: tuple[str, ...]
    passwd_added: tuple[str, ...]
    passwd_removed: tuple[str, ...]
    group_added: tuple[str, ...]
    group_removed: tuple[str, ...]
    enabled_units_added: tuple[str, ...]
    enabled_units_removed: tuple[str, ...]
    sockets_added: tuple[str, ...]
    sockets_removed: tuple[str, ...]

    # frob:doc docs/commands/deploy.md#state-capture
    @property
    def is_empty(self) -> bool:
        """`True` when every field above is empty -- the states are
        identical modulo the allowlist. Used directly by the idempotence
        (`S1'==S1`) and artifact-freeness (`diff(S0,S2)` empty) proofs."""
        return not (
            self.added_paths
            or self.removed_paths
            or self.changed_paths
            or self.added_units
            or self.removed_units
            or self.changed_units
            or self.passwd_added
            or self.passwd_removed
            or self.group_added
            or self.group_removed
            or self.enabled_units_added
            or self.enabled_units_removed
            or self.sockets_added
            or self.sockets_removed
        )

    # frob:doc docs/commands/deploy.md#the-four-proofs
    def mutated_targets(self) -> frozenset[MutationTarget]:
        """This diff's touched set expressed as `frob.deploy._conform`'s
        shared `MutationTarget` shape (kind `"path"`/`"unit"`/`"user"`) --
        the install-exactness proof's LHS, directly set-comparable
        against `expected_mutation_surface(model)`'s RHS without a second,
        independently-maintained translation."""
        targets: set[MutationTarget] = set()
        for path in (*self.added_paths, *self.changed_paths):
            targets.add(MutationTarget(kind="path", target=path))
        for unit in (*self.added_units, *self.changed_units):
            targets.add(MutationTarget(kind="unit", target=unit))
        for line in self.passwd_added:
            name = line.split(":", 1)[0]
            if name:
                targets.add(MutationTarget(kind="user", target=name))
        return frozenset(targets)


# frob:doc docs/commands/deploy.md#state-capture
def diff_states(before: StateCapture, after: StateCapture) -> StateDiff:
    """Allowlist-filtered delta from `before` to `after` -- the ONE diff
    routine every proof (`idempotence_holds`/`artifact_freeness_holds`/
    `install_exactness_holds`) calls, so all three ever see the same
    notion of "changed" (module docstring)."""
    added_paths, removed_paths, changed_paths = _fs_diff(before, after)
    added_units, removed_units, changed_units = _units_diff(before, after)
    passwd_added, passwd_removed, group_added, group_removed = _accounts_diff(
        before, after
    )
    enabled_added, enabled_removed = _enabled_units_diff(before, after)
    sockets_added, sockets_removed = _sockets_diff(before, after)

    return StateDiff(
        added_paths=added_paths,
        removed_paths=removed_paths,
        changed_paths=changed_paths,
        added_units=added_units,
        removed_units=removed_units,
        changed_units=changed_units,
        passwd_added=passwd_added,
        passwd_removed=passwd_removed,
        group_added=group_added,
        group_removed=group_removed,
        enabled_units_added=enabled_added,
        enabled_units_removed=enabled_removed,
        sockets_added=sockets_added,
        sockets_removed=sockets_removed,
    )


def _fs_diff(
    before: StateCapture, after: StateCapture
) -> tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """Allowlist-filtered `(added, removed, changed)` filesystem paths."""
    before_fs = {p: f for p, f in before.filesystem.items() if not _is_allowlisted(p)}
    after_fs = {p: f for p, f in after.filesystem.items() if not _is_allowlisted(p)}
    added_paths = tuple(sorted(set(after_fs) - set(before_fs)))
    removed_paths = tuple(sorted(set(before_fs) - set(after_fs)))
    changed_paths = tuple(
        sorted(p for p in set(before_fs) & set(after_fs) if before_fs[p] != after_fs[p])
    )
    return added_paths, removed_paths, changed_paths


def _units_diff(
    before: StateCapture, after: StateCapture
) -> tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """`(added, removed, changed)` systemd unit files."""
    added_units = tuple(sorted(set(after.unit_files) - set(before.unit_files)))
    removed_units = tuple(sorted(set(before.unit_files) - set(after.unit_files)))
    changed_units = tuple(
        sorted(
            u
            for u in set(before.unit_files) & set(after.unit_files)
            if before.unit_files[u] != after.unit_files[u]
        )
    )
    return added_units, removed_units, changed_units


def _accounts_diff(
    before: StateCapture, after: StateCapture
) -> tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """`(passwd_added, passwd_removed, group_added, group_removed)`."""
    passwd_added = tuple(sorted(set(after.passwd) - set(before.passwd)))
    passwd_removed = tuple(sorted(set(before.passwd) - set(after.passwd)))
    group_added = tuple(sorted(set(after.group) - set(before.group)))
    group_removed = tuple(sorted(set(before.group) - set(after.group)))
    return passwd_added, passwd_removed, group_added, group_removed


def _enabled_units_diff(
    before: StateCapture, after: StateCapture
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """`(added, removed)` enabled systemd units."""
    enabled_added = tuple(sorted(set(after.enabled_units) - set(before.enabled_units)))
    enabled_removed = tuple(
        sorted(set(before.enabled_units) - set(after.enabled_units))
    )
    return enabled_added, enabled_removed


def _sockets_diff(
    before: StateCapture, after: StateCapture
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """`(added, removed)` listening sockets."""
    sockets_added = tuple(
        sorted(set(after.listening_sockets) - set(before.listening_sockets))
    )
    sockets_removed = tuple(
        sorted(set(before.listening_sockets) - set(after.listening_sockets))
    )
    return sockets_added, sockets_removed


# frob:doc docs/commands/deploy.md#the-four-proofs
def idempotence_holds(s1: StateCapture, s1_prime: StateCapture) -> bool:
    """PROOF: `S1' == S1` exactly (modulo the allowlist) -- installing
    twice performs zero mutations the second time (module docstring)."""
    return diff_states(s1, s1_prime).is_empty


# frob:doc docs/commands/deploy.md#the-four-proofs
def artifact_freeness_holds(s0: StateCapture, s2: StateCapture) -> bool:
    """PROOF: `diff(S0, S2)` is empty -- install then uninstall leaves the
    host exactly as it started, modulo the allowlist (module docstring)."""
    return diff_states(s0, s2).is_empty


# frob:doc docs/commands/deploy.md#the-four-proofs
def install_exactness_holds(
    s0: StateCapture,
    s1: StateCapture,
    expected: frozenset[MutationTarget],
) -> tuple[bool, frozenset[MutationTarget], frozenset[MutationTarget]]:
    """PROOF: `diff(S0, S1)`'s touched-target set equals `expected`
    (`frob.deploy.expected_mutation_surface(model)`, T-0258) exactly.
    Returns `(holds, extra, missing)` -- `extra` is what the diff touched
    beyond the manifest (a smuggled mutation), `missing` is a declared
    manifest entry the diff never touched (an incomplete install); both
    are empty iff `holds`."""
    actual = diff_states(s0, s1).mutated_targets()
    extra = actual - expected
    missing = expected - actual
    return (not extra and not missing, extra, missing)


# frob:doc docs/commands/deploy.md#status-assertions
_STATUS_UNIT_LINE_RE = re.compile(
    r"unit=(?P<unit>\S+) node=(?P<node>\S+) "
    r"active=(?P<active>\S*) enabled=(?P<enabled>\S*)"
)


# frob:doc docs/commands/deploy.md#status-assertions
def assert_not_installed(status_text: str) -> bool:
    """CHECK C0/C2 assertion: `status.sh`'s output reports every declared
    unit as `inactive`/`disabled` (or the unit-status line is entirely
    absent, the pre-first-install case) -- `generate_status_script`
    (`_generate.py`) guards each `systemctl` call so a not-yet-installed
    unit prints `active=inactive enabled=disabled` rather than aborting."""
    for match in _STATUS_UNIT_LINE_RE.finditer(status_text):
        if match.group("active") == "active" or match.group("enabled") == "enabled":
            return False
    return True


# frob:doc docs/commands/deploy.md#status-assertions
def assert_healthy(status_text: str, expected_units: frozenset[str]) -> bool:
    """CHECK C1/C1' assertion: every unit name in `expected_units` appears
    in `status_text` with `active=active enabled=enabled`, and no
    `expected_units` member is missing from the output entirely (a unit
    that silently failed to install would be absent, not merely
    inactive)."""
    seen: dict[str, tuple[str, str]] = {}
    for match in _STATUS_UNIT_LINE_RE.finditer(status_text):
        seen[match.group("unit")] = (match.group("active"), match.group("enabled"))
    for unit in expected_units:
        state = seen.get(unit)
        if state is None or state != ("active", "enabled"):
            return False
    return True


# frob:doc docs/commands/deploy.md#attestation
class CheckpointResult(BaseModel):
    """One CHECK's recorded outcome (module docstring: C0/C1/C1'/C2) --
    the state label and the status assertion result at that checkpoint."""

    model_config = ConfigDict(frozen=True)

    label: str
    status_assertion: str
    status_assertion_passed: bool


# frob:doc docs/commands/deploy.md#attestation
class AuditAttestation(BaseModel):
    """The full `frob deploy audit --vm` attestation record (module
    docstring) -- snapshot ids, per-checkpoint status assertions, and the
    three diff-based proof results, everything `--evidence-cmd` (T-0215)
    needs to record this run as ticket evidence without re-deriving
    anything from raw captures."""

    model_config = ConfigDict(frozen=True)

    vm_name: str
    base_snapshot: str
    started_at: datetime
    finished_at: datetime
    checkpoints: tuple[CheckpointResult, ...]
    idempotence_holds: bool
    artifact_freeness_holds: bool
    install_exactness_holds: bool
    install_exactness_extra: tuple[str, ...]
    install_exactness_missing: tuple[str, ...]

    # frob:doc docs/commands/deploy.md#attestation
    @property
    def passed(self) -> bool:
        """`True` iff every proof holds AND every checkpoint's status
        assertion passed -- the single field `frob deploy audit`'s exit
        code is derived from."""
        return (
            self.idempotence_holds
            and self.artifact_freeness_holds
            and self.install_exactness_holds
            and all(c.status_assertion_passed for c in self.checkpoints)
        )

    # frob:doc docs/commands/deploy.md#attestation
    def to_json(self) -> str:
        """Deterministic (sorted-key) JSON serialization -- the exact text
        `frob deploy audit` writes to its output file and hands to
        `--evidence-cmd`."""
        return json.dumps(self.model_dump(mode="json"), sort_keys=True, indent=2)


# frob:doc docs/commands/deploy.md#attestation
def build_attestation(
    *,
    vm_name: str,
    base_snapshot: str,
    started_at: datetime,
    checkpoints: tuple[CheckpointResult, ...],
    s0: StateCapture,
    s1: StateCapture,
    s1_prime: StateCapture,
    s2: StateCapture,
    expected_surface: frozenset[MutationTarget],
    finished_at: datetime | None = None,
) -> AuditAttestation:
    """Run all three diff-based proofs over the four captured states and
    assemble the `AuditAttestation` -- the one call site `_vm_runner.py`'s
    orchestration and every fixture-based unit test share, so the proof
    wiring is identical whether the captures came from a real VM or a
    test fixture dict."""
    idempotent = idempotence_holds(s1, s1_prime)
    artifact_free = artifact_freeness_holds(s0, s2)
    exact, extra, missing = install_exactness_holds(s0, s1, expected_surface)
    return AuditAttestation(
        vm_name=vm_name,
        base_snapshot=base_snapshot,
        started_at=started_at,
        finished_at=finished_at or datetime.now(UTC),
        checkpoints=checkpoints,
        idempotence_holds=idempotent,
        artifact_freeness_holds=artifact_free,
        install_exactness_holds=exact,
        install_exactness_extra=tuple(sorted(t.target for t in extra)),
        install_exactness_missing=tuple(sorted(t.target for t in missing)),
    )
