"""`frob deploy generate`: compile `std.host` (T-0255) `HostManifest` facts
into idempotent Linux/systemd install/status/uninstall bash (T-0257, deploy
epic T-0254).

Reads every node/store's `HostManifest` (`frob.strata.host_manifest_for`,
T-0255 -- NOT redefined here) out of a merged `KernelModel` and renders
three deterministic, shellcheck-clean bash scripts:

- **install.sh**: check-then-apply per step (service user exists? unit
  file hash already matches? owned path already has the right
  owner/mode?) so a re-run performs zero commands and exits 0 -- honesty
  is in the exit code, not a printed claim. Creates one dedicated,
  system-scoped, no-login service user per declared `runs_as`, writes a
  hardened `systemd` unit (`NoNewPrivileges=yes`, `ProtectSystem=strict`,
  `PrivateTmp=yes`, `CapabilityBoundingSet=` derived from `may`
  capabilities, `SystemCallFilter=` reusing the EXISTING seccomp exporter
  `frob.strata.node_allowed_syscalls` -- one join, not a second one) for
  every `unit`-marked node, and sets exact ownership/mode on every
  `owns` entry.
- **status.sh**: per unit, `systemctl is-active`/`is-enabled` plus a
  `/dev/tcp` probe of every declared `listens` port -- one line per unit,
  machine-parseable (`unit=... active=... enabled=... port:N=open|closed`).
- **uninstall.sh**: removes EXACTLY the manifest's own set -- units
  stopped+disabled+deleted, service users removed, owned paths deleted --
  nothing else. Artifact-freeness (nothing outside the manifest survives)
  is manifest COMPLETENESS, which T-0254 child 5's VM audit proves
  empirically; this script's job is just to touch nothing beyond what it
  itself declares.

Every generated script's header carries a `# frob-deploy-manifest-digest:
<sha256>` line (`manifest_digest`) -- `frob.deploy._drift`'s DEPLOY001
gate recompiles from the CURRENT model and compares full body text, never
a line-by-line diff, catching an operator hand-edit the same way
`DRIFT001` catches a stale acked doc digest.

v0 scope cut, inherited honestly from T-0255: OS users do not yet join
the trust lattice through any dedicated plumbing here -- `runs_as` is
read as a plain `HostManifest` field like any other, never model-checked
by this module. `HostManifest`/`host_manifest_for` (T-0255) and
HOST001/HOST002 (T-0256) are consumed, never redefined, here.
"""
# frob:waive INV006 reason="T-0585 INV006 first-turn-on pool: \
# src/frob/deploy/_generate.py's exclusivity-vocabulary hit is source-level \
# design-rationale/scope-cut prose (a docstring or comment describing \
# already-implemented internal behavior, verifiable by reading the code it annotates) \
# rather than a separate cross-module contract needing its own tracked invariant; \
# disposed as a calibration batch, not claim-by-claim"

from __future__ import annotations

import hashlib
import json

from pydantic import BaseModel, ConfigDict

from frob.logging import get_logger
from frob.strata import (
    HostManifest,
    KernelModel,
    Node,
    node_allowed_syscalls,
    node_may_kinds,
)
from frob.strata._host import HostOwns, host_manifest_for

_log = get_logger(__name__)

#: `may` capability KIND -> Linux capability name(s) a generated unit's
#: `CapabilityBoundingSet=` grants. Deliberately coarse (same honesty
#: posture `_export.py::_SECCOMP_KIND_MAP` documents for syscalls): a
#: `may` kind names a capability CLASS, not an exact Linux capability,
#: until the surface grammar can express finer atoms. Kinds with no entry
#: grant nothing beyond the empty (most restrictive) bounding set.
_CAP_KIND_MAP: dict[str, tuple[str, ...]] = {
    "net": ("CAP_NET_BIND_SERVICE",),
}

#: Ports below this number require `CAP_NET_BIND_SERVICE` on Linux (the
#: kernel's own privileged-port cutoff, `ip_unprivileged_port_start`'s
#: default). T-0281 item 8 (malmberg pilot finding): a node's `may net`
#: previously granted `CAP_NET_BIND_SERVICE` unconditionally, even when
#: every declared `listens` port is unprivileged -- an over-grant
#: `_node_capabilities` below now gates on this cutoff instead.
_PRIVILEGED_PORT_CUTOFF = 1024

# frob:doc docs/strata/host.md#the-deploy-generator
#: Header line every generated script carries. `_drift.py`'s DEPLOY001
#: check does not grep for this prefix specifically -- it compares full
#: script bodies -- but every generated script's header opens with it, so
#: it is documented as part of that generated-script shape.
DIGEST_HEADER_PREFIX = "# frob-deploy-manifest-digest: "

#: The one comment banner every generated script opens with, naming the
#: regeneration command so a reader never mistakes this for hand-authored
#: bash.
_GENERATED_BANNER = (
    "# GENERATED by `frob deploy generate` -- DO NOT EDIT BY HAND.\n"
    "# Re-run `frob deploy generate` to regenerate after a design change.\n"
)


# frob:doc docs/strata/host.md#the-deploy-generator
class ManifestEntry(BaseModel):
    """One node id's `HostManifest`, paired for deterministic iteration
    (`sorted_manifest_entries`) -- the one shape every renderer below
    walks instead of re-deriving node-id -> manifest pairs itself."""

    model_config = ConfigDict(frozen=True)

    node_id: str
    manifest: HostManifest
    capabilities: tuple[str, ...]
    syscalls: tuple[str, ...]


# frob:doc docs/strata/host.md#the-deploy-generator
# frob:tests tests/unit/deploy/test_generate.py::TestSorted.test_sorted kind="unit"
def sorted_manifest_entries(model: KernelModel) -> tuple[ManifestEntry, ...]:
    """Every node/store in `model` with a declared `std.host` manifest,
    sorted by node id -- the ONE deterministic walk `manifest_digest` and
    every script renderer share, so two calls over the same model always
    see facts in the same order (determinism is what makes the digest
    and the generated bash byte-for-byte reproducible)."""
    entries: list[ManifestEntry] = []
    # frob:waive PERF004 reason="sorted() is this loop's own iterable, not repeated"
    for node in sorted(model.nodes, key=lambda n: n.id):
        manifest = host_manifest_for(node)
        if manifest is None:
            continue
        entries.append(
            ManifestEntry(
                node_id=node.id,
                manifest=manifest,
                capabilities=tuple(
                    sorted(_node_capabilities(node, manifest)),
                ),
                syscalls=tuple(sorted(node_allowed_syscalls(node))),
            )
        )
    return tuple(entries)


def _node_capabilities(node: Node, manifest: HostManifest) -> frozenset[str]:
    """`CapabilityBoundingSet=` members for `node`, derived from the SAME
    `may`-kind join `node_allowed_syscalls` uses for `SystemCallFilter=`
    (`_CAP_KIND_MAP`, module docstring) -- never a second, independently
    maintained kind mapping.

    T-0281 item 8 (malmberg pilot finding): `CAP_NET_BIND_SERVICE` is only
    a real requirement when the manifest actually binds a PRIVILEGED port
    (`_PRIVILEGED_PORT_CUTOFF`) -- a `may net` node whose every declared
    `listens` port is >=1024 (or that declares no `listens` at all) never
    needs it, so granting it unconditionally was an over-grant. Other
    `_CAP_KIND_MAP` kinds (should the map grow) are unaffected by this
    port gate -- it applies to `CAP_NET_BIND_SERVICE` specifically, the
    one Linux capability whose need is itself port-dependent."""
    needs_privileged_bind = any(
        port < _PRIVILEGED_PORT_CUTOFF for port in manifest.listens
    )
    caps: set[str] = set()
    for kind in node_may_kinds(node):
        for cap in _CAP_KIND_MAP.get(kind, ()):
            if cap == "CAP_NET_BIND_SERVICE" and not needs_privileged_bind:
                continue
            caps.add(cap)
    return frozenset(caps)


# frob:doc docs/strata/host.md#the-deploy-generator
# frob:tests tests/unit/deploy/test_generate.py::TestDigest.test_det kind="unit"
def manifest_digest(model: KernelModel) -> str:
    """sha256 over a deterministic JSON serialization of every declared
    `HostManifest`, keyed by node id -- the DEPLOY001 drift lock's join
    key (`_drift.py`). Two `KernelModel`s with identical host facts,
    built in any order, always produce the same digest; anything else
    (a manifest added/removed/changed) always produces a different one."""
    entries = sorted_manifest_entries(model)
    payload = {
        entry.node_id: {
            "manifest": entry.manifest.model_dump(mode="json"),
            "capabilities": list(entry.capabilities),
            "syscalls": list(entry.syscalls),
        }
        for entry in entries
    }
    text = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _header(model: KernelModel, title: str) -> str:
    """The shared `#!/usr/bin/env bash` + banner + digest header every
    generated script opens with -- ONE place the header shape is written
    so install/status/uninstall can never desync on it."""
    digest = manifest_digest(model)
    return (
        "#!/usr/bin/env bash\n"
        f"# {title}\n"
        f"{_GENERATED_BANNER}"
        f"{DIGEST_HEADER_PREFIX}{digest}\n"
        "set -euo pipefail\n"
        "\n"
    )


def _unit_name(node_id: str) -> str:
    """`systemd` unit name for `node_id` -- `frob-deploy-<id>.service`, the
    ONE naming rule every renderer (install/status/uninstall) uses so a
    unit created by install.sh is always the exact one status.sh queries
    and uninstall.sh deletes."""
    return f"frob-deploy-{node_id}.service"


def _unit_file_path(node_id: str) -> str:
    """Absolute `systemd` unit file path for `node_id`, matching `_unit_name`."""
    return f"/etc/systemd/system/{_unit_name(node_id)}"


def _render_unit_file(entry: ManifestEntry) -> str:
    """The hardened `systemd` unit file body for one `unit`-marked node
    (docs/strata/host.md's `unit` clause docstring): `NoNewPrivileges`,
    `ProtectSystem=strict`, `PrivateTmp`, a `CapabilityBoundingSet=`
    derived from `may` capabilities, and a `SystemCallFilter=` reusing
    the existing seccomp exporter's allowed-syscall join -- never a
    second, independently maintained syscall list.

    T-0281 item 6 (malmberg pilot finding): a declared `listens` PORT
    previously drove `status.sh`'s `/dev/tcp` probe (`_status_unit_block`)
    but was never materialized into the unit itself -- an operator reading
    the unit file alone had no way to see what port the service is
    expected to bind. `_listens_comment_line` below documents every
    declared port as a `# listens: PORT` comment; full kernel-level
    network hardening (`IPAddressAllow=`/`SocketBindAllow=`) is deferred
    (docs/strata/host.md#the-honest-gap) since `std.host` has no inbound/
    outbound direction vocabulary for `listens` yet -- documenting the
    port honestly is the T-0281-scoped fix, not a fabricated allow-list."""
    manifest = entry.manifest
    read_write_paths = " ".join(sorted({o.path for o in manifest.owns}))
    cap_set = " ".join(entry.capabilities) if entry.capabilities else ""
    syscalls = " ".join(entry.syscalls)
    user_line = f"User={manifest.runs_as}\n" if manifest.runs_as else ""
    rwp_line = f"ReadWritePaths={read_write_paths}\n" if read_write_paths else ""
    listens_comment = _listens_comment_line(manifest.listens)
    return (
        "[Unit]\n"
        f"Description=frob deploy generated unit for {entry.node_id}\n"
        f"{listens_comment}"
        "\n"
        "[Service]\n"
        f"{user_line}"
        "NoNewPrivileges=yes\n"
        "ProtectSystem=strict\n"
        "PrivateTmp=yes\n"
        f"{rwp_line}"
        f"CapabilityBoundingSet={cap_set}\n"
        f"SystemCallFilter={syscalls}\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def _listens_comment_line(listens: tuple[int, ...] | list[int]) -> str:
    """`# listens: PORT[, PORT...]\\n` documenting every declared `listens`
    port on the unit itself (T-0281 item 6), or `""` when none are
    declared -- so a unit file reader never has to cross-reference
    `status.sh` just to learn what port a service is expected to bind."""
    if not listens:
        return ""
    ports = ", ".join(str(p) for p in listens)
    return f"# listens: {ports}\n"


def _distinct_runs_as(entries: tuple[ManifestEntry, ...]) -> tuple[str, ...]:
    """Every distinct `runs_as` identity declared across `entries`, in
    first-seen (== `sorted_manifest_entries`' deterministic node-id) order.

    T-0281 item 5 (malmberg pilot finding): a service-user name shared
    across more than one node/store (e.g. a store and its consuming node
    both declaring `runs_as "malmberg-ingest"`) previously got its
    `useradd`/`userdel` guard block rendered ONCE PER ENTRY -- harmless
    under `set -e` (the second `id -u` check just sees the user already
    exists) but a literal duplicate block in the generated script, which
    reads as a bug to anyone reviewing the output. This is the ONE place
    entries are collapsed to distinct identities, shared by both
    `generate_install_script` and `generate_uninstall_script` so the two
    can never dedup by different rules."""
    seen: dict[str, None] = {}
    for entry in entries:
        name = entry.manifest.runs_as
        if name is not None and name not in seen:
            seen[name] = None
    return tuple(seen)


# frob:waive DUP001 reason="mirror-image of _uninstall_user_block below by design \
# (install creates, uninstall removes the same service user); parallel \
# install/uninstall pairs read clearer kept separate than forced into one \
# parameterized helper for a 5-line body"
def _install_user_block(name: str) -> str:
    """Check-then-apply service-user creation for one distinct `runs_as`
    identity: `id -u` gates the `useradd`, so a re-run performs zero
    commands when the user already exists (idempotent-by-construction,
    T-0257's install requirement). Called once per DISTINCT identity
    (`_distinct_runs_as`, T-0281 item 5), never once per node."""
    return (
        f'if ! id -u "{name}" >/dev/null 2>&1; then\n'
        f'    useradd --system --no-create-home --shell /usr/sbin/nologin "{name}"\n'
        f'    echo "created service user {name}"\n'
        "else\n"
        f'    echo "service user {name} already present, skipping"\n'
        "fi\n"
    )


def _install_owns_block(manifest: HostManifest) -> str:
    """Check-then-apply ownership/mode for every declared `owns` entry:
    `stat` reads the CURRENT owner/mode and only calls `chown`/`chmod`
    when they differ from the declared values, and only `mkdir -p` when
    the path is missing -- a re-run over an already-correct path issues
    no filesystem-mutating command at all."""
    if not manifest.owns:
        return ""
    owner = manifest.runs_as or "root"
    lines = [_owns_check_block(entry, owner) for entry in manifest.owns]
    return "\n".join(lines)


def _owns_check_block(entry: HostOwns, owner: str) -> str:
    """One `owns` entry's check-then-apply mkdir/chown/chmod block.

    `stat -c "%a"` prints without a leading zero (e.g. "644"), while a
    declared mode commonly carries one ("0644") -- both sides are
    stripped of leading zeros before comparison so the two octal
    spellings of the same mode never look like a drift and re-trigger
    `chmod` on every idempotent re-run.
    """
    path = entry.path
    mode = entry.mode
    return (
        f'desired_mode="{mode}"\n'
        f'if [ ! -e "{path}" ]; then\n'
        f'    mkdir -p "{path}"\n'
        f'    echo "created {path}"\n'
        "fi\n"
        f'current_owner="$(stat -c "%U" "{path}")"\n'
        f'if [ "$current_owner" != "{owner}" ]; then\n'
        f'    chown "{owner}":"{owner}" "{path}"\n'
        f'    echo "chowned {path} to {owner}"\n'
        "fi\n"
        f'current_mode="$(stat -c "%a" "{path}")"\n'
        f'if [ "${{current_mode#0}}" != "${{desired_mode#0}}" ]; then\n'
        f'    chmod "{mode}" "{path}"\n'
        f'    echo "chmoded {path} to {mode}"\n'
        "fi\n"
    )


def _install_unit_block(entry: ManifestEntry) -> str:
    """Check-then-apply unit enrollment: the unit file's own sha256 is
    compared to the CONTENT `_render_unit_file` would write, so a re-run
    with no design change writes nothing and issues no `systemctl`
    command; a content change rewrites the file, reloads the daemon, and
    (re-)enables+starts the unit."""
    if not entry.manifest.is_unit:
        return ""
    unit_path = _unit_file_path(entry.node_id)
    unit_name = _unit_name(entry.node_id)
    body = _render_unit_file(entry)
    body_digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return _unit_write_block(
        unit_path, unit_name, body_digest, body
    ) + _unit_enable_start_block(unit_name)


# frob:waive DUP001 reason="dup grouped this shell-heredoc builder with \
# _waive.py::_stale_detail and dup/_rules.py::_dup001_message purely on generic \
# f-string shape -- unrelated domain (systemd unit install script), false positive"
def _unit_write_block(
    unit_path: str, unit_name: str, body_digest: str, body: str
) -> str:
    """Check-then-apply hash-compared unit-file write block."""
    return (
        f'desired_hash="{body_digest}"\n'
        f'if [ -f "{unit_path}" ]; then\n'
        f'    current_hash="$(sha256sum "{unit_path}" | cut -d" " -f1)"\n'
        "else\n"
        '    current_hash=""\n'
        "fi\n"
        'if [ "$current_hash" != "$desired_hash" ]; then\n'
        f"    cat > \"{unit_path}\" <<'FROB_UNIT_EOF'\n"
        f"{body}"
        "FROB_UNIT_EOF\n"
        "    systemctl daemon-reload\n"
        f'    echo "wrote unit {unit_name}"\n'
        "else\n"
        f'    echo "unit {unit_name} already up to date"\n'
        "fi\n"
    )


# frob:waive DUP001 reason="same false-positive grouping as _unit_write_block above \
# (dup/_rules.py::_dup001_message, _waive.py:: _stale_detail); generic f-string shape, \
# unrelated domain"
def _unit_enable_start_block(unit_name: str) -> str:
    """Check-then-apply `systemctl enable`/`start` block for `unit_name`."""
    return (
        f'if ! systemctl is-enabled --quiet "{unit_name}" 2>/dev/null; then\n'
        f'    systemctl enable "{unit_name}"\n'
        f'    echo "enabled {unit_name}"\n'
        "fi\n"
        f'if ! systemctl is-active --quiet "{unit_name}" 2>/dev/null; then\n'
        f'    systemctl start "{unit_name}"\n'
        f'    echo "started {unit_name}"\n'
        "fi\n"
    )


# frob:doc docs/strata/host.md#the-deploy-generator
# frob:tests tests/unit/deploy/test_generate.py::TestInstall.test_idempotent kind="unit"
def generate_install_script(model: KernelModel) -> str:
    """Render `install.sh`: check-then-apply, one block per node in
    `sorted_manifest_entries` order -- user, then unit, then owned paths
    (module docstring). Every step logs what it did (or that it skipped),
    so a re-run's zero-command output is itself the honest idempotency
    proof, not a claim."""
    return _render_install_script(model, sorted_manifest_entries(model))


def _render_install_script(
    model: KernelModel, entries: tuple[ManifestEntry, ...]
) -> str:
    """`generate_install_script`'s body, taking an already-computed
    `entries` walk. `generate_all` (below) computes `sorted_manifest_entries`
    exactly ONCE and passes it to this and its status/uninstall siblings --
    T-0281 item 4 (malmberg pilot finding): each of the three top-level
    `generate_*_script` functions independently re-walking the model via
    `sorted_manifest_entries` meant `host_manifest_for`'s per-node DEBUG
    log line fired three times per node for one `frob deploy generate`
    invocation. Sharing one walk cuts that back to once."""
    parts = [_header(model, "frob deploy install.sh")]
    if not entries:
        parts.append('echo "no host manifests declared, nothing to install"\n')
        return "".join(parts)
    parts.append('echo "--- service users ---"\n')
    for name in _distinct_runs_as(entries):
        parts.append(_install_user_block(name))
    for entry in entries:
        parts.append(f'echo "--- {entry.node_id} ---"\n')
        parts.append(_install_unit_block(entry))
        parts.append(_install_owns_block(entry.manifest))
    parts.append('echo "install complete"\n')
    return "".join(parts)


def _status_unit_block(entry: ManifestEntry) -> str:
    """One unit's status line: `systemctl is-active`/`is-enabled` (each
    guarded so a not-yet-installed unit reports `inactive`/`disabled`
    rather than aborting the whole script under `set -e`), plus one
    `/dev/tcp` probe per declared `listens` port."""
    if not entry.manifest.is_unit:
        return ""
    unit_name = _unit_name(entry.node_id)
    lines = [
        f'active="$(systemctl is-active "{unit_name}" 2>/dev/null || true)"\n',
        f'enabled="$(systemctl is-enabled "{unit_name}" 2>/dev/null || true)"\n',
        f'echo "unit={unit_name} node={entry.node_id} '
        'active=$active enabled=$enabled"\n',
    ]
    for port in entry.manifest.listens:
        lines.append(
            f"if timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/{port}' "
            "2>/dev/null; then\n"
            f'    echo "unit={unit_name} port={port}=open"\n'
            "else\n"
            f'    echo "unit={unit_name} port={port}=closed"\n'
            "fi\n"
        )
    return "".join(lines)


# frob:doc docs/strata/host.md#the-deploy-generator
# frob:tests tests/unit/deploy/test_generate.py::TestStatus.test_one_line kind="unit"
def generate_status_script(model: KernelModel) -> str:
    """Render `status.sh`: per-unit active/enabled state plus a listen-
    port probe, one machine-parseable `key=value ...` line per fact
    (module docstring)."""
    return _render_status_script(model, sorted_manifest_entries(model))


#: T-0281 item 7 (malmberg pilot finding): `std.host` has no host/
#: placement vocabulary yet -- every generated `status.sh` probes
#: `127.0.0.1` for every declared unit's `listens` ports regardless of
#: which physical host that unit is actually meant to run on, so a
#: multi-host deployment (e.g. malmberg's display node is a SEPARATE host
#: from its ingest node) always reports a remote unit's port as closed.
#: This comment is the honest documentation of that gap (rather than a
#: fabricated per-host partition `std.host` cannot yet express) --
#: designing the placement construct itself is filed separately
#: (docs/strata/host.md#the-honest-gap) since it is bigger than this
#: ticket's scope and may grow its own child tickets.
_MULTI_HOST_STATUS_NOTE = (
    "# NOTE: every socket probe below runs against 127.0.0.1 -- std.host\n"
    "# has no host/placement vocabulary yet, so this script cannot tell\n"
    "# which unit is meant to run on which physical host. Run this script\n"
    "# ON EACH declared host separately; a unit not actually placed here\n"
    "# will always read as closed. See docs/commands/deploy.md#scope-and-\n"
    "# honesty-notes-generate.\n"
)


def _render_status_script(
    model: KernelModel, entries: tuple[ManifestEntry, ...]
) -> str:
    """`generate_status_script`'s body, taking an already-computed
    `entries` walk (`_render_install_script`'s docstring: T-0281 item 4,
    one shared walk per `generate_all` invocation instead of three)."""
    parts = [_header(model, "frob deploy status.sh"), _MULTI_HOST_STATUS_NOTE]
    unit_entries = [e for e in entries if e.manifest.is_unit]
    if not unit_entries:
        parts.append('echo "no units declared"\n')
        return "".join(parts)
    for entry in unit_entries:
        parts.append(_status_unit_block(entry))
    return "".join(parts)


def _uninstall_unit_block(entry: ManifestEntry) -> str:
    """Stop+disable+delete exactly this node's own generated unit --
    check-then-apply so re-running uninstall against an already-removed
    unit issues no command (uninstall is idempotent too, same posture as
    install)."""
    if not entry.manifest.is_unit:
        return ""
    unit_name = _unit_name(entry.node_id)
    unit_path = _unit_file_path(entry.node_id)
    return (
        f'if systemctl is-active --quiet "{unit_name}" 2>/dev/null; then\n'
        f'    systemctl stop "{unit_name}"\n'
        "fi\n"
        f'if systemctl is-enabled --quiet "{unit_name}" 2>/dev/null; then\n'
        f'    systemctl disable "{unit_name}"\n'
        "fi\n"
        f'if [ -f "{unit_path}" ]; then\n'
        f'    rm -f "{unit_path}"\n'
        "    systemctl daemon-reload\n"
        f'    echo "removed unit {unit_name}"\n'
        "fi\n"
    )


def _uninstall_owns_block(manifest: HostManifest) -> str:
    """Delete EXACTLY the manifest's own declared `owns` paths -- never a
    parent directory, never a glob, so uninstall cannot reach outside
    what install itself created (artifact-freeness, module docstring)."""
    lines: list[str] = []
    for entry in manifest.owns:
        path = entry.path
        lines.append(
            f'if [ -e "{path}" ]; then\n'
            f'    rm -rf "{path}"\n'
            f'    echo "removed {path}"\n'
            "fi\n"
        )
    return "".join(lines)


# frob:waive DUP001 reason="mirror-image of _install_user_block above by design; see \
# that function's waiver"
def _uninstall_user_block(name: str) -> str:
    """Remove exactly one distinct `runs_as` identity's service user --
    check-then-apply via `id -u` first, matching `_install_user_block`'s
    mirror-image gate. Called once per DISTINCT identity
    (`_distinct_runs_as`, T-0281 item 5), never once per node -- a user
    shared by two nodes/stores is removed once, not `userdel`'d twice."""
    return (
        f'if id -u "{name}" >/dev/null 2>&1; then\n'
        f'    userdel "{name}"\n'
        f'    echo "removed service user {name}"\n'
        "fi\n"
    )


# frob:doc docs/strata/host.md#the-deploy-generator
# frob:tests tests/unit/deploy/test_generate.py::TestUninstall.test_removes kind="unit"
def generate_uninstall_script(model: KernelModel) -> str:
    """Render `uninstall.sh`: units stopped+disabled+deleted, owned paths
    removed, service users deleted -- EXACTLY the manifest set, reverse
    order of install (unit down before its user is removed, module
    docstring's artifact-freeness requirement)."""
    return _render_uninstall_script(model, sorted_manifest_entries(model))


def _render_uninstall_script(
    model: KernelModel, entries: tuple[ManifestEntry, ...]
) -> str:
    """`generate_uninstall_script`'s body, taking an already-computed
    `entries` walk (`_render_install_script`'s docstring: T-0281 item 4,
    one shared walk per `generate_all` invocation instead of three)."""
    parts = [_header(model, "frob deploy uninstall.sh")]
    if not entries:
        parts.append('echo "no host manifests declared, nothing to uninstall"\n')
        return "".join(parts)
    for entry in entries:
        parts.append(f'echo "--- {entry.node_id} ---"\n')
        parts.append(_uninstall_unit_block(entry))
        parts.append(_uninstall_owns_block(entry.manifest))
    parts.append('echo "--- service users ---"\n')
    for name in _distinct_runs_as(entries):
        parts.append(_uninstall_user_block(name))
    parts.append('echo "uninstall complete"\n')
    return "".join(parts)


# frob:doc docs/strata/host.md#the-deploy-generator
# frob:tests tests/unit/deploy/test_generate.py::TestAll.test_returns_all kind="unit"
def generate_all(model: KernelModel) -> dict[str, str]:
    """`{"install.sh": ..., "status.sh": ..., "uninstall.sh": ...}`, PLUS
    `{"install.ps1": ..., "status.ps1": ..., "uninstall.ps1": ...}` when
    `model` declares at least one `HostPlatform.WINDOWS` manifest
    (T-0264, `frob.deploy._generate_windows`) -- the ONE call site `frob
    deploy generate`'s CLI runner and `_drift.py`'s DEPLOY001
    recompilation both use, so no generated filename can ever drift apart
    between the writer and the checker, on either platform.

    T-0281 item 4 (malmberg pilot finding): `sorted_manifest_entries` is
    computed exactly ONCE here and shared across all renderers (bash AND,
    when applicable, windows), instead of each one independently
    re-walking the model -- the shared walk is what stops `host_manifest_
    for`'s per-node DEBUG log line from firing once per renderer per node
    for one `frob deploy generate` run."""
    entries = sorted_manifest_entries(model)
    rendered = {
        "install.sh": _render_install_script(model, entries),
        "status.sh": _render_status_script(model, entries),
        "uninstall.sh": _render_uninstall_script(model, entries),
    }
    # Deferred import: `_generate_windows` imports FROM this module
    # (`DIGEST_HEADER_PREFIX`/`ManifestEntry`/`manifest_digest`/
    # `sorted_manifest_entries`) -- a top-level import here would cycle.
    from ._generate_windows import (
        _krb_manifest_by_node_id,
        _render_windows_install_script,
        _render_windows_status_script,
        _render_windows_uninstall_script,
        windows_entries,
    )

    win_entries = windows_entries(entries)
    if win_entries:
        krb_by_node = _krb_manifest_by_node_id(model)
        rendered["install.ps1"] = _render_windows_install_script(
            model, win_entries, krb_by_node
        )
        rendered["status.ps1"] = _render_windows_status_script(model, win_entries)
        rendered["uninstall.ps1"] = _render_windows_uninstall_script(model, win_entries)
    return rendered
