//! The generated languages page `docs/reference/languages.md`: every adapter extension with its
//! fidelity and capability-matrix cells (code-model.md section 3, language-engines.md section 5).

// frob:ticket 01M47QKW1R6KY7K1H6N4M1BX5H

use std::fmt::Write as _;

use crate::registry::fidelity_report;

/// Header comment of the generated page.
const HEADER: &str = "<!-- generated by gob_symbols::languages_page; do not edit -->\n";

/// Renders the languages page: an extension table, then one capability table per adapter.
pub fn languages_page() -> String {
    let report = fidelity_report();
    let mut out = String::from(HEADER);
    out.push_str("\n# Languages\n\nCells: `Implemented` (with its precision), `NotApplicable` (the language has no such concept) or `Gap` (not provided yet; the answer is Unknown).\n");
    out.push_str("\n## Extensions\n\n| Extension | Language | Fidelity |\n|---|---|---|\n");
    let mut by_ext: Vec<(&str, &str, String)> = report
        .iter()
        .flat_map(|r| {
            r.extensions
                .iter()
                .map(move |e| (*e, r.language, r.fidelity.to_string()))
        })
        .collect();
    by_ext.sort();
    for (ext, lang, fid) in &by_ext {
        let _ = writeln!(out, "| `.{ext}` | {lang} | {fid} |");
    }
    for r in &report {
        let _ = write!(out, "\n## {}\n\nFidelity {}", r.language, r.fidelity);
        if !r.extensions.is_empty() {
            let exts: Vec<String> = r.extensions.iter().map(|e| format!("`.{e}`")).collect();
            let _ = write!(out, "; extensions {}", exts.join(", "));
        }
        out.push_str(".\n\n| Capability | Cell | Precision |\n|---|---|---|\n");
        for (c, p) in &r.capabilities {
            let _ = writeln!(out, "| {} | {} | {} |", c.name(), p.cell(), p.label());
        }
    }
    tracing::debug!(
        adapters = report.len(),
        extensions = by_ext.len(),
        "languages page rendered"
    );
    out
}
