//! Raw directive arguments, the typed-argument trait and the derive's cursor.

use gob_text::TextRange;

/// One argument value as written, with its byte range in the scanned file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    /// The value with quotes removed and escapes resolved.
    pub value: String,
    /// Byte range of the token in the file, quotes included.
    pub range: TextRange,
    /// True when the value was written in double quotes.
    pub quoted: bool,
}

/// A `key=value` argument as written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Keyed {
    /// The key text.
    pub key: String,
    /// Byte range of the key.
    pub key_range: TextRange,
    /// The value token.
    pub value: Token,
}

/// The raw arguments of one directive: positionals and `key=value` pairs.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ArgList {
    /// Positional tokens in source order.
    pub positional: Vec<Token>,
    /// Keyed pairs in source order.
    pub keyed: Vec<Keyed>,
}

impl ArgList {
    /// The first value written for `key`, if any.
    pub fn get(&self, key: &str) -> Option<&Token> {
        self.keyed.iter().find(|k| k.key == key).map(|k| &k.value)
    }
}

/// Why typed argument parsing failed.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ArgError {
    /// A required argument is absent.
    #[error("missing required argument `{name}`")]
    Missing {
        /// Field name or key of the absent argument.
        name: String,
    },
    /// A value does not have the expected shape.
    #[error("invalid value {value:?} for `{name}`: expected {expected}")]
    Invalid {
        /// Field name or key.
        name: String,
        /// The offending text.
        value: String,
        /// What was expected.
        expected: &'static str,
        /// Where the value sits.
        range: TextRange,
    },
    /// A `key=` the directive does not declare.
    #[error("unknown argument `{key}=`")]
    UnknownKey {
        /// The key as written.
        key: String,
        /// Where the key sits.
        range: TextRange,
    },
    /// A positional argument beyond what the directive takes.
    #[error("unexpected extra argument {value:?}")]
    Unexpected {
        /// The extra text.
        value: String,
        /// Where it sits.
        range: TextRange,
    },
    /// The same `key=` given twice.
    #[error("argument `{key}=` given more than once")]
    Duplicate {
        /// The repeated key.
        key: String,
        /// Where the second occurrence sits.
        range: TextRange,
    },
}

impl ArgError {
    /// The byte range to point at, when the error has one.
    pub fn range(&self) -> Option<TextRange> {
        match self {
            Self::Missing { .. } => None,
            Self::Invalid { range, .. }
            | Self::UnknownKey { range, .. }
            | Self::Unexpected { range, .. }
            | Self::Duplicate { range, .. } => Some(*range),
        }
    }
}

/// Primitive kind of an argument value, for docs and the JSON schema.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArgKind {
    /// Free text.
    Str,
    /// An unsigned 32-bit integer.
    U32,
    /// `true` or `false`.
    Bool,
}

impl ArgKind {
    /// The JSON schema `type` name for this kind.
    pub const fn json_type(self) -> &'static str {
        match self {
            Self::Str => "string",
            Self::U32 => "integer",
            Self::Bool => "boolean",
        }
    }
}

/// Static description of one directive argument, generated by the derive.
#[allow(
    clippy::struct_excessive_bools,
    reason = "independent facts of one declaration"
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ArgMeta {
    /// Field name.
    pub name: &'static str,
    /// The `key=` spelling for keyed arguments.
    pub key: Option<&'static str>,
    /// True for positional (and list) arguments.
    pub positional: bool,
    /// True when the argument takes all remaining positionals.
    pub list: bool,
    /// True when the argument may be omitted.
    pub optional: bool,
    /// Kind of one value.
    pub kind: ArgKind,
    /// True when the value is a ticket id (checked for abbreviation, DSL002).
    pub ticket_ref: bool,
    /// One-line summary from the field's doc comment.
    pub summary: &'static str,
}

/// A type a directive argument can be parsed into.
pub trait FromArg: Sized {
    /// The primitive kind of the type.
    const KIND: ArgKind;

    /// Parse one token; the error names what was expected.
    ///
    /// # Errors
    ///
    /// A short description of the expected shape when the token is invalid.
    fn from_token(token: &Token) -> Result<Self, &'static str>;
}

impl FromArg for String {
    const KIND: ArgKind = ArgKind::Str;

    fn from_token(token: &Token) -> Result<Self, &'static str> {
        Ok(token.value.clone())
    }
}

impl FromArg for u32 {
    const KIND: ArgKind = ArgKind::U32;

    fn from_token(token: &Token) -> Result<Self, &'static str> {
        token.value.parse().map_err(|_| "an unsigned integer")
    }
}

impl FromArg for bool {
    const KIND: ArgKind = ArgKind::Bool;

    fn from_token(token: &Token) -> Result<Self, &'static str> {
        token.value.parse().map_err(|_| "`true` or `false`")
    }
}

impl FromArg for gob_rules::RuleId {
    const KIND: ArgKind = ArgKind::Str;

    fn from_token(token: &Token) -> Result<Self, &'static str> {
        token.value.parse().map_err(|_| "a rule id such as COV006")
    }
}

/// Reads typed fields out of an [`ArgList`]; used by derive-generated code.
#[derive(Debug)]
pub struct Cursor<'a> {
    args: &'a ArgList,
    next: usize,
}

impl<'a> Cursor<'a> {
    /// Start reading `args` from the first positional.
    pub fn new(args: &'a ArgList) -> Self {
        Self { args, next: 0 }
    }

    fn convert<T: FromArg>(name: &str, token: &Token) -> Result<T, ArgError> {
        T::from_token(token).map_err(|expected| ArgError::Invalid {
            name: name.to_owned(),
            value: token.value.clone(),
            expected,
            range: token.range,
        })
    }

    /// The next required positional, parsed as `T`.
    ///
    /// # Errors
    ///
    /// [`ArgError::Missing`] when none is left, [`ArgError::Invalid`] on a bad value.
    pub fn positional<T: FromArg>(&mut self, name: &str) -> Result<T, ArgError> {
        self.positional_opt(name)?.ok_or_else(|| ArgError::Missing {
            name: name.to_owned(),
        })
    }

    /// The next positional if present, parsed as `T`.
    ///
    /// # Errors
    ///
    /// [`ArgError::Invalid`] on a bad value.
    pub fn positional_opt<T: FromArg>(&mut self, name: &str) -> Result<Option<T>, ArgError> {
        let Some(token) = self.args.positional.get(self.next) else {
            return Ok(None);
        };
        self.next += 1;
        Self::convert(name, token).map(Some)
    }

    /// A required `key=` value parsed as `T`.
    ///
    /// # Errors
    ///
    /// [`ArgError::Missing`] when absent, [`ArgError::Invalid`] on a bad value.
    pub fn keyed<T: FromArg>(&mut self, key: &str) -> Result<T, ArgError> {
        self.keyed_opt(key)?.ok_or_else(|| ArgError::Missing {
            name: key.to_owned(),
        })
    }

    /// An optional `key=` value parsed as `T`.
    ///
    /// # Errors
    ///
    /// [`ArgError::Invalid`] on a bad value.
    pub fn keyed_opt<T: FromArg>(&mut self, key: &str) -> Result<Option<T>, ArgError> {
        self.args
            .get(key)
            .map(|token| Self::convert(key, token))
            .transpose()
    }

    /// Every remaining positional parsed as `T`.
    ///
    /// # Errors
    ///
    /// [`ArgError::Invalid`] on the first bad value.
    pub fn list<T: FromArg>(&mut self, name: &str) -> Result<Vec<T>, ArgError> {
        let rest = self.args.positional.get(self.next..).unwrap_or_default();
        self.next = self.args.positional.len();
        rest.iter().map(|t| Self::convert(name, t)).collect()
    }

    /// Reject undeclared or repeated keys and leftover positionals.
    ///
    /// # Errors
    ///
    /// [`ArgError::UnknownKey`], [`ArgError::Duplicate`] or [`ArgError::Unexpected`].
    pub fn finish(&self, keys: &[&str]) -> Result<(), ArgError> {
        for (i, k) in self.args.keyed.iter().enumerate() {
            if !keys.contains(&k.key.as_str()) {
                return Err(ArgError::UnknownKey {
                    key: k.key.clone(),
                    range: k.key_range,
                });
            }
            if self.args.keyed[..i].iter().any(|p| p.key == k.key) {
                return Err(ArgError::Duplicate {
                    key: k.key.clone(),
                    range: k.key_range,
                });
            }
        }
        match self.args.positional.get(self.next) {
            Some(extra) => Err(ArgError::Unexpected {
                value: extra.value.clone(),
                range: extra.range,
            }),
            None => Ok(()),
        }
    }
}
