//! The `Directive` trait, its static metadata, the registry and the schema.

use std::collections::BTreeMap;

use crate::args::{ArgError, ArgList, ArgMeta};

/// A directive verb; implemented by `#[derive(Directive)]`.
pub trait Directive: Sized {
    /// Namespace the verb lives in (`frob`).
    const NAMESPACE: &'static str;
    /// The verb word (`ticket`).
    const VERB: &'static str;

    /// Build the typed directive from raw arguments.
    ///
    /// # Errors
    ///
    /// [`ArgError`] when arguments are missing, unknown or malformed.
    fn parse_args(args: &ArgList) -> Result<Self, ArgError>;
}

/// Static description of a directive, generated by the derive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DirectiveMeta {
    /// Namespace (`frob`).
    pub namespace: &'static str,
    /// Verb word (`ticket`).
    pub verb: &'static str,
    /// One-line summary from the doc comment.
    pub summary: &'static str,
    /// Declared arguments in field order.
    pub args: &'static [ArgMeta],
}

impl DirectiveMeta {
    /// The JSON schema fragment (an object schema) for this directive's arguments.
    ///
    /// Positional and list arguments appear under their field name, keyed
    /// ones under their key; lists are arrays of their element kind.
    pub fn json_schema(&self) -> schemars::Schema {
        let mut props = serde_json::Map::new();
        let mut required = Vec::new();
        for a in self.args {
            let name = a.key.unwrap_or(a.name);
            let scalar = serde_json::json!({ "type": a.kind.json_type() });
            let mut prop = if a.list {
                serde_json::json!({ "type": "array", "items": scalar })
            } else {
                scalar
            };
            if !a.summary.is_empty() {
                prop["description"] = a.summary.into();
            }
            props.insert(name.to_owned(), prop);
            if !a.optional && !a.list {
                required.push(name);
            }
        }
        let value = serde_json::json!({
            "title": format!("{}:{}", self.namespace, self.verb),
            "description": self.summary,
            "type": "object",
            "properties": props,
            "required": required,
            "additionalProperties": false,
        });
        schemars::Schema::try_from(value).unwrap_or_else(|_| unreachable!("an object is a schema"))
    }

    /// `namespace:verb`.
    pub fn qualified(&self) -> String {
        format!("{}:{}", self.namespace, self.verb)
    }
}

/// An inventory record of one directive, submitted by `#[derive(Directive)]`.
#[derive(Debug)]
pub struct DirectiveEntry {
    pub(crate) meta: &'static DirectiveMeta,
    pub(crate) validate: fn(&ArgList) -> Result<(), ArgError>,
}

impl DirectiveEntry {
    /// Wrap a directive's metadata and validator for registration.
    pub const fn new(
        meta: &'static DirectiveMeta,
        validate: fn(&ArgList) -> Result<(), ArgError>,
    ) -> Self {
        Self { meta, validate }
    }
}

inventory::collect!(DirectiveEntry);

/// Validate `args` against `D` and discard the value; stored in the registry.
///
/// # Errors
///
/// The [`ArgError`] from `D::parse_args`.
pub fn validate<D: Directive>(args: &ArgList) -> Result<(), ArgError> {
    D::parse_args(args).map(|_| ())
}

/// Every directive linked into the binary, sorted by namespace then verb.
pub fn all_directives() -> impl Iterator<Item = &'static DirectiveMeta> {
    let mut metas: Vec<&'static DirectiveMeta> = inventory::iter::<DirectiveEntry>()
        .map(|e| e.meta)
        .collect();
    metas.sort_by_key(|m| (m.namespace, m.verb));
    metas.into_iter()
}

/// Registered entries keyed by `(namespace, verb)`.
pub(crate) fn entries() -> BTreeMap<(&'static str, &'static str), &'static DirectiveEntry> {
    inventory::iter::<DirectiveEntry>()
        .map(|e| ((e.meta.namespace, e.meta.verb), e))
        .collect()
}
