//! `crunk tokens` end to end: write, `--target` preview, `--check` drift and `--dry-run`.

// frob:ticket 01M43ARZH9F9MCPJCKXM635E0X

use std::path::Path;

use gob_cli::run_for_test;
use serde_json::Value;

const SPEC: &str = r##"[project]
css_root = "styles"
tokens_file = "tokens.css"
root_font_size = 16

[palette]
ink = "#111"

[scales]
spacing = [0, 8]
font_sizes = [16]
radii = [0]

[typography]
families = ["Inter"]
weights = [400]

[org]
buckets = ["base"]

[tokens]
json_file = "tokens.json"

[tailwind]
tokens_file = "tailwind.tokens.json"
namespace_keys = true
"##;

fn project() -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(dir.path().join("crunk.toml"), SPEC).expect("write spec");
    dir
}

fn crunk(dir: &Path, args: &[&str]) -> (i32, String, String) {
    run_for_test(&crunk::cli(), args, dir)
}

fn json(out: &str) -> Value {
    serde_json::from_str(out).unwrap_or_else(|e| panic!("not json ({e}): {out}"))
}

// frob:tests crates/crunk/src/tokens.rs::Tokens
#[test]
fn bare_tokens_writes_every_configured_file_and_check_then_passes() {
    let dir = project();
    let (code, out, err) = crunk(dir.path(), &["tokens", "--json"]);
    assert_eq!(code, 0, "{out} {err}");
    let env = json(&out);
    assert_eq!(env["data"]["mode"], "write");
    assert_eq!(env["data"]["files"].as_array().unwrap().len(), 3);
    assert!(dir.path().join("styles/tokens.css").is_file());
    assert!(dir.path().join("tokens.json").is_file());
    assert!(dir.path().join("tailwind.tokens.json").is_file());

    let (code, out, _) = crunk(dir.path(), &["tokens", "--check", "--json"]);
    assert_eq!(code, 0, "{out}");
    assert_eq!(json(&out)["data"]["status"], "clean");
}

// frob:tests crates/crunk/src/tokens.rs::Tokens
#[test]
fn a_hand_edited_tokens_css_fails_check_with_exit_one_naming_the_file() {
    let dir = project();
    crunk(dir.path(), &["tokens"]);
    let css = dir.path().join("styles/tokens.css");
    let edited = std::fs::read_to_string(&css)
        .unwrap()
        .replace("#111111", "#ff00ff");
    std::fs::write(&css, edited).unwrap();

    let (code, out, _) = crunk(dir.path(), &["tokens", "--check", "--json"]);
    assert_eq!(code, 1, "{out}");
    let env = json(&out);
    assert_eq!(env["data"]["status"], "drifted");
    let css_row = env["data"]["files"]
        .as_array()
        .unwrap()
        .iter()
        .find(|f| f["target"] == "css")
        .unwrap();
    assert_eq!(css_row["path"], "styles/tokens.css");
    assert_eq!(css_row["status"], "drifted");

    let (code, _, err) = crunk(dir.path(), &["tokens", "--check", "--text"]);
    assert_eq!(code, 1);
    assert!(err.contains("styles/tokens.css (drifted)"), "{err}");

    let (code, _, _) = crunk(dir.path(), &["tokens"]);
    assert_eq!(code, 0, "bare tokens regenerates");
    let (code, _, _) = crunk(dir.path(), &["tokens", "--check"]);
    assert_eq!(code, 0);
}

// frob:tests crates/crunk/src/tokens.rs::Tokens
#[test]
fn a_missing_file_fails_check() {
    let dir = project();
    let (code, out, _) = crunk(dir.path(), &["tokens", "--check", "--json"]);
    assert_eq!(code, 1, "{out}");
    let files = json(&out)["data"]["files"].clone();
    assert!(
        files
            .as_array()
            .unwrap()
            .iter()
            .all(|f| f["status"] == "missing")
    );
}

// frob:tests crates/crunk/src/tokens.rs::Tokens
#[test]
fn target_preview_prints_the_render_and_writes_nothing() {
    let dir = project();
    let (code, out, err) = crunk(dir.path(), &["tokens", "--target", "json", "--json"]);
    assert_eq!(code, 0, "{out} {err}");
    let env = json(&out);
    assert_eq!(env["data"]["mode"], "preview");
    let content = env["data"]["content"].as_str().unwrap();
    assert!(content.contains("\"color-ink\": \"#111111\""), "{content}");
    assert!(
        !dir.path().join("tokens.json").exists(),
        "preview must not write"
    );
    assert!(!dir.path().join("styles").exists());

    let (code, text, _) = crunk(dir.path(), &["tokens", "--target", "css", "--text"]);
    assert_eq!(code, 0);
    assert!(
        text.starts_with("/* GENERATED by crunk tokens -- edit crunk.toml instead. */\n:root {\n"),
        "{text}"
    );
    assert!(!dir.path().join("styles").exists());
}

// frob:tests crates/crunk/src/tokens.rs::Tokens
#[test]
fn dry_run_reports_the_files_without_writing_them() {
    let dir = project();
    let (code, out, _) = crunk(dir.path(), &["tokens", "--dry-run", "--json"]);
    assert_eq!(code, 0, "{out}");
    assert_eq!(json(&out)["data"]["mode"], "dryrun");
    assert!(!dir.path().join("styles").exists());
}

// frob:tests crates/crunk/src/tokens.rs::Tokens
#[test]
fn an_unknown_target_is_a_usage_error_and_a_bad_spec_is_a_refusal() {
    let dir = project();
    let (code, _, _) = crunk(dir.path(), &["tokens", "--target", "uss"]);
    assert_eq!(code, 2);
    std::fs::write(dir.path().join("crunk.toml"), "[palette]\nink = \"nope\"\n").unwrap();
    let (code, out, _) = crunk(dir.path(), &["tokens", "--json"]);
    assert_eq!(code, 3, "{out}");
    assert_eq!(json(&out)["error"]["code"], "E-SPEC");
}
