//! The declaration side of `#[rule(..)]` (D107, `docs/design/rule-authoring.md` section 2).
//!
//! [`RuleDef`] is the static description the attribute generates (every field required, file and
//! line recorded); [`RuleDecl`] ties it to the rule type; [`FileRule`], [`RepoRule`] and
//! [`Measured`] are the evaluation traits the attribute probes at the declaration so a rule
//! without an evaluation fails to compile. The old `#[derive(Rule)]` and [`crate::RuleMeta`] are
//! deprecated and keep working until the migration tickets delete them.

use std::marker::PhantomData;

use crate::meta::{FixKind, Polarity, Scope, Severity};

/// Which files a rule applies to; maps 1:1 onto GRL `lang *`, `lang [..]` and `lang -`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Applies {
    /// Every language that supplies the capabilities.
    Universal {
        /// Capabilities the rule reads.
        needs: &'static [gob_caps::Capability],
        /// Lowest fidelity the rule accepts.
        min_fidelity: gob_caps::Fidelity,
    },
    /// Only the named languages.
    Languages {
        /// The languages.
        langs: &'static [gob_caps::Lang],
        /// Capabilities the rule reads.
        needs: &'static [gob_caps::Capability],
        /// Lowest fidelity the rule accepts.
        min_fidelity: gob_caps::Fidelity,
    },
    /// Not about files in a language (ledger, release, config).
    Project,
}

/// The declared, static description of one rule, generated by `#[rule(..)]`.
#[derive(Debug)]
pub struct RuleDef {
    /// Rule id, `FAMILY` plus three digits.
    pub id: &'static str,
    /// Lowercase kebab-case slug.
    pub slug: &'static str,
    /// Family prefix, derived from the id.
    pub family: &'static str,
    /// Default severity.
    pub severity: Severity,
    /// Polarity class.
    pub polarity: Polarity,
    /// Whether the rule must account for the subjects it measured.
    pub must_measure: bool,
    /// File or repo scope.
    pub scope: Scope,
    /// Fix kind.
    pub fix: FixKind,
    /// Applicability declaration.
    pub applies: Applies,
    /// Cache version.
    pub version: u32,
    /// First release carrying the rule.
    pub since: &'static str,
    /// The colocated `.md` page, `include_str!`d by the macro.
    pub doc: &'static str,
    /// Source file of the declaration (`file!()`).
    pub file: &'static str,
    /// Source line of the declaration (`line!()`).
    pub line: u32,
}

impl RuleDef {
    /// Placeholder the macro emits after reporting an error, so one mistake is one diagnostic.
    #[doc(hidden)]
    pub const POISONED: RuleDef = RuleDef {
        id: "POISONED",
        slug: "poisoned",
        family: "POISONED",
        severity: Severity::Advisory,
        polarity: Polarity::P0,
        must_measure: false,
        scope: Scope::File,
        fix: FixKind::Manual,
        applies: Applies::Project,
        version: 0,
        since: "0.0.0",
        doc: "",
        file: "",
        line: 0,
    };
}

/// A rule declared with `#[rule(..)]`; implemented by the attribute only.
pub trait RuleDecl {
    /// The static description of this rule.
    const DEF: &'static RuleDef;
}

/// A finding emitted through [`Out`] before the pipeline anchors it (reshaped by the pipeline work).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Emitted {
    /// The id stamped by [`Out`], never chosen by the rule body.
    pub rule: &'static str,
    /// Byte offset of the finding.
    pub offset: usize,
    /// Message.
    pub message: String,
}

/// Typed sink that stamps `R`'s id on every finding, so a rule cannot emit another rule's id.
pub struct Out<'a, R> {
    sink: &'a mut Vec<Emitted>,
    rule: PhantomData<R>,
}

impl<'a, R: RuleDecl> Out<'a, R> {
    /// A sink appending to `sink`.
    pub fn new(sink: &'a mut Vec<Emitted>) -> Self {
        Self {
            sink,
            rule: PhantomData,
        }
    }

    /// Record a finding at `offset`, stamped with `R`'s id.
    pub fn fire(&mut self, offset: usize, message: impl Into<String>) {
        tracing::trace!(rule = R::DEF.id, offset, "rule fired");
        self.sink.push(Emitted {
            rule: R::DEF.id,
            offset,
            message: message.into(),
        });
    }
}

/// The per-file context a [`FileRule`] reads, generic over the product host `P`.
pub struct FileCx<'a, P: ?Sized> {
    /// The product host that supplies facts.
    pub host: &'a P,
    /// File text.
    pub text: &'a str,
}

/// A rule judging one file against host `P`; chosen by `scope = File`.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is declared `scope = File` but does not implement `FileRule<{P}>`",
    note = "write `impl<P: ?Sized + YourHost> FileRule<P> for {Self}`, where `host = YourHost` in `#[rule(..)]`"
)]
pub trait FileRule<P: ?Sized>: RuleDecl {
    /// Examine one file, emitting findings through `out`.
    fn check(&self, cx: &FileCx<'_, P>, out: &mut Out<'_, Self>)
    where
        Self: Sized;
}

/// A rule judging the whole repository against host `P`; chosen by `scope = Repo`.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is declared `scope = Repo` but does not implement `RepoRule<{P}>`",
    note = "write `impl<P: ?Sized + YourHost> RepoRule<P> for {Self}`, where `host = YourHost` in `#[rule(..)]`"
)]
pub trait RepoRule<P: ?Sized>: RuleDecl {
    /// Examine the repository, emitting findings through `out`.
    fn check(&self, host: &P, out: &mut Out<'_, Self>)
    where
        Self: Sized;
}

/// Subject accounting a `must_measure = true` rule must provide.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is declared `must_measure = true` but does not implement `Measured<{P}>`",
    note = "implement `Measured<P>` so the pipeline can tell a clean pass from an empty one"
)]
pub trait Measured<P: ?Sized>: RepoRule<P> {
    /// How many subjects the rule examined.
    fn subjects(&self, host: &P) -> usize;
}

/// The product-side bind: instantiating this for a rule and a host is the "does this product
/// host that rule" check (an unsatisfied bound is a compile error at the product's list).
pub fn run_file<R: FileRule<P>, P: ?Sized>(rule: &R, host: &P, text: &str) -> Vec<Emitted> {
    let mut found = Vec::new();
    rule.check(&FileCx { host, text }, &mut Out::new(&mut found));
    tracing::debug!(rule = R::DEF.id, found = found.len(), "file rule ran");
    found
}

/// The product-side bind for a repo rule: instantiating this is the "does this product host that
/// rule" check.
pub fn run_repo<R: RepoRule<P>, P: ?Sized>(rule: &R, host: &P) -> Vec<Emitted> {
    let mut found = Vec::new();
    rule.check(host, &mut Out::new(&mut found));
    tracing::debug!(rule = R::DEF.id, found = found.len(), "repo rule ran");
    found
}
