//! The generator behind `cargo dev gen rules-index` and the crate freshness test (D107, section 4).
//!
//! A rule crate keeps one file per `#[rule(..)]` rule in `src/rules/<id>.rs`. The crate's
//! `src/rules/mod.rs` is generated from those files: the `mod` lines, `METAS`, the [`RuleIndex`]
//! with its const uniqueness check, `bind` and a freshness test. rustc never sees a file nobody
//! mentions and `build.rs` is banned, so a stale index is caught here (GEN001) and by the test.
//!
//! [`RuleIndex`]: crate::RuleIndex

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// First line of every generated index; hand-written `mod.rs` files lack it.
pub const HEADER: &str = "// @generated by `cargo dev gen rules-index`; do not edit by hand.";

/// A rule file found in `src/rules/`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuleSrc {
    /// File stem, which must equal the lowercase rule id.
    pub stem: String,
    /// The rule id from the attribute.
    pub id: String,
    /// Name of the unit struct the attribute is on.
    pub ty: String,
    /// `scope = ..` of the attribute.
    pub scope: SrcScope,
}

/// `scope` as written in the attribute.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SrcScope {
    /// `scope = File`.
    File,
    /// `scope = Repo`.
    Repo,
}

/// Why an index could not be generated or is stale.
#[derive(Debug, thiserror::Error)]
pub enum IndexError {
    /// A directory or file could not be read.
    #[error("read {}: {source}", path.display())]
    Io {
        /// The path involved.
        path: PathBuf,
        /// Underlying error.
        source: std::io::Error,
    },
    /// A rule file is not in the expected shape.
    #[error("{}: {reason}", path.display())]
    Shape {
        /// The offending rule file.
        path: PathBuf,
        /// What is wrong.
        reason: String,
    },
    /// `mod.rs` exists, is hand-written, and the crate has attribute rules.
    #[error("{}: hand-written mod.rs in a crate with #[rule] rules; delete it and run `cargo dev gen rules-index --write`", path.display())]
    HandWritten {
        /// The hand-written `mod.rs`.
        path: PathBuf,
    },
    /// The committed index differs from what the rule files imply.
    #[error("{}: rule index is stale; run `cargo dev gen rules-index --write`", path.display())]
    Stale {
        /// The committed `mod.rs`.
        path: PathBuf,
    },
}

/// Index of the unit-struct rule declared by each `#[rule(..)]` file under `crate_dir/src/rules`.
///
/// Files holding the legacy `#[derive(Rule)]` are skipped; `mod.rs` and `retired.rs` are not rules.
///
/// # Errors
/// [`IndexError`] when a directory cannot be read or an attribute rule is malformed.
pub fn scan(crate_dir: &Path) -> Result<Vec<RuleSrc>, IndexError> {
    let dir = crate_dir.join("src").join("rules");
    let entries = match std::fs::read_dir(&dir) {
        Ok(e) => e,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(source) => return Err(IndexError::Io { path: dir, source }),
    };
    let mut out = Vec::new();
    for entry in entries {
        let path = entry
            .map_err(|source| IndexError::Io {
                path: dir.clone(),
                source,
            })?
            .path();
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()).map(str::to_owned) else {
            continue;
        };
        let is_rs = path.extension().is_some_and(|e| e == "rs");
        if !is_rs || stem == "mod" || stem == "retired" {
            continue;
        }
        let text = std::fs::read_to_string(&path).map_err(|source| IndexError::Io {
            path: path.clone(),
            source,
        })?;
        if let Some(src) = parse_rule_file(&path, &stem, &text)? {
            tracing::debug!(rule = %src.id, file = %path.display(), "indexed rule file");
            out.push(src);
        }
    }
    out.sort_by(|a, b| a.stem.cmp(&b.stem));
    Ok(out)
}

/// The text of the first `#[rule(..)]` attribute in `text`, found at the start of a line.
fn attribute_body(text: &str) -> Option<(usize, &str)> {
    let mut offset = 0;
    for line in text.split_inclusive('\n') {
        if line.trim_start().starts_with("#[rule(") {
            let start = offset + line.find("#[rule(")? + "#[rule(".len();
            let mut depth = 1usize;
            let mut in_str = false;
            for (i, ch) in text[start..].char_indices() {
                match ch {
                    '"' => in_str = !in_str,
                    '(' | '[' if !in_str => depth += 1,
                    ')' | ']' if !in_str => {
                        depth -= 1;
                        if depth == 0 {
                            return Some((start + i, &text[start..start + i]));
                        }
                    }
                    _ => {}
                }
            }
            return None;
        }
        offset += line.len();
    }
    None
}

/// The string literal after `key =` in an attribute body.
fn string_arg<'a>(body: &'a str, key: &str) -> Option<&'a str> {
    let at = body.find(&format!("{key} ="))? + key.len() + 2;
    let rest = body[at..].trim_start().strip_prefix('"')?;
    rest.split('"').next()
}

/// The bare word after `key =` in an attribute body.
fn word_arg<'a>(body: &'a str, key: &str) -> Option<&'a str> {
    let at = body.find(&format!("{key} ="))? + key.len() + 2;
    body[at..]
        .trim_start()
        .split(|c: char| !c.is_alphanumeric() && c != '_')
        .next()
}

fn parse_rule_file(path: &Path, stem: &str, text: &str) -> Result<Option<RuleSrc>, IndexError> {
    let shape = |reason: &str| IndexError::Shape {
        path: path.to_path_buf(),
        reason: reason.to_owned(),
    };
    let Some((end, body)) = attribute_body(text) else {
        return Ok(None);
    };
    // The legacy derive also spells `#[rule(..)]`; it always sits under `#[derive(.. Rule)]`.
    if text[..end]
        .lines()
        .any(|l| l.trim_start().starts_with("#[derive(") && l.contains("Rule"))
    {
        return Ok(None);
    }
    let id = string_arg(body, "id").ok_or_else(|| shape("`#[rule]` has no `id = \"..\"`"))?;
    if id.to_ascii_lowercase() != stem {
        return Err(shape(&format!(
            "file stem `{stem}` must be the lowercase rule id `{}`",
            id.to_ascii_lowercase()
        )));
    }
    let scope = match word_arg(body, "scope") {
        Some("File") => SrcScope::File,
        Some("Repo") => SrcScope::Repo,
        _ => return Err(shape("`#[rule]` needs `scope = File` or `scope = Repo`")),
    };
    let after = &text[end..];
    let ty = after
        .split("struct ")
        .nth(1)
        .ok_or_else(|| shape("no `struct` after the `#[rule]` attribute"))?;
    let ty_end = ty
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(ty.len());
    let (name, tail) = ty.split_at(ty_end);
    if !tail.trim_start().starts_with(';') {
        return Err(shape("a rule must be a unit struct (`pub struct Name;`)"));
    }
    Ok(Some(RuleSrc {
        stem: stem.to_owned(),
        id: id.to_owned(),
        ty: name.to_owned(),
        scope,
    }))
}

/// Render the generated `mod.rs` for `rules`; `has_retired` adds the hand-written `retired` module.
pub fn render(rules: &[RuleSrc], has_retired: bool) -> String {
    // Laid out the way rustfmt leaves it (the comment keeps a one-rule list vertical), so
    // `cargo fmt --check` never disagrees with the committed file.
    let mut mods: Vec<(&str, String)> = rules
        .iter()
        .map(|r| {
            (
                r.stem.as_str(),
                format!("/// Rule `{}`.\npub mod {};", r.id, r.stem),
            )
        })
        .collect();
    if has_retired {
        mods.push((
            "retired",
            "/// Renamed and retired ids of this crate.\npub mod retired;".to_owned(),
        ));
    }
    mods.sort_by(|a, b| a.0.cmp(b.0));
    let mut s = String::new();
    let _ = writeln!(s, "{HEADER}");
    let _ = writeln!(
        s,
        "//! The rules of this crate, one module per `src/rules/<id>.rs`.\n"
    );
    for (_, decl) in &mods {
        let _ = writeln!(s, "{decl}");
    }
    let _ = writeln!(
        s,
        "\n/// The declaration of every rule in this crate, sorted by file stem.\npub const METAS: &[&gob_rules::RuleDef] = &[\n    // one entry per rule file"
    );
    for r in rules {
        let _ = writeln!(s, "    <{}::{} as gob_rules::RuleDecl>::DEF,", r.stem, r.ty);
    }
    let (renamed, retired) = if has_retired {
        ("retired::RENAMED", "retired::RETIRED")
    } else {
        ("&[]", "&[]")
    };
    let _ = write!(
        s,
        "];\n\n/// This crate's rule index: the declarations plus renamed and retired ids.\npub const INDEX: gob_rules::RuleIndex = gob_rules::RuleIndex {{\n    krate: env!(\"CARGO_PKG_NAME\"),\n    metas: METAS,\n    renamed: {renamed},\n    retired: {retired},\n}};\n\nconst _: () = gob_rules::assert_unique(\"crate\", &[&[&INDEX]]);\n\n"
    );
    let _ = writeln!(
        s,
        "/// Bind every rule of this crate to the product host `P`; fails to compile unless `P` hosts them all.\n#[allow(clippy::vec_init_then_push, reason = \"generated: one push per rule\")]\npub fn bind<P: ?Sized + 'static>() -> Vec<gob_rules::BoundRule<P>>\nwhere"
    );
    for r in rules {
        let tr = match r.scope {
            SrcScope::File => "FileRule",
            SrcScope::Repo => "RepoRule",
        };
        let _ = writeln!(s, "    {}::{}: gob_rules::{tr}<P>,", r.stem, r.ty);
    }
    let _ = writeln!(s, "{{\n    let mut rules = Vec::new();");
    for r in rules {
        let ctor = match r.scope {
            SrcScope::File => "file",
            SrcScope::Repo => "repo",
        };
        let _ = writeln!(
            s,
            "    rules.push(gob_rules::BoundRule::{ctor}({}::{}));",
            r.stem, r.ty
        );
    }
    let _ = writeln!(s, "    rules\n}}");
    let _ = write!(
        s,
        "\n#[cfg(test)]\nmod freshness {{\n    /// The committed index equals what the rule files imply.\n    #[test]\n    fn rules_index_is_fresh() {{\n        gob_rules::indexgen::assert_fresh(env!(\"CARGO_MANIFEST_DIR\")).expect(\"rules index\");\n    }}\n}}\n"
    );
    s
}

/// The index `crate_dir` should hold, or `None` when it has no attribute rules.
///
/// # Errors
/// [`IndexError`] when rule files cannot be read or are malformed.
pub fn expected(crate_dir: &Path) -> Result<Option<String>, IndexError> {
    let rules = scan(crate_dir)?;
    if rules.is_empty() {
        return Ok(None);
    }
    let has_retired = crate_dir
        .join("src")
        .join("rules")
        .join("retired.rs")
        .is_file();
    Ok(Some(render(&rules, has_retired)))
}

/// Check that `crate_dir/src/rules/mod.rs` is the generated index (the crate freshness test).
///
/// # Errors
/// [`IndexError::Stale`] when it differs or is missing, [`IndexError::HandWritten`] when a
/// hand-written `mod.rs` sits in a crate with attribute rules, other variants on I/O or shape errors.
pub fn assert_fresh(crate_dir: impl AsRef<Path>) -> Result<(), IndexError> {
    let crate_dir = crate_dir.as_ref();
    let path = crate_dir.join("src").join("rules").join("mod.rs");
    let Some(want) = expected(crate_dir)? else {
        return Ok(());
    };
    match std::fs::read_to_string(&path) {
        Ok(have) if have == want => Ok(()),
        Ok(have) if !have.starts_with(HEADER) => Err(IndexError::HandWritten { path }),
        Ok(_) => Err(IndexError::Stale { path }),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            tracing::warn!(path = %path.display(), "rules index missing");
            Err(IndexError::Stale { path })
        }
        Err(source) => Err(IndexError::Io { path, source }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rule_file(id: &str, ty: &str, scope: &str) -> String {
        format!(
            "use gob_rules::rule;\n\n#[rule(\n    id = \"{id}\",\n    slug = \"x-y\",\n    severity = Warn,\n    scope = {scope},\n    applies = universal(needs = [Comments], min_fidelity = F1),\n    since = \"0.1.0\",\n)]\n/// Doc.\npub struct {ty};\n"
        )
    }

    fn crate_with(files: &[(&str, String)]) -> tempfile::TempDir {
        let dir = tempfile::tempdir().expect("tmp");
        let rules = dir.path().join("src/rules");
        std::fs::create_dir_all(&rules).expect("mkdir");
        for (name, text) in files {
            std::fs::write(rules.join(name), text).expect("write");
        }
        dir
    }

    #[test]
    fn scan_finds_attribute_rules_sorted_by_stem() {
        let dir = crate_with(&[
            ("neat002.rs", rule_file("NEAT002", "Neat002", "Repo")),
            ("cov001.rs", rule_file("COV001", "Cov001", "File")),
            ("cov001.md", "page".to_owned()),
        ]);
        let found = scan(dir.path()).expect("scan");
        let stems: Vec<_> = found
            .iter()
            .map(|r| (r.stem.as_str(), r.ty.as_str(), r.scope))
            .collect();
        assert_eq!(
            stems,
            [
                ("cov001", "Cov001", SrcScope::File),
                ("neat002", "Neat002", SrcScope::Repo)
            ]
        );
    }

    #[test]
    fn legacy_derive_files_and_mod_rs_are_skipped() {
        let legacy = "#[derive(Rule)]\n#[rule(id = \"OLD001\", family = \"OLD\", tier = Universal)]\npub struct Old001;\n";
        let dir = crate_with(&[
            ("old001.rs", legacy.to_owned()),
            ("mod.rs", "pub mod old001;\n".to_owned()),
        ]);
        assert!(scan(dir.path()).expect("scan").is_empty());
        assert_eq!(expected(dir.path()).expect("expected"), None);
    }

    #[test]
    fn a_file_stem_that_is_not_the_lowercase_id_is_rejected() {
        let dir = crate_with(&[("wrong.rs", rule_file("COV001", "Cov001", "File"))]);
        let err = scan(dir.path()).expect_err("stem mismatch");
        assert!(
            err.to_string().contains("lowercase rule id `cov001`"),
            "{err}"
        );
    }

    #[test]
    fn a_non_unit_rule_struct_is_rejected() {
        let text = rule_file("COV001", "Cov001", "File").replace("Cov001;", "Cov001 { x: u8 }");
        let dir = crate_with(&[("cov001.rs", text)]);
        let err = scan(dir.path()).expect_err("not a unit struct");
        assert!(err.to_string().contains("unit struct"), "{err}");
    }

    #[test]
    fn render_lists_mods_metas_bind_and_the_freshness_test() {
        let rules = [
            RuleSrc {
                stem: "cov001".into(),
                id: "COV001".into(),
                ty: "Cov001".into(),
                scope: SrcScope::File,
            },
            RuleSrc {
                stem: "cov002".into(),
                id: "COV002".into(),
                ty: "Cov002".into(),
                scope: SrcScope::Repo,
            },
        ];
        let text = render(&rules, false);
        assert!(text.starts_with(HEADER));
        assert!(text.contains("pub mod cov001;"));
        assert!(text.contains("<cov002::Cov002 as gob_rules::RuleDecl>::DEF,"));
        assert!(text.contains("cov001::Cov001: gob_rules::FileRule<P>,"));
        assert!(text.contains("gob_rules::BoundRule::repo(cov002::Cov002),"));
        assert!(text.contains("fn rules_index_is_fresh()"));
        assert!(text.contains("renamed: &[],"));
        assert!(text.is_ascii());
        assert!(render(&rules, true).contains("renamed: retired::RENAMED,"));
    }

    #[test]
    fn freshness_follows_the_committed_file() {
        let dir = crate_with(&[("cov001.rs", rule_file("COV001", "Cov001", "File"))]);
        let mod_rs = dir.path().join("src/rules/mod.rs");
        assert!(
            matches!(assert_fresh(dir.path()), Err(IndexError::Stale { .. })),
            "missing mod.rs is stale"
        );
        std::fs::write(&mod_rs, "pub mod cov001;\n").expect("write");
        assert!(matches!(
            assert_fresh(dir.path()),
            Err(IndexError::HandWritten { .. })
        ));
        let want = expected(dir.path()).expect("expected").expect("some");
        std::fs::write(&mod_rs, format!("{want}// drift\n")).expect("write");
        assert!(matches!(
            assert_fresh(dir.path()),
            Err(IndexError::Stale { .. })
        ));
        std::fs::write(&mod_rs, want).expect("write");
        assert_fresh(dir.path()).expect("fresh");
    }

    #[test]
    fn a_new_unindexed_rule_file_makes_the_index_stale() {
        let dir = crate_with(&[("cov001.rs", rule_file("COV001", "Cov001", "File"))]);
        let mod_rs = dir.path().join("src/rules/mod.rs");
        std::fs::write(
            &mod_rs,
            expected(dir.path()).expect("expected").expect("some"),
        )
        .expect("write");
        assert_fresh(dir.path()).expect("fresh");
        std::fs::write(
            dir.path().join("src/rules/cov002.rs"),
            rule_file("COV002", "Cov002", "File"),
        )
        .expect("write");
        assert!(matches!(
            assert_fresh(dir.path()),
            Err(IndexError::Stale { .. })
        ));
    }
}
