//! Rule metadata types shared by the derive, the registry and findings.

use serde::{Deserialize, Serialize};

use crate::id::{ParseRuleIdError, RuleId};

/// How serious a finding is; ordered `Unresolved < Advisory < Warn < Error`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Severity {
    /// Could not be decided (missing tool, unreadable input).
    Unresolved,
    /// Informational; never fails a gate.
    Advisory,
    /// Reported; fails only in strict modes.
    Warn,
    /// Fails the gate.
    Error,
}

/// Whether a rule applies to every language or to one language family.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Tier {
    /// Language-independent rule.
    Universal,
    /// Rule bound to a language.
    Lang,
}

/// Whether a rule evaluates one file at a time or the whole repo.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Scope {
    /// Evaluated per file.
    File,
    /// Evaluated over the whole repository.
    Repo,
}

/// How a finding of this rule can be repaired.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FixKind {
    /// A human must fix it.
    Manual,
    /// A deterministic edit is attached.
    Deterministic,
    /// A fix verified by a command, then committed.
    VerifyCommit,
    /// An editor fix-it suggestion.
    FixIt,
}

/// Which bound of a three-valued answer a rule may fire on and certify clean on.
///
/// The authoritative table is `universal-model.md` 4.2; the evaluator in
/// `gob-ir` applies it. Declared per rule with `polarity = Pplus | Pminus |
/// P0 | Pn | Pc` in `#[derive(Rule)]`; the default is [`Polarity::Pplus`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Polarity {
    /// P+, presence: fires on `lo`, clean when `hi` is empty.
    Pplus,
    /// P-, absence: fires when `hi` holds no good thing, clean when `lo` does.
    Pminus,
    /// P0, equality: both sides must be `Exact`.
    P0,
    /// Pn, threshold: max-type fires on `lo > N`, min-type on `hi < N`.
    Pn,
    /// Pc, closure: fires on a path inside `lo` edges, clean without one inside `hi`.
    Pc,
}

impl Polarity {
    /// The design spelling (`P+`, `P-`, `P0`, `Pn`, `Pc`) used on rule pages.
    pub const fn symbol(self) -> &'static str {
        match self {
            Self::Pplus => "P+",
            Self::Pminus => "P-",
            Self::P0 => "P0",
            Self::Pn => "Pn",
            Self::Pc => "Pc",
        }
    }
}

/// Static description of a rule, generated by `#[derive(Rule)]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleMeta {
    /// Rule id string, FAMILY + 3 digits.
    pub id: &'static str,
    /// Kebab-case alias.
    pub slug: &'static str,
    /// Family prefix of the id.
    pub family: &'static str,
    /// Product namespace (e.g. `frob`).
    pub product: &'static str,
    /// Default severity of findings.
    pub severity: Severity,
    /// First doc-comment line.
    pub summary: &'static str,
    /// Full doc comment (markdown), lines joined with newlines.
    pub explanation: &'static str,
    /// Universal or language tier.
    pub tier: Tier,
    /// File or repo scope.
    pub scope: Scope,
    /// Fix kind.
    pub fix: FixKind,
    /// Which answer bound the rule fires on (default [`Polarity::Pplus`]).
    pub polarity: Polarity,
    /// True when examining zero subjects is a required Unresolved, never a clean pass.
    pub must_measure: bool,
    /// Rule semantic version, bumped when behavior changes.
    pub version: u32,
    /// Release in which the rule appeared.
    pub since: &'static str,
    /// `module_path!()` of the declaring item, naming the declaring crate.
    pub module: &'static str,
}

impl RuleMeta {
    /// The validated [`RuleId`] of this rule.
    ///
    /// # Errors
    ///
    /// Returns an error if `id` is malformed (the derive prevents this).
    pub fn rule_id(&self) -> Result<RuleId, ParseRuleIdError> {
        self.id.parse()
    }
}

/// An inventory item pointing at a rule's static metadata.
#[derive(Debug)]
pub struct RuleEntry {
    /// The registered metadata.
    pub meta: &'static RuleMeta,
}

impl RuleEntry {
    /// Wrap static metadata for submission to the inventory.
    pub const fn new(meta: &'static RuleMeta) -> Self {
        Self { meta }
    }
}

inventory::collect!(RuleEntry);
