//! The keyword table (grmb-spec 2.6): the single source for the parser and the editor grammar.

// frob:ticket 01M3Z713VGKF4Z0JJ3263XJMC3

/// Reserved words, in every position.
pub const KEYWORDS: &[&str] = &[
    "accept",
    "age",
    "allocates",
    "alias",
    "as",
    "assumed",
    "at",
    "attr",
    "blocked_by",
    "bound",
    "boundary",
    "claim",
    "clearance",
    "condition",
    "consumer",
    "contract",
    "declassify",
    "decides",
    "defer",
    "digest",
    "endorse",
    "evidence",
    "excuses",
    "extend",
    "fanout",
    "flow",
    "growth",
    "hotfix",
    "include",
    "kind",
    "label",
    "latency",
    "level",
    "may",
    "module",
    "namespace",
    "node",
    "noflow",
    "of",
    "on",
    "owns",
    "pack",
    "part",
    "producer",
    "proof",
    "reach",
    "ref",
    "refines",
    "renamed_from",
    "rate",
    "runnable",
    "satisfies",
    "shape",
    "size",
    "supersedes",
    "surface",
    "tests",
    "transport",
    "utilization",
    "verifies",
    "version",
    "versioning",
    "vmodel",
    "when",
];

/// True when `word` is reserved.
pub fn is_keyword(word: &str) -> bool {
    KEYWORDS.contains(&word)
}
