// @generated by `cargo dev gen rules-index`; do not edit by hand.
//! The rules of this crate, one module per `src/rules/<id>.rs`.

/// Rule `GAM001`.
pub mod gam001;

/// The declaration of every rule in this crate, sorted by file stem.
pub const METAS: &[&gob_rules::RuleDef] = &[
    // one entry per rule file
    <gam001::Gam001 as gob_rules::RuleDecl>::DEF,
];

/// This crate's rule index: the declarations plus renamed and retired ids.
pub const INDEX: gob_rules::RuleIndex = gob_rules::RuleIndex {
    krate: env!("CARGO_PKG_NAME"),
    metas: METAS,
    renamed: &[],
    retired: &[],
};

const _: () = gob_rules::assert_unique("crate", &[&[&INDEX]]);

/// Bind every rule of this crate to the product host `P`; fails to compile unless `P` hosts them all.
#[allow(clippy::vec_init_then_push, reason = "generated: one push per rule")]
pub fn bind<P: ?Sized + 'static>() -> Vec<gob_rules::BoundRule<P>>
where
    gam001::Gam001: gob_rules::Measured<P>,
{
    let mut rules = Vec::new();
    rules.push(gob_rules::BoundRule::measured(gam001::Gam001));
    rules
}

#[cfg(test)]
mod freshness {
    /// The committed index equals what the rule files imply.
    #[test]
    fn rules_index_is_fresh() {
        gob_rules::indexgen::assert_fresh(env!("CARGO_MANIFEST_DIR")).expect("rules index");
    }
}
