"""Generated-file marker detection (T-0234).

Sibling-repo pilot P1 surfaced a real gap: `frontend/src/api/api.generated.ts`
(and this repo's own `frob exports`/`frob deploy generate` outputs) draw
COV001 ("public symbol has no explicit frob:doc edge") demands even though
nobody hand-documents machine-generated code. The `[graph] exclude` leaf
(`frob.excludes`) is the wrong tool for this: excluding a path removes it
from the graph entirely, so xref/dup/arch lose visibility into it too.
Generated files should stay IN the graph -- symbols resolvable, xref intact
-- while being exempt from the *hand-authored documentation* obligation.

This module owns the one place that decides "is this file generated" so
COV001 (and any future gate that needs the same distinction) asks it
instead of re-deriving a marker regex per call site.
"""

from __future__ import annotations

import itertools
import re
from pathlib import Path

from frob.logging import get_logger

_log = get_logger(__name__)

#: Lines scanned per file when probing for a generated-file marker. Every
#: marker convention observed -- Go's `Code generated ... DO NOT EDIT.`,
#: this repo's own `frob exports` (`exports/__init__.py::as_text`) and
#: `frob deploy generate` (`deploy/_generate.py::_GENERATED_BANNER`)
#: headers, and the widely used `@generated` tag -- lands in the first few
#: lines of the file, so a small bound keeps this cheap even against huge
#: generated blobs.
_MARKER_SCAN_LINES = 20

#: Case-insensitive marker recognized as "this file is generated, do not
#: hand-document it." Matches this repo's own conventions (`# generated
#: by: ...`, `# GENERATED by ... DO NOT EDIT BY HAND.`) plus the common
#: external convention (`@generated`, Go/protobuf-style `Code generated by
#: ... DO NOT EDIT.`).
# frob:doc docs/modules/graph.md#generated-file-marker
GENERATED_MARKER_RE = re.compile(
    r"@generated\b|do[ -]not[ -]edit|generated by", re.IGNORECASE
)


# frob:doc docs/modules/graph.md#generated-file-marker
# frob:tests tests/test_graph.py::TestGeneratedSource.test_is_generated_source_detects_repo_convention_header  # noqa: E501
# frob:tests tests/test_graph.py::TestGeneratedSource.test_is_generated_source_detects_do_not_edit_and_at_markers  # noqa: E501
# frob:tests tests/test_graph.py::TestGeneratedSource.test_is_generated_source_false_for_hand_authored_file  # noqa: E501
# frob:tests tests/test_graph.py::TestGeneratedSource.test_is_generated_source_false_for_missing_file  # noqa: E501
def is_generated_source(root: Path, path: str) -> bool:
    """True if the file at repo-relative `path` carries a recognized
    generated-file marker (`GENERATED_MARKER_RE`) within its first lines.

    A read failure (missing/unreadable file -- can happen against stale
    graph state) is treated as "not generated" rather than raised; callers
    such as COV001 already tolerate the more conservative "still owes
    documentation" outcome in that case.
    """
    full = root / path
    try:
        with full.open("r", encoding="utf-8", errors="replace") as handle:
            head = "".join(itertools.islice(handle, _MARKER_SCAN_LINES))
    except OSError:
        _log.debug("is_generated_source: could not read %s", full)
        return False
    found = GENERATED_MARKER_RE.search(head) is not None
    if found:
        _log.debug("is_generated_source: %s carries a generated-file marker", path)
    return found


__all__ = ["GENERATED_MARKER_RE", "is_generated_source"]
