"""End-to-end tests for `frob exports`."""

import json
from pathlib import Path

from tests.system.conftest import run


def _make_pkg(tmp_path: Path, files: dict[str, str]) -> Path:
    pkg = tmp_path / "mypkg"
    pkg.mkdir(exist_ok=True)
    (pkg / "__init__.py").write_text("")
    for name, src in files.items():
        (pkg / name).write_text(src)
    return pkg


class TestExportsBasic:
    def test_shows_import_line(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\ndef bar(): ...\n"})
        r = run("exports", str(pkg))
        assert r.returncode == 0
        out = r.stdout + r.stderr
        assert "from mypkg.mod import" in out

    def test_shows_all_directive(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\n"})
        r = run("exports", str(pkg))
        assert r.returncode == 0
        assert "__all__" in (r.stdout + r.stderr)

    def test_public_symbols_present(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def alpha(): ...\ndef beta(): ...\n"})
        r = run("exports", str(pkg))
        out = r.stdout + r.stderr
        assert "alpha" in out
        assert "beta" in out

    def test_private_excluded_by_default(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def public(): ...\ndef _private(): ...\n"})
        r = run("exports", str(pkg))
        out = r.stdout + r.stderr
        assert "public" in out
        assert "_private" not in out

    def test_classes_included(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"models.py": "class Foo:\n    pass\nclass Bar:\n    pass\n"})
        r = run("exports", str(pkg))
        out = r.stdout + r.stderr
        assert "Foo" in out
        assert "Bar" in out

    def test_header_comment_present(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def x(): ...\n"})
        r = run("exports", str(pkg))
        assert "generated by" in (r.stdout + r.stderr).lower() or "frob exports" in (r.stdout + r.stderr)


class TestExportsFlags:
    def test_all_flag_includes_private(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def public(): ...\ndef _private(): ...\n"})
        r = run("exports", str(pkg), "--all")
        assert r.returncode == 0
        assert "_private" in (r.stdout + r.stderr)

    def test_exclude_skips_module(self, tmp_path):
        pkg = _make_pkg(tmp_path, {
            "alpha.py": "def foo(): ...\n",
            "beta.py": "def bar(): ...\n",
        })
        r = run("exports", str(pkg), "--exclude", "beta")
        assert r.returncode == 0
        out = r.stdout + r.stderr
        assert "foo" in out
        assert "beta" not in out

    def test_json_output(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\n"})
        r = run("exports", str(pkg), "--json")
        assert r.returncode == 0
        out = r.stdout + r.stderr
        for line in out.splitlines():
            line = line.strip()
            if line.startswith("{"):
                data = json.loads(line)
                assert "modules" in data
                return
        raise AssertionError(f"no JSON in output: {out!r}")

    def test_json_modules_have_symbols(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def alpha(): ...\n"})
        r = run("exports", str(pkg), "--json")
        out = r.stdout + r.stderr
        for line in out.splitlines():
            line = line.strip()
            if line.startswith("{"):
                data = json.loads(line)
                all_symbols = [s for m in data["modules"] for s in m["symbols"]]
                assert "alpha" in all_symbols
                return
        raise AssertionError("no JSON in output")


class TestExportsWrite:
    def test_write_creates_init_py(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\n"})
        r = run("exports", str(pkg), "--write")
        assert r.returncode == 0
        init = pkg / "__init__.py"
        assert init.exists()
        content = init.read_text()
        assert "foo" in content
        assert "__all__" in content

    def test_write_contains_import_line(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def alpha(): ...\ndef beta(): ...\n"})
        run("exports", str(pkg), "--write")
        content = (pkg / "__init__.py").read_text()
        assert "from mypkg.mod import" in content
        assert "alpha" in content
        assert "beta" in content

    def test_write_header_comment(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def x(): ...\n"})
        run("exports", str(pkg), "--write")
        content = (pkg / "__init__.py").read_text()
        assert "generated by" in content.lower() or "frob exports" in content

    def test_write_overwrites_on_rerun(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\n"})
        run("exports", str(pkg), "--write")

        # Add a new symbol and rerun
        (pkg / "mod.py").write_text("def foo(): ...\ndef bar(): ...\n")
        run("exports", str(pkg), "--write")

        content = (pkg / "__init__.py").read_text()
        assert "bar" in content

    def test_write_no_stdout(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\n"})
        r = run("exports", str(pkg), "--write")
        # --write should not dump imports to stdout (just a log line is ok)
        out = r.stdout
        assert "from mypkg" not in out
        assert "__all__" not in out

    def test_write_and_print_exclusive(self, tmp_path):
        pkg = _make_pkg(tmp_path, {"mod.py": "def foo(): ...\n"})
        # --write: init file updated
        run("exports", str(pkg), "--write")
        # --json (no --write): stdout shows JSON, file stays written
        r = run("exports", str(pkg), "--json")
        assert r.returncode == 0


class TestExportsErrors:
    def test_non_directory_fails(self, tmp_path):
        f = tmp_path / "solo.py"
        f.write_text("def x(): ...\n")
        r = run("exports", str(f))
        assert r.returncode != 0

    def test_empty_package_fails(self, tmp_path):
        pkg = tmp_path / "emptypkg"
        pkg.mkdir()
        (pkg / "__init__.py").write_text("")
        r = run("exports", str(pkg))
        assert r.returncode != 0
