from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel
from typani import Err, ErrorSet, Ok
from typani.result import Result

from frob.outline import outline_file


# frob:doc docs/commands/exports.md#public-api
class ExportsError(ErrorSet):
    NotADirectory = "Path is not a directory"
    NoSourceFiles = "No Python source files found in directory"


# frob:doc docs/commands/exports.md#public-api
class ModuleExports(BaseModel):
    module: str
    symbols: list[str]


# frob:doc docs/commands/exports.md#public-api
class ExportsResult(BaseModel):
    package_dir: str
    modules: list[ModuleExports]

    # frob:waive TEST005 reason="ExportsResult.as_text 80.0% branch cover, debt T-0160"
    # frob:ticket T-0588
    # frob:tests tests/unit/test_exports.py::TestExportsPackage.test_as_text_output
    def as_text(self) -> str:
        # frob:doc docs/commands/exports.md#public-api
        # Find which symbol names are duplicated across modules
        counts: dict[str, int] = {}
        for mod in self.modules:
            for s in mod.symbols:
                counts[s] = counts.get(s, 0) + 1
        duplicates = {name for name, n in counts.items() if n > 1}

        all_exported: list[str] = []
        lines = [f"# generated by: frob exports {self.package_dir}"]
        for mod in self.modules:
            if not mod.symbols:
                continue
            parts: list[str] = []
            for s in mod.symbols:
                if s in duplicates:
                    # e.g. exports_runner.run -> "exports_runner_run" alias
                    mod_short = mod.module.split(".")[-1]
                    alias = f"{mod_short}_{s}"
                    parts.append(f"{s} as {alias}")
                    all_exported.append(alias)
                else:
                    parts.append(s)
                    all_exported.append(s)
            lines.append(f"from {mod.module} import {', '.join(parts)}")
        lines.append("")
        if all_exported:
            quoted = ", ".join(f'"{n}"' for n in sorted(all_exported))
            lines.append(f"__all__ = [{quoted}]")
        return "\n".join(lines)

    # frob:waive TEST005 reason="ExportsResult.as_json 50.0% branch cover, debt T-0160"
    # frob:ticket T-0588
    # frob:tests tests/unit/test_app_runners.py::TestExportsRunner.test_json_mode_logs_result  # noqa: E501
    def as_json(self) -> str:
        # frob:doc docs/commands/exports.md#public-api
        return self.model_dump_json(indent=2)


def _module_exports(
    py_file: Path, *, pkg_name: str, include_private: bool
) -> ModuleExports | None:
    """The public (or all, if `include_private`) symbols outlined from one
    module file, or `None` if unparseable/empty."""
    result = outline_file(py_file)
    if result.is_err:
        return None
    ol = result.danger_ok

    symbols: list[str] = []
    for fn in ol.functions:
        if not include_private and fn.name.startswith("_"):
            continue
        symbols.append(fn.name)
    for cls in ol.classes:
        if not include_private and cls.name.startswith("_"):
            continue
        symbols.append(cls.name)

    if not symbols:
        return None
    return ModuleExports(module=f"{pkg_name}.{py_file.stem}", symbols=symbols)


# frob:doc docs/commands/exports.md#public-api
def exports_package(
    pkg_dir: Path,
    *,
    include_private: bool = False,
    exclude_modules: list[str] | None = None,
) -> Result[ExportsResult, ExportsError]:
    if not pkg_dir.is_dir():
        return Err(ExportsError.NotADirectory)

    exclude = set(exclude_modules or [])
    pkg_name = pkg_dir.name

    py_files = sorted(f for f in pkg_dir.glob("*.py") if f.name != "__init__.py")
    if not py_files:
        return Err(ExportsError.NoSourceFiles)

    modules: list[ModuleExports] = []
    for py_file in py_files:
        if py_file.stem in exclude:
            continue
        mod = _module_exports(
            py_file, pkg_name=pkg_name, include_private=include_private
        )
        if mod is not None:
            modules.append(mod)

    return Ok(ExportsResult(package_dir=str(pkg_dir), modules=modules))
