from __future__ import annotations

import re
from pathlib import Path

from pydantic import BaseModel
from typani import Err, ErrorSet, Ok
from typani.result import Result

from frob.outline import outline_file
from frob.xref import xref


# frob:doc docs/commands/exports.md#public-api
class ExportsError(ErrorSet):
    NotADirectory = "Path is not a directory"
    NoSourceFiles = "No Python source files found in directory"


# frob:doc docs/commands/exports.md#public-api
class ModuleExports(BaseModel):
    module: str
    symbols: list[str]


# frob:doc docs/commands/exports.md#public-api
class ExportsResult(BaseModel):
    package_dir: str
    modules: list[ModuleExports]

    # frob:ticket T-0588
    # frob:tests tests/unit/test_exports.py::TestExportsPackage.test_as_text_output
    def as_text(self) -> str:
        # frob:doc docs/commands/exports.md#public-api
        # Find which symbol names are duplicated across modules
        counts: dict[str, int] = {}
        for mod in self.modules:
            for s in mod.symbols:
                counts[s] = counts.get(s, 0) + 1
        duplicates = {name for name, n in counts.items() if n > 1}

        all_exported: list[str] = []
        lines = [f"# generated by: frob exports {self.package_dir}"]
        for mod in self.modules:
            if not mod.symbols:
                continue
            parts: list[str] = []
            for s in mod.symbols:
                if s in duplicates:
                    # e.g. exports_runner.run -> "exports_runner_run" alias
                    mod_short = mod.module.split(".")[-1]
                    alias = f"{mod_short}_{s}"
                    parts.append(f"{s} as {alias}")
                    all_exported.append(alias)
                else:
                    parts.append(s)
                    all_exported.append(s)
            lines.append(f"from {mod.module} import {', '.join(parts)}")
        lines.append("")
        if all_exported:
            quoted = ", ".join(f'"{n}"' for n in sorted(all_exported))
            lines.append(f"__all__ = [{quoted}]")
        return "\n".join(lines)

    # frob:ticket T-0588
    # frob:tests tests/unit/test_app_runners.py::TestExportsRunner.test_json_mode_logs_result  # noqa: E501
    def as_json(self) -> str:
        # frob:doc docs/commands/exports.md#public-api
        return self.model_dump_json(indent=2)


def _module_exports(
    py_file: Path, *, pkg_name: str, include_private: bool
) -> ModuleExports | None:
    """The public (or all, if `include_private`) symbols outlined from one
    module file, or `None` if unparseable/empty."""
    result = outline_file(py_file)
    if result.is_err:
        return None
    ol = result.danger_ok

    symbols: list[str] = []
    for fn in ol.functions:
        if not include_private and fn.name.startswith("_"):
            continue
        symbols.append(fn.name)
    for cls in ol.classes:
        if not include_private and cls.name.startswith("_"):
            continue
        symbols.append(cls.name)

    if not symbols:
        return None
    return ModuleExports(module=f"{pkg_name}.{py_file.stem}", symbols=symbols)


# frob:doc docs/commands/exports.md#public-api
def exports_package(
    pkg_dir: Path,
    *,
    include_private: bool = False,
    exclude_modules: list[str] | None = None,
) -> Result[ExportsResult, ExportsError]:
    if not pkg_dir.is_dir():
        return Err(ExportsError.NotADirectory)

    exclude = set(exclude_modules or [])
    pkg_name = pkg_dir.name

    py_files = sorted(f for f in pkg_dir.glob("*.py") if f.name != "__init__.py")
    if not py_files:
        return Err(ExportsError.NoSourceFiles)

    modules: list[ModuleExports] = []
    for py_file in py_files:
        if py_file.stem in exclude:
            continue
        mod = _module_exports(
            py_file, pkg_name=pkg_name, include_private=include_private
        )
        if mod is not None:
            modules.append(mod)

    return Ok(ExportsResult(package_dir=str(pkg_dir), modules=modules))


# Matches a Python `import x` / `from x import y` statement line (allowing
# leading whitespace for indented/conditional imports) -- used to separate
# real import-consumers from mere prose/comment mentions of a symbol name
# (T-0858: the recurring "who imports this symbol" question that grep
# demonstrably answers wrong in both directions -- missed matches and false
# positives on comments).
_IMPORT_LINE_RE = re.compile(r"^\s*(from\s+\S+\s+import\b|import\s+\S+)")


# frob:doc docs/modules/cli.md#exports-consumers-surface-t-0858
class ConsumerRef(BaseModel):
    file: str
    line: int
    context: str


# frob:doc docs/modules/cli.md#exports-consumers-surface-t-0858
# frob:ticket T-0876
class ConsumersResult(BaseModel):
    symbol: str
    consumers: list[ConsumerRef]

    # frob:doc docs/modules/cli.md#exports-consumers-surface-t-0858
    # frob:ticket T-0858
    # frob:tests tests/unit/test_exports.py::TestExportsConsumers.test_as_text_output
    def as_text(self) -> str:
        parts = [self.symbol]
        if self.consumers:
            parts.append("  imported by:")
            for c in self.consumers:
                parts.append(f"    {c.file}:{c.line:<6} {c.context}")
        else:
            parts.append("  imported by: (none found)")
        return "\n".join(parts)

    # frob:doc docs/modules/cli.md#exports-consumers-surface-t-0858
    # frob:ticket T-0858
    # frob:tests tests/unit/test_exports.py::TestExportsConsumers.test_as_json_output
    def as_json(self) -> str:
        return self.model_dump_json(indent=2)


# frob:doc docs/modules/cli.md#exports-consumers-surface-t-0858
# frob:ticket T-0858
# frob:tests tests/unit/test_exports.py::TestExportsConsumers.test_finds_import_consumer
# frob:tests tests/unit/test_exports.py::TestExportsConsumers.test_excludes_prose_mention  # noqa: E501
def exports_consumers(
    symbol: str, root: Path, *, lang: str | None = None
) -> Result[ConsumersResult, ExportsError]:
    """Which files actually `import`/`from ... import` `symbol` under `root`,
    filtered down from `frob.xref`'s raw identifier usages to real import
    statements only.

    Folds the one xref query that stayed in recurring, gate-driven use
    (T-0858's reevaluation of the T-0580/T-0802 navigation-command sunset)
    into the surviving `exports` surface, so the sunset of the standalone
    `frob xref` porcelain does not delete the underlying capability. Plain
    `xref`/grep usage cannot cleanly separate "this file imports the symbol"
    from "this file merely mentions the symbol name in a comment or string"
    -- this narrows to lines that parse as an import statement.
    """
    result = xref(symbol, root, lang=lang)
    if result.is_err:
        return Err(ExportsError.NoSourceFiles)

    xr = result.danger_ok
    consumers = [
        ConsumerRef(file=u.file, line=u.line, context=u.context.strip())
        for u in xr.usages
        if _IMPORT_LINE_RE.match(u.context)
    ]
    return Ok(ConsumersResult(symbol=symbol, consumers=consumers))
