//! crunk's rule crate (D107, `rule-authoring.md`; design `crunk.md` section 6): the families crunk
//! owns, the registry over every `#[rule]` declaration, the `[lint]` severity resolution and the
//! `crunk:waive` waivers with their one rule, WAIVE001.
//!
//! # Overview
//!
//! - [`rules`]: one `src/rules/<id>.rs` plus `<id>.md` per rule, the index generated by
//!   `cargo dev gen rules-index`. WAIVE001, COLOR001-002 and CONTRAST001 live here; later crunk
//!   rules join the same directory (or another crate listed in `crunk-check`'s `product_rules!`).
//! - [`color`], [`contrast`], [`mode`], [`sheets`]: the plain modules the colour and contrast rules
//!   share (palette conformance, the definition set, role measurement, the mode loop, site paths).
//! - [`family`]: [`family::FamilyMeta`], the metadata a family shares (tiers, waivability and the
//!   release severity room), and [`family::Gate`] with [`family::gate_severity`].
//! - [`registry`]: [`registry::entries`] lists id, family, default severity, fixable flag and doc
//!   of every declared rule; [`registry::render_markdown`] is the generated page under
//!   `docs/crunk/rules/`.
//! - [`lint`]: `[lint]` of `crunk.toml` applied to a declared rule or to a finding.
//! - [`waiver`]: the `crunk:waive` comment: scan, bind to the covered region, turn into exceptions.
//! - [`host`]: [`host::CrunkHost`], the host trait crunk's rules evaluate against.

// frob:ticket 01M43ATASM383KB9130JY79XVV

pub mod color;
pub mod contrast;
pub mod family;
pub mod host;
pub mod lint;
pub mod mode;
pub mod registry;
pub mod rules;
pub mod sheets;
pub mod waiver;

pub use host::CrunkHost;
