//! The registry: every `#[rule]` declaration of crunk's rule crates, listed and checked.
//!
//! There is no hand-written id table: the generated `rules::INDEX` of each rule crate is the
//! source, uniqueness is a `const` check (`gob_rules::assert_unique`), and the catalog the spec
//! crate keeps for `[lint]` is checked against the declarations by [`catalog_mismatches`]. The
//! page under `docs/crunk/rules/` is [`render_markdown`] of [`entries`], kept fresh by a test.

// frob:ticket 01M43ATASM383KB9130JY79XVV

use crunk_spec::catalog::default_severity;
use std::fmt::Write as _;

use gob_rules::{FixKind, RuleIndex, Severity};

use crate::family::{CheckTier, family};

/// One listed rule: the columns of the registry page.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    /// Rule id, for example `WAIVE001`.
    pub id: &'static str,
    /// Kebab-case slug.
    pub slug: &'static str,
    /// Family prefix.
    pub family: &'static str,
    /// Declared default severity.
    pub severity: Severity,
    /// Severity at the release gate (equal to `severity` unless the family raises it).
    pub release_severity: Severity,
    /// True when a fix kind other than manual is declared.
    pub fixable: bool,
    /// Tiers of the family, `T0` when the family is unknown.
    pub tiers: Vec<CheckTier>,
    /// The first sentence of the rule page's "What it does" section.
    pub summary: String,
}

/// Every rule of `indexes`, sorted by id.
pub fn entries(indexes: &[&RuleIndex]) -> Vec<Entry> {
    let mut out: Vec<Entry> = indexes
        .iter()
        .flat_map(|ix| ix.metas.iter())
        .map(|def| Entry {
            id: def.id,
            slug: def.slug,
            family: def.family,
            severity: def.severity,
            release_severity: crate::family::gate_severity(def, crate::family::Gate::Release),
            fixable: def.fix != FixKind::Manual,
            tiers: family(def.family).map_or_else(|| vec![CheckTier::T0], |f| f.tiers.to_vec()),
            summary: what_it_does(def.doc),
        })
        .collect();
    out.sort_by(|a, b| a.id.cmp(b.id));
    tracing::debug!(rules = out.len(), "crunk registry listed");
    out
}

/// The first sentence under `## What it does` in a rule page, whitespace collapsed.
fn what_it_does(doc: &str) -> String {
    let body = doc
        .split("## What it does")
        .nth(1)
        .and_then(|rest| rest.split("\n## ").next())
        .unwrap_or_default();
    let flat = body.split_whitespace().collect::<Vec<_>>().join(" ");
    match flat.find(". ") {
        Some(i) => flat[..=i].to_owned(),
        None => flat,
    }
}

/// Ids declared in `indexes` whose family has no [`family`] row (a new family needs one).
pub fn unknown_families(indexes: &[&RuleIndex]) -> Vec<&'static str> {
    indexes
        .iter()
        .flat_map(|ix| ix.metas.iter())
        .filter(|d| family(d.family).is_none())
        .map(|d| d.id)
        .collect()
}

/// Declared rules whose default severity disagrees with the spec catalog `[lint]` is checked
/// against, as `(id, declared, catalog)`. A rule absent from the catalog is not a mismatch (the
/// catalog is the Python port's list; new rules need no row).
pub fn catalog_mismatches(indexes: &[&RuleIndex]) -> Vec<(&'static str, Severity, Severity)> {
    indexes
        .iter()
        .flat_map(|ix| ix.metas.iter())
        .filter_map(|d| {
            let cat = match default_severity(d.id)? {
                crunk_spec::Severity::Error => Severity::Error,
                crunk_spec::Severity::Warn => Severity::Warn,
                crunk_spec::Severity::Off => return None,
            };
            (cat != d.severity).then_some((d.id, d.severity, cat))
        })
        .collect()
}

fn severity_name(s: Severity) -> &'static str {
    match s {
        Severity::Unresolved => "unresolved",
        Severity::Advisory => "advisory",
        Severity::Warn => "warn",
        Severity::Error => "error",
    }
}

/// The registry page (`docs/crunk/rules/README.md`) for `indexes`: one table of rules, then the
/// family table. Generated; a test compares the committed file with this text.
pub fn render_markdown(indexes: &[&RuleIndex]) -> String {
    let mut out = String::from(
        "<!-- @generated by `UPDATE_CRUNK_RULES_DOC=1 cargo nextest run -p crunk-check registry`; do not edit by hand. -->\n\n# crunk rules\n\n",
    );
    out.push_str("Every rule is two files in its crate, `src/rules/<id>.rs` and `<id>.md`; this page lists the declarations.\n\n");
    out.push_str("| Id | Slug | Family | Severity | Release | Fixable | Tiers | What it does |\n|---|---|---|---|---|---|---|---|\n");
    for e in entries(indexes) {
        let tiers: Vec<&str> = e.tiers.iter().map(|t| t.as_str()).collect();
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} | {} | {} |",
            e.id,
            e.slug,
            e.family,
            severity_name(e.severity),
            severity_name(e.release_severity),
            if e.fixable { "yes" } else { "no" },
            tiers.join(", "),
            e.summary.replace('|', "\\|"),
        );
    }
    out.push_str("\n## Families\n\n| Family | Tiers | Waivable | Release severity | Checks |\n|---|---|---|---|---|\n");
    for f in crate::family::FAMILIES {
        let tiers: Vec<&str> = f.tiers.iter().map(|t| t.as_str()).collect();
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} |",
            f.prefix,
            tiers.join(", "),
            if f.waivable { "yes" } else { "no" },
            f.release_severity.map_or("same", severity_name),
            f.summary,
        );
    }
    out
}
