//! The `tokens.css` exporter: a `:root` block of custom properties under the GENERATED banner.

// frob:ticket 01M43ARZH9F9MCPJCKXM635E0X

use std::path::PathBuf;

use crunk_spec::DesignSpec;

use super::{Comparison, Exporter, Target};
use crate::model::TokenSet;

/// The banner line every `tokens.css` carries.
pub const BANNER: &str = "/* GENERATED by crunk tokens -- edit crunk.toml instead. */";

/// Renders `tokens.css`.
#[derive(Debug, Clone, Copy, Default)]
pub struct CssExporter;

impl Exporter for CssExporter {
    fn target(&self) -> Target {
        Target::Css
    }

    /// `[tokens] header` verbatim (when set), the banner, then `:root { --name: value; }`.
    fn render(&self, spec: &DesignSpec, tokens: &TokenSet) -> String {
        let mut lines: Vec<String> = Vec::new();
        if !spec.tokens.header.is_empty() {
            lines.push(spec.tokens.header.clone());
        }
        lines.push(BANNER.to_owned());
        lines.push(":root {".to_owned());
        for (name, value) in tokens.css_entries() {
            lines.push(format!("  {name}: {value};"));
        }
        lines.push("}".to_owned());
        let mut text = lines.join("\n");
        text.push('\n');
        text
    }

    fn path(&self, spec: &DesignSpec) -> Option<PathBuf> {
        Some(spec.tokens_path())
    }

    fn comparison(&self) -> Comparison {
        Comparison::Bytes
    }
}
