//! Token exporters: one [`Exporter`] interface, one implementation per [`Target`].
//!
//! `crunk.toml` compiles to a [`TokenSet`]; each exporter turns that set into the text of one
//! generated file (`tokens.css`, the flat JSON export, the Tailwind theme mapping). Later targets
//! (DTCG, USS, a C# token class; docs/design/crunk.md section 2) are further implementations of
//! the same trait and one more [`Target`] variant, with no change to the write and drift code.
//!
//! The drift side is split so `TOKENS001` can compute its input without touching this crate's
//! I/O: [`render_managed`] is pure (the expected text of every configured file),
//! [`compare`] is pure (expected text against whatever text is on disk, or `None` when the file
//! is missing), and [`check`] / [`write_all`] are the disk-backed wrappers.
//!
//! ```
//! use std::path::Path;
//! use crunk_tokens::export::{Target, render_target};
//!
//! let spec = crunk_spec::parse_spec(
//!     crunk_spec::presets::DEFAULT,
//!     Path::new("crunk.toml"),
//!     Path::new("/proj"),
//! )
//! .unwrap();
//! let css = render_target(&spec, Target::Css).unwrap();
//! assert!(css.starts_with("/* GENERATED by crunk tokens"));
//! ```

// frob:ticket 01M43ARZH9F9MCPJCKXM635E0X

mod css;
mod drift;
mod flat;
mod json;
mod tailwind;
mod write;

use std::fmt;
use std::path::PathBuf;

use crunk_spec::DesignSpec;

use crate::model::{TokenError, TokenSet};

pub use css::{BANNER, CssExporter};
pub use drift::{DriftReport, FileDrift, Rendered, Status, check, compare, render_managed};
pub use flat::FlatJsonExporter;
pub use json::Json;
pub use tailwind::TailwindExporter;
pub use write::{ExportError, WriteReport, WrittenFile, write_all};

/// An export target: which generated artifact an [`Exporter`] produces.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[non_exhaustive]
pub enum Target {
    /// `tokens.css`: the `:root` custom-property block.
    Css,
    /// The flat `{name: value}` JSON export (`[tokens] json_file`).
    Json,
    /// The Tailwind `theme.extend` mapping (`[tailwind] tokens_file`).
    Tailwind,
}

impl Target {
    /// Every target, in the order the managed files are written and reported.
    pub const ALL: [Target; 3] = [Target::Css, Target::Tailwind, Target::Json];

    /// The `--target` / `--format` spelling (`css`, `json`, `tailwind`).
    pub fn name(self) -> &'static str {
        match self {
            Self::Css => "css",
            Self::Json => "json",
            Self::Tailwind => "tailwind",
        }
    }

    /// Parse the spelling [`Target::name`] prints.
    pub fn parse(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|t| t.name() == name)
    }

    /// The exporter that renders this target.
    pub fn exporter(self) -> &'static dyn Exporter {
        match self {
            Self::Css => &CssExporter,
            Self::Json => &FlatJsonExporter,
            Self::Tailwind => &TailwindExporter,
        }
    }
}

impl serde::Serialize for Target {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.name())
    }
}

impl fmt::Display for Target {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// How drift between the expected text and the file on disk is decided.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Comparison {
    /// Byte for byte.
    Bytes,
    /// After parsing both sides as JSON, so a formatter's re-indent never drifts.
    Json,
}

/// One generated-file format.
pub trait Exporter: Sync {
    /// The target this exporter renders.
    fn target(&self) -> Target;

    /// The deterministic text of the generated file for `tokens` (derived from `spec`).
    fn render(&self, spec: &DesignSpec, tokens: &TokenSet) -> String;

    /// The absolute path `spec` configures for this target's file, or `None` when unset.
    fn path(&self, spec: &DesignSpec) -> Option<PathBuf>;

    /// How a file on disk is compared with [`Exporter::render`].
    fn comparison(&self) -> Comparison;
}

/// Render one target for `spec`.
///
/// # Errors
///
/// [`TokenError`] when the spec produces a colliding token name.
pub fn render_target(spec: &DesignSpec, target: Target) -> Result<String, TokenError> {
    let tokens = TokenSet::from_spec(spec)?;
    Ok(target.exporter().render(spec, &tokens))
}
