//! Rendering a version section and verifying the sections already in CHANGELOG.md.

use std::fmt::Write as _;

use crate::config::ProductTags;
use crate::error::ReleaseError;
use crate::fragment::{Fragment, Kind, PRODUCTS};

/// Prefix of the integrity line that closes every compiled section.
const MARKER: &str = "<!-- frob-section: ";

/// Prefix of the first line of a header that `release changelog` wrote itself.
const GENERATED: &str = "<!-- GENERATED by frob:";

/// The header of a fresh CHANGELOG.md: generated-file marker, visible line, and a link to the v1 history when `has_v1_history`.
pub fn initial_header(has_v1_history: bool) -> String {
    let mut out = format!(
        "{GENERATED} DO NOT EDIT between releases. Regenerate: frob release changelog --version <X> -->\n\
         # Changelog\n\n\
         Generated by `frob release changelog` from `changelog.d/` fragments; compiled at release, never hand-edited.\n"
    );
    if has_v1_history {
        out.push_str(
            "The history of frob v1 (before 0.532.0) is in [CHANGELOG-v1.md](CHANGELOG-v1.md).\n",
        );
    }
    out.push('\n');
    out
}

/// True when `text` is a file this tool generated from its header (every section is then marked); false for a hand-written file to adopt.
pub fn is_generated(text: &str) -> bool {
    text.starts_with(GENERATED)
}

/// The version a `## ` heading line names (`## 1.2.0`, `## [1.2.0] - date`, `## v1.2.0`), or `None` for any other heading such as `## Unreleased`.
pub fn heading_version(line: &str) -> Option<&str> {
    let rest = line.strip_prefix("## ")?.trim_start_matches('[');
    let word = rest.split([' ', ']']).next()?;
    let word = word.strip_prefix('v').unwrap_or(word);
    word.starts_with(|c: char| c.is_ascii_digit())
        .then_some(word)
}

/// Split a hand-written CHANGELOG.md at its first version heading: everything above it, and the rest (from that heading on).
///
/// With no version heading the whole text is "above" and the rest is empty.
pub fn split_adopted(text: &str) -> (&str, &str) {
    let mut pos = 0;
    for line in text.split_inclusive('\n') {
        if heading_version(line.trim_end()).is_some() {
            return (&text[..pos], &text[pos..]);
        }
        pos += line.len();
    }
    (text, "")
}

/// Render the section for `version`: the lead notice first, then with several products grouped under product headings (configured products first), then by type, entries by ULID, closed by its hash.
///
/// With one product there is no product heading and every fragment is listed.
pub fn render_section(
    version: &str,
    date: &str,
    fragments: &[Fragment],
    products: &ProductTags,
) -> String {
    let mut out = format!("## {version} - {date}\n\n");
    // The lead notice (at most one, enforced when fragments are read) sits above every group.
    for n in fragments.iter().filter(|f| f.kind == Kind::Notice) {
        let _ = write!(out, "{} ({}, {})\n\n", n.text, n.handle, n.ulid);
    }
    let fragments: Vec<Fragment> = fragments
        .iter()
        .filter(|f| f.kind != Kind::Notice)
        .cloned()
        .collect();
    let groups: Vec<(Option<&str>, Vec<&Fragment>)> = if products.is_multi() {
        let mut order: Vec<&str> = products.products().iter().map(String::as_str).collect();
        let extra: Vec<&str> = PRODUCTS
            .iter()
            .copied()
            .filter(|p| !order.contains(p))
            .collect();
        order.extend(extra);
        order
            .into_iter()
            .map(|p| {
                (
                    Some(p),
                    fragments.iter().filter(|f| f.product == p).collect(),
                )
            })
            .collect()
    } else {
        vec![(None, fragments.iter().collect())]
    };
    for (product, mine) in groups {
        if mine.is_empty() {
            continue;
        }
        if let Some(product) = product {
            let _ = write!(out, "### {}\n\n", products.label(product));
        }
        for kind in Kind::ALL {
            let mut group: Vec<&&Fragment> = mine.iter().filter(|f| f.kind == kind).collect();
            if group.is_empty() {
                continue;
            }
            group.sort_by(|a, b| a.ulid.cmp(&b.ulid));
            let _ = write!(out, "#### {}\n\n", kind.title());
            for f in group {
                // Reference by handle and ULID in plain text, never a path (navigation.md 1).
                let _ = writeln!(out, "- {} ({}, {})", f.text, f.handle, f.ulid);
            }
            out.push('\n');
        }
    }
    let hash = digest(&out);
    let _ = writeln!(out, "{MARKER}{version} blake3:{hash} -->");
    out
}

fn digest(body: &str) -> String {
    blake3::hash(body.trim_end().as_bytes())
        .to_hex()
        .to_string()
}

/// Split CHANGELOG.md into its header and its `## ` sections (each with its trailing newline).
pub fn split(text: &str) -> (&str, Vec<&str>) {
    let mut starts: Vec<usize> = Vec::new();
    let mut pos = 0;
    for line in text.split_inclusive('\n') {
        if line.starts_with("## ") {
            starts.push(pos);
        }
        pos += line.len();
    }
    let Some(&first) = starts.first() else {
        return (text, Vec::new());
    };
    let mut sections = Vec::new();
    for (i, &s) in starts.iter().enumerate() {
        let end = starts.get(i + 1).copied().unwrap_or(text.len());
        sections.push(&text[s..end]);
    }
    (&text[..first], sections)
}

/// Verify every section after the header carries a marker whose hash matches its body.
///
/// # Errors
/// [`ReleaseError::Unmarked`] for a section with no marker, [`ReleaseError::Tampered`] for a hash mismatch.
///
/// A hand-written file (see [`is_generated`]) is being adopted: its unmarked sections are the
/// author's and are skipped; only sections that carry a marker are verified.
pub fn verify(text: &str) -> Result<(), ReleaseError> {
    let (_, sections) = split(text);
    let adopted = !is_generated(text);
    for sec in sections {
        if adopted
            && !sec
                .trim_end()
                .lines()
                .last()
                .is_some_and(|l| l.starts_with(MARKER))
        {
            continue;
        }
        let heading = sec
            .lines()
            .next()
            .unwrap_or("")
            .trim_start_matches("## ")
            .to_owned();
        let trimmed = sec.trim_end();
        let (body, marker) = match trimmed.rsplit_once('\n') {
            Some((b, m)) if m.starts_with(MARKER) => (b, m),
            _ => return Err(ReleaseError::Unmarked(heading)),
        };
        let version = heading.split(' ').next().unwrap_or("").to_owned();
        let want = format!("{MARKER}{version} blake3:{} -->", digest(body));
        if marker != want {
            tracing::warn!(section = %version, "section hash mismatch");
            return Err(ReleaseError::Tampered(version));
        }
    }
    Ok(())
}

/// True when a section for `version` is already present.
pub fn has_version(text: &str, version: &str) -> bool {
    text.lines().any(|l| heading_version(l) == Some(version))
}

/// The body of the section for `version` in a CHANGELOG.md `text`: what follows its `## ` heading, without the integrity marker, trimmed of blank edges; `None` when there is no such section.
///
/// This is the text `frob release notes` prints for `gh release create --notes-file`.
pub fn section_body(text: &str, version: &str) -> Option<String> {
    let (_, sections) = split(text);
    let sec = sections
        .into_iter()
        .find(|s| s.lines().next().and_then(heading_version) == Some(version))?;
    let body: Vec<&str> = sec
        .lines()
        .skip(1)
        .filter(|l| !l.starts_with(MARKER))
        .collect();
    Some(body.join("\n").trim().to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    // frob:ticket 01M41B4KPWQVBT234N2DY20758
    // frob:tests crates/frob-release/src/changelog.rs::section_body
    #[test]
    fn section_body_is_exactly_one_versions_body_without_heading_or_marker() {
        let text = "<!-- GENERATED by frob: x -->\n# Changelog\n\n\
                    ## 0.2.0 - 2026-10-04\n\nNew.\n\n<!-- frob-section: 0.2.0 blake3:aa -->\n\
                    ## 0.1.0 - 2026-10-03\n\nOld.\n\n#### Added\n\n- x\n\n<!-- frob-section: 0.1.0 blake3:bb -->\n";
        assert_eq!(section_body(text, "0.2.0").as_deref(), Some("New."));
        assert_eq!(
            section_body(text, "0.1.0").as_deref(),
            Some("Old.\n\n#### Added\n\n- x")
        );
        assert_eq!(section_body(text, "0.3.0"), None);
        assert_eq!(section_body("", "0.1.0"), None);
    }
}
