//! Rendering a version section and verifying the sections already in CHANGELOG.md.

use std::fmt::Write as _;

use crate::error::ReleaseError;
use crate::fragment::{Fragment, Kind, PRODUCTS};

/// Prefix of the integrity line that closes every compiled section.
const MARKER: &str = "<!-- frob-section: ";

/// The header of a fresh CHANGELOG.md: generated-file marker, visible line, link to the v1 history.
pub fn initial_header() -> String {
    "<!-- GENERATED by frob: DO NOT EDIT between releases. Regenerate: frob release changelog --version <X> -->\n\
     # Changelog\n\n\
     Generated by `frob release changelog` from `changelog.d/` fragments; compiled at release, never hand-edited.\n\
     The history of frob v1 (before 0.532.0) is in [CHANGELOG-v1.md](CHANGELOG-v1.md).\n\n"
        .to_owned()
}

/// Render the section for `version`: grouped by product, then type, entries by ULID, closed by its hash.
pub fn render_section(version: &str, date: &str, fragments: &[Fragment]) -> String {
    let mut out = format!("## {version} - {date}\n\n");
    for product in PRODUCTS {
        let mine: Vec<&Fragment> = fragments.iter().filter(|f| f.product == product).collect();
        if mine.is_empty() {
            continue;
        }
        let _ = write!(out, "### {product}\n\n");
        for kind in Kind::ALL {
            let mut group: Vec<&&Fragment> = mine.iter().filter(|f| f.kind == kind).collect();
            if group.is_empty() {
                continue;
            }
            group.sort_by(|a, b| a.ulid.cmp(&b.ulid));
            let _ = write!(out, "#### {}\n\n", kind.title());
            for f in group {
                let _ = writeln!(
                    out,
                    "- {} ([{}](tickets/{}/ticket.md))",
                    f.text, f.handle, f.ulid
                );
            }
            out.push('\n');
        }
    }
    let hash = digest(&out);
    let _ = writeln!(out, "{MARKER}{version} blake3:{hash} -->");
    out
}

fn digest(body: &str) -> String {
    blake3::hash(body.trim_end().as_bytes())
        .to_hex()
        .to_string()
}

/// Split CHANGELOG.md into its header and its `## ` sections (each with its trailing newline).
pub fn split(text: &str) -> (&str, Vec<&str>) {
    let mut starts: Vec<usize> = Vec::new();
    let mut pos = 0;
    for line in text.split_inclusive('\n') {
        if line.starts_with("## ") {
            starts.push(pos);
        }
        pos += line.len();
    }
    let Some(&first) = starts.first() else {
        return (text, Vec::new());
    };
    let mut sections = Vec::new();
    for (i, &s) in starts.iter().enumerate() {
        let end = starts.get(i + 1).copied().unwrap_or(text.len());
        sections.push(&text[s..end]);
    }
    (&text[..first], sections)
}

/// Verify every section after the header carries a marker whose hash matches its body.
///
/// # Errors
/// [`ReleaseError::Unmarked`] for a section with no marker, [`ReleaseError::Tampered`] for a hash mismatch.
pub fn verify(text: &str) -> Result<(), ReleaseError> {
    let (_, sections) = split(text);
    for sec in sections {
        let heading = sec
            .lines()
            .next()
            .unwrap_or("")
            .trim_start_matches("## ")
            .to_owned();
        let trimmed = sec.trim_end();
        let (body, marker) = match trimmed.rsplit_once('\n') {
            Some((b, m)) if m.starts_with(MARKER) => (b, m),
            _ => return Err(ReleaseError::Unmarked(heading)),
        };
        let version = heading.split(' ').next().unwrap_or("").to_owned();
        let want = format!("{MARKER}{version} blake3:{} -->", digest(body));
        if marker != want {
            tracing::warn!(section = %version, "section hash mismatch");
            return Err(ReleaseError::Tampered(version));
        }
    }
    Ok(())
}

/// True when a section for `version` is already present.
pub fn has_version(text: &str, version: &str) -> bool {
    split(text).1.iter().any(|s| {
        s.lines()
            .next()
            .and_then(|l| l.strip_prefix("## "))
            .and_then(|l| l.split(' ').next())
            == Some(version)
    })
}
