//! `release bump` tests on temporary workspaces: bump, idempotence, downgrade, dry run, formatting.
// frob:ticket 01M4069X2KPQ6RNV26SWSY4VA5

use std::fs;
use std::path::Path;

use frob_release::bump::{BumpError, BumpOptions, LockState, run};

const ROOT: &str = "# workspace root\n[workspace]\nmembers = [\"crates/*\"]\n\n[workspace.package]\nversion = \"0.0.0\"\nedition = \"2024\"\n";

const A: &str = "# crate a\n[package]\nname = \"a\"\nversion = \"0.0.0\" # lockstep\nedition = \"2024\"\n\n[dependencies]\nb = { path = \"../b\", version = \"0.0.0\" }   # pin for publishing\nserde = \"1\"\n\n[target.'cfg(unix)'.dev-dependencies]\nb = { path = \"../b\", version = \"=0.0.0\" }\n";

const B: &str = "[package]\nname = \"b\"\nedition = \"2024\"\n\n[dependencies]\n";

const WHEEL: &str = "[build-system]\nrequires = [\"setuptools\"]\nbuild-backend = \"setuptools.build_meta\"\n\n[project]\nname = \"frob\"\nversion = \"0.0.0\"  # keep in step\n";

const LOCK: &str = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"a\"\nversion = \"0.0.0\"\ndependencies = [\n \"b\",\n]\n\n[[package]]\nname = \"b\"\nversion = \"0.0.0\"\n";

fn write(root: &Path, rel: &str, text: &str) {
    let p = root.join(rel);
    fs::create_dir_all(p.parent().unwrap()).unwrap();
    fs::write(p, text).unwrap();
}

fn fixture() -> tempfile::TempDir {
    let d = tempfile::tempdir().unwrap();
    let r = d.path();
    write(r, "Cargo.toml", ROOT);
    write(r, "crates/a/Cargo.toml", A);
    write(r, "crates/a/src/lib.rs", "");
    write(r, "crates/b/Cargo.toml", B);
    write(r, "crates/b/src/lib.rs", "");
    write(r, "pyproject.toml", WHEEL);
    write(r, "Cargo.lock", LOCK);
    d
}

fn opts(version: &str) -> BumpOptions {
    BumpOptions {
        version: version.to_owned(),
        dry_run: false,
        allow_downgrade: false,
    }
}

fn text(root: &Path, rel: &str) -> String {
    fs::read_to_string(root.join(rel)).unwrap()
}

fn snapshot(root: &Path) -> Vec<(String, String)> {
    [
        "Cargo.toml",
        "crates/a/Cargo.toml",
        "crates/b/Cargo.toml",
        "pyproject.toml",
        "Cargo.lock",
    ]
    .iter()
    .map(|p| ((*p).to_owned(), text(root, p)))
    .collect()
}

#[test]
fn bump_sets_every_crate_pin_wheel_and_lock() {
    // frob:tests crates/frob-release/src/bump.rs::run
    let d = fixture();
    let r = run(d.path(), &opts("0.532.0")).unwrap();
    assert!(!r.already);
    assert_eq!(r.previous.as_deref(), Some("0.0.0"));
    assert_eq!(r.lock, LockState::Refreshed);
    assert_eq!(r.rel002, Some(vec![]), "REL002 clean after the bump");
    let root = text(d.path(), "Cargo.toml");
    assert!(root.contains("version = \"0.532.0\""), "{root}");
    let a_toml = text(d.path(), "crates/a/Cargo.toml");
    assert!(a_toml.contains("version.workspace = true"), "{a_toml}");
    assert!(
        a_toml.contains("version = \"0.532.0\" }   # pin for publishing"),
        "{a_toml}"
    );
    assert!(
        a_toml.contains("version.workspace = true # lockstep"),
        "{a_toml}"
    );
    assert!(a_toml.contains("version = \"=0.532.0\""), "{a_toml}");
    assert!(!a_toml.contains("0.0.0"), "{a_toml}");
    let b_toml = text(d.path(), "crates/b/Cargo.toml");
    assert!(b_toml.contains("version.workspace = true"), "{b_toml}");
    let wheel = text(d.path(), "pyproject.toml");
    assert!(
        wheel.contains("version = \"0.532.0\"  # keep in step"),
        "{wheel}"
    );
    let lock = text(d.path(), "Cargo.lock");
    assert_eq!(lock.matches("version = \"0.532.0\"").count(), 2, "{lock}");
    assert!(!lock.contains("0.0.0"), "{lock}");
}

#[test]
fn repeat_changes_nothing() {
    // frob:tests crates/frob-release/src/bump.rs::run
    let d = fixture();
    run(d.path(), &opts("0.532.0")).unwrap();
    let before = snapshot(d.path());
    let r = run(d.path(), &opts("0.532.0")).unwrap();
    assert!(r.already);
    assert!(r.files.is_empty());
    assert_eq!(r.lock, LockState::NotNeeded);
    assert_eq!(snapshot(d.path()), before);
}

#[test]
fn downgrade_is_refused_with_a_remedy_unless_allowed() {
    // frob:tests crates/frob-release/src/bump.rs::run
    let d = fixture();
    run(d.path(), &opts("0.532.0")).unwrap();
    let before = snapshot(d.path());
    let err = run(d.path(), &opts("0.531.0")).unwrap_err();
    assert!(matches!(err, BumpError::Downgrade { .. }), "{err}");
    assert!(err.to_string().contains("--allow-downgrade"), "{err}");
    assert_eq!(snapshot(d.path()), before);
    let mut o = opts("0.531.0");
    o.allow_downgrade = true;
    let r = run(d.path(), &o).unwrap();
    assert!(!r.already);
    assert!(text(d.path(), "Cargo.toml").contains("0.531.0"));
}

#[test]
fn invalid_version_is_refused() {
    // frob:tests crates/frob-release/src/bump.rs::run
    let d = fixture();
    let err = run(d.path(), &opts("1.2")).unwrap_err();
    assert!(matches!(err, BumpError::InvalidVersion(_)), "{err}");
}

#[test]
fn dry_run_reports_files_and_diffs_but_writes_nothing() {
    // frob:tests crates/frob-release/src/bump.rs::run
    let d = fixture();
    let before = snapshot(d.path());
    let mut o = opts("0.532.0");
    o.dry_run = true;
    let r = run(d.path(), &o).unwrap();
    assert!(r.dry_run && !r.already);
    assert_eq!(r.lock, LockState::WouldRefresh);
    let paths: Vec<&str> = r.files.iter().map(|f| f.path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "Cargo.toml",
            "crates/a/Cargo.toml",
            "crates/b/Cargo.toml",
            "pyproject.toml"
        ]
    );
    assert!(
        r.files[0].diff.contains("+version = \"0.532.0\""),
        "{}",
        r.files[0].diff
    );
    assert_eq!(snapshot(d.path()), before);
}

#[test]
fn comments_and_layout_survive_and_the_workspace_version_is_added_when_absent() {
    // frob:tests crates/frob-release/src/bump.rs::run
    let d = fixture();
    write(
        d.path(),
        "Cargo.toml",
        "# keep me\n[workspace]\nmembers = [\"crates/*\"]   # globbed\n",
    );
    run(d.path(), &opts("1.0.0")).unwrap();
    let root = text(d.path(), "Cargo.toml");
    assert!(
        root.starts_with("# keep me\n[workspace]\nmembers = [\"crates/*\"]   # globbed\n"),
        "{root}"
    );
    assert!(
        root.contains("[workspace.package]\nversion = \"1.0.0\""),
        "{root}"
    );
    let a = text(d.path(), "crates/a/Cargo.toml");
    assert!(a.starts_with("# crate a\n"), "{a}");
    assert!(a.contains("version.workspace = true # lockstep"), "{a}");
    assert!(a.contains("serde = \"1\"\n"), "{a}");
    assert!(a.contains("# pin for publishing"), "{a}");
}
