//! `release cut` engine tests on temporary repositories with a fake ledger: one commit, tags, resume, refusals.
// frob:ticket 01M4069X6S9RJWRXX3YBZ9EG10

use std::cell::RefCell;
use std::fs;
use std::path::Path;

use frob_pm::event::CutData;
use frob_release::cut::{CutError, CutLedger, CutPlan, Phase, SHIPPED_BINARIES, cut, tag_name};
use gob_git::{CommitOptions, RelPath, Repo};

const ROOT: &str = "[workspace]\nmembers = [\"crates/*\"]\n\n[workspace.package]\nversion = \"0.0.0\"\nedition = \"2024\"\n";
const A: &str = "[package]\nname = \"a\"\nversion = \"0.0.0\"\nedition = \"2024\"\n";
const LOCK: &str = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"a\"\nversion = \"0.0.0\"\n";

/// A ledger double recording what the engine asked of it.
#[derive(Default)]
struct Fake {
    ready: bool,
    cleared: u32,
    recorded: RefCell<Vec<CutData>>,
    done: bool,
    fail_record: bool,
}

impl CutLedger for Fake {
    fn clear(&mut self) -> Result<(), CutError> {
        self.cleared += 1;
        if self.ready {
            Ok(())
        } else {
            Err(CutError::NotReady("NOT READY: 1 blocker".to_owned()))
        }
    }
    fn recorded(&self) -> Result<bool, CutError> {
        Ok(self.done)
    }
    fn record(&mut self, data: &CutData) -> Result<(), CutError> {
        if self.fail_record {
            return Err(CutError::Ledger("simulated".to_owned()));
        }
        self.recorded.borrow_mut().push(data.clone());
        self.done = true;
        Ok(())
    }
}

fn opts() -> CommitOptions {
    CommitOptions {
        cas_retries: 5,
        author: Some(("Test".into(), "test@example.com".into())),
    }
}

/// A repository on `main` with a workspace, a lockfile and one changelog fragment, committed.
fn fixture() -> (tempfile::TempDir, Repo) {
    let dir = tempfile::tempdir().unwrap();
    let repo = Repo::init(dir.path()).unwrap();
    fs::write(repo.git_dir().join("HEAD"), "ref: refs/heads/main\n").unwrap();
    let files = [
        ("Cargo.toml", ROOT),
        ("crates/a/Cargo.toml", A),
        ("crates/a/src/lib.rs", ""),
        ("Cargo.lock", LOCK),
        (
            "changelog.d/01M4069X6S9RJWRXX3YBZ9EG10.added.md",
            "frob: Added cut.\n",
        ),
    ];
    let changes: Vec<_> = files
        .iter()
        .map(|(p, t)| (RelPath::new(*p).unwrap(), Some(t.as_bytes().to_vec())))
        .collect();
    repo.commit_paths("refs/heads/main", &changes, "base", &opts())
        .unwrap();
    // Author identity for the release commit and tags.
    fs::write(
        repo.git_dir().join("config"),
        format!(
            "{}[user]\n\tname = Test\n\temail = test@example.com\n",
            fs::read_to_string(repo.git_dir().join("config")).unwrap()
        ),
    )
    .unwrap();
    (dir, repo)
}

fn plan(root: &Path, stop: Option<Phase>) -> CutPlan<'_> {
    CutPlan {
        root,
        version: "0.532.0".to_owned(),
        date: "2026-10-03".to_owned(),
        base: "main".to_owned(),
        push: false,
        stop_after: stop,
    }
}

#[allow(clippy::unnecessary_wraps)] // the TicketResolver signature
fn resolver(ulid: &str) -> Option<String> {
    Some(format!("~{}", &ulid[ulid.len() - 7..]))
}

fn count(repo: &Repo) -> usize {
    repo.first_parent_subjects("main", 100).unwrap().len()
}

#[test]
fn a_ready_cut_is_one_commit_with_bump_and_changelog_and_both_tags() {
    // frob:tests crates/frob-release/src/cut.rs::cut
    let (d, repo) = fixture();
    let before = count(&repo);
    let mut ledger = Fake {
        ready: true,
        ..Fake::default()
    };
    let out = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap();
    assert_eq!(count(&repo), before + 1, "exactly one commit");
    let tip = repo.rev_parse("main").unwrap();
    assert_eq!(out.commit, tip);
    assert!(!out.resumed);
    let mut files = out.files.clone();
    files.sort();
    assert_eq!(
        files,
        [
            "CHANGELOG.md",
            "Cargo.lock",
            "Cargo.toml",
            "changelog.d/01M4069X6S9RJWRXX3YBZ9EG10.added.md",
            "crates/a/Cargo.toml"
        ]
    );
    let changelog =
        String::from_utf8(repo.read_blob_at("main", "CHANGELOG.md").unwrap().unwrap()).unwrap();
    assert!(changelog.contains("## 0.532.0 - 2026-10-03") && changelog.contains("Added cut."));
    assert!(
        repo.read_blob_at("main", FRAG_PATH).unwrap().is_none(),
        "fragment removed"
    );
    let root =
        String::from_utf8(repo.read_blob_at("main", "Cargo.toml").unwrap().unwrap()).unwrap();
    assert!(root.contains("version = \"0.532.0\""), "{root}");
    for bin in SHIPPED_BINARIES {
        let t = repo
            .find_tag(&tag_name(bin, "0.532.0"))
            .unwrap()
            .expect("tag");
        assert!(t.annotated);
        assert_eq!(t.commit, tip);
    }
    assert!(SHIPPED_BINARIES.contains(&"grimble"));
    let rec = ledger.recorded.borrow();
    assert_eq!(rec.len(), 1);
    assert_eq!(rec[0].commit, tip.to_string());
    assert_eq!(rec[0].tags.len(), 2);
    assert!(
        gob_git::Repo::discover(d.path())
            .unwrap()
            .status(&gob_git::StatusOptions::default())
            .unwrap()
            .is_empty(),
        "tree synced and clean"
    );
}

const FRAG_PATH: &str = "changelog.d/01M4069X6S9RJWRXX3YBZ9EG10.added.md";

#[test]
fn not_ready_refuses_and_leaves_the_tree_and_refs_alone() {
    // frob:tests crates/frob-release/src/cut.rs::cut
    let (d, repo) = fixture();
    let tip = repo.rev_parse("main").unwrap();
    let mut ledger = Fake::default();
    let err = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap_err();
    assert!(
        matches!(err, CutError::NotReady(_)) && err.is_refusal(),
        "{err}"
    );
    assert!(
        err.remedy("0.532.0", "main")
            .contains("--override --reason")
    );
    assert_eq!(repo.rev_parse("main").unwrap(), tip);
    assert!(d.path().join(FRAG_PATH).exists());
    assert!(repo.find_tag("frob-v0.532.0").unwrap().is_none());
}

#[test]
fn a_dirty_tree_is_refused() {
    // frob:tests crates/frob-release/src/cut.rs::cut
    let (d, _repo) = fixture();
    fs::write(d.path().join("stray.txt"), "x").unwrap();
    let mut ledger = Fake {
        ready: true,
        ..Fake::default()
    };
    let err = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap_err();
    match err {
        CutError::Dirty(p) => assert_eq!(p, ["stray.txt"]),
        e => panic!("{e}"),
    }
    assert_eq!(ledger.cleared, 0);
}

#[test]
fn an_existing_tag_is_refused_and_never_moved() {
    // frob:tests crates/frob-release/src/cut.rs::cut
    let (d, repo) = fixture();
    let tip = repo.rev_parse("main").unwrap();
    let obj = repo
        .create_annotated_tag("frob-v0.532.0", tip, "foreign", None)
        .unwrap();
    let mut ledger = Fake {
        ready: true,
        ..Fake::default()
    };
    let err = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap_err();
    assert!(
        matches!(err, CutError::TagExists(ref t) if t == "frob-v0.532.0"),
        "{err}"
    );
    assert_eq!(repo.find_tag("frob-v0.532.0").unwrap().unwrap().object, obj);
    assert_eq!(repo.rev_parse("main").unwrap(), tip, "no commit made");
}

#[test]
fn a_cut_interrupted_between_commit_and_tag_resumes_without_a_second_commit() {
    // frob:tests crates/frob-release/src/cut.rs::cut
    let (d, repo) = fixture();
    let before = count(&repo);
    let mut ledger = Fake {
        ready: true,
        ..Fake::default()
    };
    let err = cut(&plan(d.path(), Some(Phase::Commit)), &resolver, &mut ledger).unwrap_err();
    assert!(matches!(err, CutError::Stopped(Phase::Commit)));
    assert_eq!(count(&repo), before + 1);
    assert!(repo.find_tag("frob-v0.532.0").unwrap().is_none());
    assert!(ledger.recorded.borrow().is_empty());
    let commit = repo.rev_parse("main").unwrap();
    let out = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap();
    assert!(out.resumed);
    assert_eq!(out.commit, commit);
    assert_eq!(count(&repo), before + 1, "still one release commit");
    assert_eq!(ledger.cleared, 1, "the gate ran only for the fresh part");
    for bin in SHIPPED_BINARIES {
        assert_eq!(
            repo.find_tag(&tag_name(bin, "0.532.0"))
                .unwrap()
                .unwrap()
                .commit,
            commit
        );
    }
    assert_eq!(ledger.recorded.borrow().len(), 1);
}

#[test]
fn a_cut_interrupted_before_the_record_resumes_and_records_only() {
    // frob:tests crates/frob-release/src/cut.rs::cut
    let (d, repo) = fixture();
    let mut ledger = Fake {
        ready: true,
        fail_record: true,
        ..Fake::default()
    };
    let err = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap_err();
    assert!(matches!(err, CutError::Ledger(_)) && !err.is_refusal());
    let commit = repo.rev_parse("main").unwrap();
    let frob_tag = repo.find_tag("frob-v0.532.0").unwrap().unwrap();
    ledger.fail_record = false;
    let out = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap();
    assert!(out.resumed && out.commit == commit);
    assert_eq!(
        repo.find_tag("frob-v0.532.0").unwrap().unwrap().object,
        frob_tag.object,
        "tags are reused"
    );
    assert_eq!(ledger.recorded.borrow().len(), 1);
    let again = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap_err();
    assert!(matches!(again, CutError::Already(_)), "{again}");
}

#[test]
fn a_failure_before_the_commit_restores_the_tree() {
    // frob:tests crates/frob-release/src/cut.rs::cut
    let (d, repo) = fixture();
    fs::remove_file(d.path().join(FRAG_PATH)).unwrap();
    // Re-commit the deletion so the tree is clean, then add a bad fragment name so the compile fails after the bump.
    let change = (
        RelPath::new("changelog.d/bad.md").unwrap(),
        Some(b"x".to_vec()),
    );
    let del = (RelPath::new(FRAG_PATH).unwrap(), None);
    repo.commit_paths("refs/heads/main", &[change, del], "bad", &opts())
        .unwrap();
    let tip = repo.rev_parse("main").unwrap();
    let mut ledger = Fake {
        ready: true,
        ..Fake::default()
    };
    let err = cut(&plan(d.path(), None), &resolver, &mut ledger).unwrap_err();
    assert!(
        matches!(err, CutError::Changelog(_)) && err.is_refusal(),
        "{err}"
    );
    assert_eq!(repo.rev_parse("main").unwrap(), tip);
    let root = fs::read_to_string(d.path().join("Cargo.toml")).unwrap();
    assert!(root.contains("version = \"0.0.0\""), "bump undone: {root}");
    assert!(
        repo.status(&gob_git::StatusOptions::default())
            .unwrap()
            .is_empty()
    );
}
