//! The `config.<table>` side relation, typed from the config JSON schema
//! (`docs/schemas/config.json`, generated by `gob-config`).
//!
//! The schema is passed in as a value rather than embedded so this crate does not reach outside
//! its own directory; the binary hands over the file it ships. A path is a table, a scalar key
//! or an array of rows; the columns of a row come from the schema's `$defs` entry (or an inline
//! object) when the schema carries it.

// frob:ticket 01M3ZX7DMYNTWB3AP04CDMAECH
use std::collections::BTreeMap;

use serde_json::Value;

use super::{Column, FieldType};

/// One node of the config tree.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConfigNode {
    /// The node's type; a table or an array of rows is `Any`.
    pub ty: FieldType,
    /// The columns of a row when the node is an array of objects whose shape the schema gives.
    pub columns: Option<Vec<Column>>,
    /// The child keys when the node is a table, sorted.
    pub children: Vec<String>,
}

/// The config schema as a typed tree keyed by dotted path.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ConfigSchema {
    nodes: BTreeMap<String, ConfigNode>,
}

fn scalar(schema: &Value) -> FieldType {
    match schema.get("type").and_then(Value::as_str) {
        Some("string") => FieldType::Str,
        Some("integer") => FieldType::Int,
        Some("number") => FieldType::Float,
        Some("boolean") => FieldType::Bool,
        _ => FieldType::Any,
    }
}

/// The object schema a row is described by: an inline object or a `$defs` reference.
fn row_schema<'a>(root: &'a Value, items: &'a Value) -> Option<&'a Value> {
    match items.get("$ref").and_then(Value::as_str) {
        Some(r) => root.pointer(r.strip_prefix('#')?),
        None => Some(items),
    }
}

fn columns_of(root: &Value, prop: &Value) -> Option<Vec<Column>> {
    let items = prop.get("items")?;
    let row = row_schema(root, items)?;
    let props = row.get("properties")?.as_object()?;
    Some(
        props
            .iter()
            .map(|(name, p)| Column {
                name: name.clone(),
                ty: scalar(p),
            })
            .collect(),
    )
}

impl ConfigSchema {
    /// Build the typed tree from the schema document.
    pub fn from_json(root: &Value) -> Self {
        let mut nodes = BTreeMap::new();
        walk(root, root, "", &mut nodes);
        tracing::debug!(nodes = nodes.len(), "typed the config schema");
        Self { nodes }
    }

    /// The node at a dotted path such as `invariants.forbid_imports`.
    pub fn node(&self, path: &str) -> Option<&ConfigNode> {
        self.nodes.get(path)
    }

    /// The top-level table names, sorted.
    pub fn tables(&self) -> Vec<&str> {
        self.nodes
            .keys()
            .filter(|k| !k.contains('.'))
            .map(String::as_str)
            .collect()
    }

    /// Whether the schema carries any node (an empty schema types nothing).
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }
}

fn walk(root: &Value, node: &Value, prefix: &str, out: &mut BTreeMap<String, ConfigNode>) {
    let Some(props) = node.get("properties").and_then(Value::as_object) else {
        return;
    };
    for (key, prop) in props {
        let path = if prefix.is_empty() {
            key.clone()
        } else {
            format!("{prefix}.{key}")
        };
        let children: Vec<String> = prop
            .get("properties")
            .and_then(Value::as_object)
            .map(|m| m.keys().cloned().collect())
            .unwrap_or_default();
        out.insert(
            path.clone(),
            ConfigNode {
                ty: scalar(prop),
                columns: columns_of(root, prop),
                children,
            },
        );
        walk(root, prop, &path, out);
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn sample() -> Value {
        json!({
            "properties": {
                "invariants": {"type": "object", "properties": {
                    "forbid_imports": {"type": "array", "items": {"$ref": "#/$defs/ForbidImport"}}
                }},
                "lease": {"type": "object", "properties": {
                    "ttl_secs": {"type": "integer"},
                    "shared_files": {"type": "array", "items": {"type": "string"}}
                }}
            },
            "$defs": {"ForbidImport": {"type": "object", "properties": {
                "from": {"type": "string"}, "to": {"type": "string"}, "reason": {"type": "string"}
            }}}
        })
    }

    #[test]
    fn row_columns_resolve_through_defs() {
        let s = ConfigSchema::from_json(&sample());
        let cols = s
            .node("invariants.forbid_imports")
            .unwrap()
            .columns
            .clone()
            .unwrap();
        let names: Vec<&str> = cols.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, ["from", "reason", "to"]);
        assert!(!names.contains(&"frm"));
        assert_eq!(s.node("lease.ttl_secs").unwrap().ty, FieldType::Int);
        assert_eq!(s.tables(), ["invariants", "lease"]);
    }

    #[test]
    fn a_ref_the_schema_lacks_leaves_the_row_untyped() {
        let mut doc = sample();
        doc.as_object_mut().unwrap().remove("$defs");
        let s = ConfigSchema::from_json(&doc);
        assert!(
            s.node("invariants.forbid_imports")
                .unwrap()
                .columns
                .is_none()
        );
    }
}
