// @generated by `cargo dev gen rules-index`; do not edit by hand.
//! The rules of this crate, one module per `src/rules/<id>.rs`.

/// Rule `BP001`.
pub mod bp001;
/// Rule `BP002`.
pub mod bp002;
/// Rule `BP003`.
pub mod bp003;
/// Rule `COLOR001`.
pub mod color001;
/// Rule `COLOR002`.
pub mod color002;
/// Rule `CONTRAST001`.
pub mod contrast001;
/// Rule `LAYER001`.
pub mod layer001;
/// Rule `ORG001`.
pub mod org001;
/// Rule `ORG002`.
pub mod org002;
/// Rule `ORG003`.
pub mod org003;
/// Rule `ORG004`.
pub mod org004;
/// Rule `ORG005`.
pub mod org005;
/// Rule `RADIUS001`.
pub mod radius001;
/// Rule `SIZE001`.
pub mod size001;
/// Rule `SPACE001`.
pub mod space001;
/// Rule `TOKENS001`.
pub mod tokens001;
/// Rule `TW001`.
pub mod tw001;
/// Rule `TW002`.
pub mod tw002;
/// Rule `TW003`.
pub mod tw003;
/// Rule `TW004`.
pub mod tw004;
/// Rule `TW005`.
pub mod tw005;
/// Rule `TYPE001`.
pub mod type001;
/// Rule `TYPE002`.
pub mod type002;
/// Rule `TYPE003`.
pub mod type003;
/// Rule `WAIVE001`.
pub mod waive001;

/// The declaration of every rule in this crate, sorted by file stem.
pub const METAS: &[&gob_rules::RuleDef] = &[
    // one entry per rule file
    <bp001::Bp001 as gob_rules::RuleDecl>::DEF,
    <bp002::Bp002 as gob_rules::RuleDecl>::DEF,
    <bp003::Bp003 as gob_rules::RuleDecl>::DEF,
    <color001::Color001 as gob_rules::RuleDecl>::DEF,
    <color002::Color002 as gob_rules::RuleDecl>::DEF,
    <contrast001::Contrast001 as gob_rules::RuleDecl>::DEF,
    <layer001::Layer001 as gob_rules::RuleDecl>::DEF,
    <org001::Org001 as gob_rules::RuleDecl>::DEF,
    <org002::Org002 as gob_rules::RuleDecl>::DEF,
    <org003::Org003 as gob_rules::RuleDecl>::DEF,
    <org004::Org004 as gob_rules::RuleDecl>::DEF,
    <org005::Org005 as gob_rules::RuleDecl>::DEF,
    <radius001::Radius001 as gob_rules::RuleDecl>::DEF,
    <size001::Size001 as gob_rules::RuleDecl>::DEF,
    <space001::Space001 as gob_rules::RuleDecl>::DEF,
    <tokens001::Tokens001 as gob_rules::RuleDecl>::DEF,
    <tw001::Tw001 as gob_rules::RuleDecl>::DEF,
    <tw002::Tw002 as gob_rules::RuleDecl>::DEF,
    <tw003::Tw003 as gob_rules::RuleDecl>::DEF,
    <tw004::Tw004 as gob_rules::RuleDecl>::DEF,
    <tw005::Tw005 as gob_rules::RuleDecl>::DEF,
    <type001::Type001 as gob_rules::RuleDecl>::DEF,
    <type002::Type002 as gob_rules::RuleDecl>::DEF,
    <type003::Type003 as gob_rules::RuleDecl>::DEF,
    <waive001::Waive001 as gob_rules::RuleDecl>::DEF,
];

/// This crate's rule index: the declarations plus renamed and retired ids.
pub const INDEX: gob_rules::RuleIndex = gob_rules::RuleIndex {
    krate: env!("CARGO_PKG_NAME"),
    metas: METAS,
    renamed: &[],
    retired: &[],
};

const _: () = gob_rules::assert_unique("crate", &[&[&INDEX]]);

/// Bind every rule of this crate to the product host `P`; fails to compile unless `P` hosts them all.
#[allow(clippy::vec_init_then_push, reason = "generated: one push per rule")]
pub fn bind<P: ?Sized + 'static>() -> Vec<gob_rules::BoundRule<P>>
where
    bp001::Bp001: gob_rules::Measured<P>,
    bp002::Bp002: gob_rules::Measured<P>,
    bp003::Bp003: gob_rules::Measured<P>,
    color001::Color001: gob_rules::Measured<P>,
    color002::Color002: gob_rules::Measured<P>,
    contrast001::Contrast001: gob_rules::RepoRule<P>,
    layer001::Layer001: gob_rules::Measured<P>,
    org001::Org001: gob_rules::Measured<P>,
    org002::Org002: gob_rules::Measured<P>,
    org003::Org003: gob_rules::Measured<P>,
    org004::Org004: gob_rules::Measured<P>,
    org005::Org005: gob_rules::Measured<P>,
    radius001::Radius001: gob_rules::Measured<P>,
    size001::Size001: gob_rules::Measured<P>,
    space001::Space001: gob_rules::Measured<P>,
    tokens001::Tokens001: gob_rules::Measured<P>,
    tw001::Tw001: gob_rules::Measured<P>,
    tw002::Tw002: gob_rules::Measured<P>,
    tw003::Tw003: gob_rules::Measured<P>,
    tw004::Tw004: gob_rules::Measured<P>,
    tw005::Tw005: gob_rules::Measured<P>,
    type001::Type001: gob_rules::Measured<P>,
    type002::Type002: gob_rules::Measured<P>,
    type003::Type003: gob_rules::Measured<P>,
    waive001::Waive001: gob_rules::FileRule<P>,
{
    let mut rules = Vec::new();
    rules.push(gob_rules::BoundRule::measured(bp001::Bp001));
    rules.push(gob_rules::BoundRule::measured(bp002::Bp002));
    rules.push(gob_rules::BoundRule::measured(bp003::Bp003));
    rules.push(gob_rules::BoundRule::measured(color001::Color001));
    rules.push(gob_rules::BoundRule::measured(color002::Color002));
    rules.push(gob_rules::BoundRule::repo(contrast001::Contrast001));
    rules.push(gob_rules::BoundRule::measured(layer001::Layer001));
    rules.push(gob_rules::BoundRule::measured(org001::Org001));
    rules.push(gob_rules::BoundRule::measured(org002::Org002));
    rules.push(gob_rules::BoundRule::measured(org003::Org003));
    rules.push(gob_rules::BoundRule::measured(org004::Org004));
    rules.push(gob_rules::BoundRule::measured(org005::Org005));
    rules.push(gob_rules::BoundRule::measured(radius001::Radius001));
    rules.push(gob_rules::BoundRule::measured(size001::Size001));
    rules.push(gob_rules::BoundRule::measured(space001::Space001));
    rules.push(gob_rules::BoundRule::measured(tokens001::Tokens001));
    rules.push(gob_rules::BoundRule::measured(tw001::Tw001));
    rules.push(gob_rules::BoundRule::measured(tw002::Tw002));
    rules.push(gob_rules::BoundRule::measured(tw003::Tw003));
    rules.push(gob_rules::BoundRule::measured(tw004::Tw004));
    rules.push(gob_rules::BoundRule::measured(tw005::Tw005));
    rules.push(gob_rules::BoundRule::measured(type001::Type001));
    rules.push(gob_rules::BoundRule::measured(type002::Type002));
    rules.push(gob_rules::BoundRule::measured(type003::Type003));
    rules.push(gob_rules::BoundRule::file(waive001::Waive001));
    rules
}

#[cfg(test)]
mod freshness {
    /// The committed index equals what the rule files imply.
    #[test]
    fn rules_index_is_fresh() {
        gob_rules::indexgen::assert_fresh(env!("CARGO_MANIFEST_DIR")).expect("rules index");
    }
}
