// @generated by `cargo dev gen rules-index`; do not edit by hand.
//! The rules of this crate, one module per `src/rules/<id>.rs`.

/// Rule `COLOR001`.
pub mod color001;
/// Rule `COLOR002`.
pub mod color002;
/// Rule `CONTRAST001`.
pub mod contrast001;
/// Rule `RADIUS001`.
pub mod radius001;
/// Rule `SIZE001`.
pub mod size001;
/// Rule `SPACE001`.
pub mod space001;
/// Rule `TYPE001`.
pub mod type001;
/// Rule `TYPE002`.
pub mod type002;
/// Rule `TYPE003`.
pub mod type003;
/// Rule `WAIVE001`.
pub mod waive001;

/// The declaration of every rule in this crate, sorted by file stem.
pub const METAS: &[&gob_rules::RuleDef] = &[
    // one entry per rule file
    <color001::Color001 as gob_rules::RuleDecl>::DEF,
    <color002::Color002 as gob_rules::RuleDecl>::DEF,
    <contrast001::Contrast001 as gob_rules::RuleDecl>::DEF,
    <radius001::Radius001 as gob_rules::RuleDecl>::DEF,
    <size001::Size001 as gob_rules::RuleDecl>::DEF,
    <space001::Space001 as gob_rules::RuleDecl>::DEF,
    <type001::Type001 as gob_rules::RuleDecl>::DEF,
    <type002::Type002 as gob_rules::RuleDecl>::DEF,
    <type003::Type003 as gob_rules::RuleDecl>::DEF,
    <waive001::Waive001 as gob_rules::RuleDecl>::DEF,
];

/// This crate's rule index: the declarations plus renamed and retired ids.
pub const INDEX: gob_rules::RuleIndex = gob_rules::RuleIndex {
    krate: env!("CARGO_PKG_NAME"),
    metas: METAS,
    renamed: &[],
    retired: &[],
};

const _: () = gob_rules::assert_unique("crate", &[&[&INDEX]]);

/// Bind every rule of this crate to the product host `P`; fails to compile unless `P` hosts them all.
#[allow(clippy::vec_init_then_push, reason = "generated: one push per rule")]
pub fn bind<P: ?Sized + 'static>() -> Vec<gob_rules::BoundRule<P>>
where
    color001::Color001: gob_rules::Measured<P>,
    color002::Color002: gob_rules::Measured<P>,
    contrast001::Contrast001: gob_rules::RepoRule<P>,
    radius001::Radius001: gob_rules::Measured<P>,
    size001::Size001: gob_rules::Measured<P>,
    space001::Space001: gob_rules::Measured<P>,
    type001::Type001: gob_rules::Measured<P>,
    type002::Type002: gob_rules::Measured<P>,
    type003::Type003: gob_rules::Measured<P>,
    waive001::Waive001: gob_rules::FileRule<P>,
{
    let mut rules = Vec::new();
    rules.push(gob_rules::BoundRule::measured(color001::Color001));
    rules.push(gob_rules::BoundRule::measured(color002::Color002));
    rules.push(gob_rules::BoundRule::repo(contrast001::Contrast001));
    rules.push(gob_rules::BoundRule::measured(radius001::Radius001));
    rules.push(gob_rules::BoundRule::measured(size001::Size001));
    rules.push(gob_rules::BoundRule::measured(space001::Space001));
    rules.push(gob_rules::BoundRule::measured(type001::Type001));
    rules.push(gob_rules::BoundRule::measured(type002::Type002));
    rules.push(gob_rules::BoundRule::measured(type003::Type003));
    rules.push(gob_rules::BoundRule::file(waive001::Waive001));
    rules
}

#[cfg(test)]
mod freshness {
    /// The committed index equals what the rule files imply.
    #[test]
    fn rules_index_is_fresh() {
        gob_rules::indexgen::assert_fresh(env!("CARGO_MANIFEST_DIR")).expect("rules index");
    }
}
