"""frob.strata -- the provable system-design language (docs/strata/charter.md).

Phase 0 exposes the kernel: the six-primitive data model the elaborator
targets and the prover consumes. Parser, elaborator, and vocabularies
arrive in later phases (docs/strata/roadmap.md); nothing here may ever
learn a surface vocabulary word (charter law 1).
"""

from __future__ import annotations

from frob.strata._ast import (
    AdmitPhase,
    AtCallRequire,
    BalancerDecl,
    BoundaryDecl,
    CacheDecl,
    CdnDecl,
    ClaimDecl,
    ConfineUse,
    EffectPhase,
    FlowDecl,
    ForbidCall,
    ForbidImport,
    Mediate,
    Module,
    NodeDecl,
    ObserveDecl,
    OperationDecl,
    ParsePhase,
    PhaseBlock,
    PolicyDecl,
    PolicyRule,
    QueueDecl,
    RecordPhase,
    RefineDecl,
    RefusePhase,
    RemoveDecl,
    RewriteDecl,
    ScaleDecl,
    ScenarioDecl,
    ScopeSpec,
    StoreDecl,
    TrustDecl,
)
from frob.strata._ast import (
    Capacity as SurfaceCapacity,
)
from frob.strata._claims import evaluate_claims
from frob.strata._elaborate import elaborate
from frob.strata._errors import StrataError
from frob.strata._facts import FactBase, build_facts
from frob.strata._infra import InfraExpansion, elaborate_infra
from frob.strata._models import (
    LABELS,
    TRUST,
    Boundary,
    BoundaryDirection,
    BoundClaim,
    Capacity,
    Claim,
    ClaimBody,
    ClaimResult,
    Flow,
    FlowCondition,
    KernelModel,
    Lattice,
    Metric,
    Node,
    NoFlow,
    Outcome,
    Quantifier,
    Quantity,
    Reach,
    RemoveNode,
    Rewrite,
    Rung,
    ScaleRate,
    Scenario,
    SetTrust,
    Verdict,
)
from frob.strata._packs import ANALYZABLE, ANALYZABLE_POLICY_ID, require_analyzable
from frob.strata._parse import parse_module
from frob.strata._policy import CompiledPolicies, CompiledPolicy, compile_policies
from frob.strata._report import render_report, summarize
from frob.strata._scenarios import ScenarioResult, evaluate_scenarios

__all__ = [
    "ANALYZABLE",
    "ANALYZABLE_POLICY_ID",
    "LABELS",
    "TRUST",
    "AdmitPhase",
    "AtCallRequire",
    "BalancerDecl",
    "Boundary",
    "BoundaryDecl",
    "BoundaryDirection",
    "BoundClaim",
    "CacheDecl",
    "Capacity",
    "CdnDecl",
    "ClaimDecl",
    "CompiledPolicies",
    "CompiledPolicy",
    "ConfineUse",
    "EffectPhase",
    "FactBase",
    "Claim",
    "ClaimBody",
    "ClaimResult",
    "Flow",
    "FlowCondition",
    "FlowDecl",
    "ForbidCall",
    "ForbidImport",
    "InfraExpansion",
    "KernelModel",
    "Lattice",
    "Mediate",
    "Metric",
    "Module",
    "Node",
    "NodeDecl",
    "NoFlow",
    "ObserveDecl",
    "OperationDecl",
    "Outcome",
    "ParsePhase",
    "PhaseBlock",
    "PolicyDecl",
    "PolicyRule",
    "Quantifier",
    "Quantity",
    "QueueDecl",
    "Reach",
    "RecordPhase",
    "RefineDecl",
    "RefusePhase",
    "RemoveDecl",
    "RemoveNode",
    "Rewrite",
    "RewriteDecl",
    "Rung",
    "ScaleDecl",
    "ScaleRate",
    "Scenario",
    "ScenarioDecl",
    "ScenarioResult",
    "ScopeSpec",
    "SetTrust",
    "StoreDecl",
    "StrataError",
    "SurfaceCapacity",
    "TrustDecl",
    "Verdict",
    "build_facts",
    "compile_policies",
    "elaborate",
    "elaborate_infra",
    "evaluate_claims",
    "evaluate_scenarios",
    "parse_module",
    "render_report",
    "require_analyzable",
    "summarize",
]
