"""frob.strata -- the provable system-design language (docs/strata/charter.md).

Phase 0 exposes the kernel: the six-primitive data model the elaborator
targets and the prover consumes. Parser, elaborator, and vocabularies
arrive in later phases (docs/strata/roadmap.md); nothing here may ever
learn a surface vocabulary word (charter law 1).
"""

from __future__ import annotations

from frob.strata._ast import (
    AdmitPhase,
    AtCallRequire,
    BalancerDecl,
    BoundaryDecl,
    CacheDecl,
    CdnDecl,
    ClaimDecl,
    ConfineUse,
    EffectPhase,
    FlowDecl,
    ForbidCall,
    ForbidImport,
    Mediate,
    Module,
    NodeDecl,
    ObserveDecl,
    OperationDecl,
    ParsePhase,
    PhaseBlock,
    PolicyDecl,
    PolicyRule,
    QueueDecl,
    RecordPhase,
    RefineDecl,
    RefusePhase,
    RemoveDecl,
    RewriteDecl,
    ScaleDecl,
    ScenarioDecl,
    ScopeSpec,
    StoreDecl,
    TrustDecl,
)
from frob.strata._ast import (
    Capacity as SurfaceCapacity,
)
from frob.strata._atomic import (
    AtomicContractReport,
    FaultInjectionCase,
    evaluate_atomic_contracts,
    evaluate_saga_contracts,
    generate_fault_injection_cases,
)
from frob.strata._breach import (
    BlastRadius,
    BreachContractReport,
    evaluate_breach_contracts,
)
from frob.strata._claims import evaluate_claims
from frob.strata._code_binding import (
    FOREIGN,
    CodeBinding,
    ConformanceReport,
    ImportViolation,
    bind_code,
    check_import_conformance,
)
from frob.strata._crash import CrashContractReport, evaluate_crash_contracts
from frob.strata._deploy import DeployContractReport, evaluate_deploy_contracts
from frob.strata._design_load import (
    DEFAULT_DESIGN_DIR,
    UNBOUND_REQUIRED_KINDS,
    DesignIds,
    DesignLoadError,
    load_design_ids,
    unbound_constructs,
)
from frob.strata._effects import (
    CapabilityViolation,
    EffectReport,
    ObservedEffect,
    check_capability_conformance,
    extract_effects,
)
from frob.strata._elaborate import elaborate
from frob.strata._errors import StrataError
from frob.strata._facts import FactBase, build_facts
from frob.strata._infra import InfraExpansion, elaborate_infra
from frob.strata._models import (
    LABELS,
    TRUST,
    Boundary,
    BoundaryDirection,
    BoundClaim,
    BreachContract,
    CanaryStage,
    Capacity,
    Claim,
    ClaimBody,
    ClaimResult,
    CrashContract,
    DeployContract,
    Flow,
    FlowCondition,
    Independent,
    KernelModel,
    Lattice,
    Metric,
    Node,
    NoFlow,
    Outcome,
    Quantifier,
    Quantity,
    Reach,
    RemoveNode,
    Rewrite,
    Rung,
    ScaleRate,
    Scenario,
    SetEquality,
    SetTrust,
    Verdict,
)
from frob.strata._packs import ANALYZABLE, ANALYZABLE_POLICY_ID, require_analyzable
from frob.strata._parse import parse_module
from frob.strata._plan import MARKER_PREFIX, PlannedTicket, PlanResult, plan_obligations
from frob.strata._policy import CompiledPolicies, CompiledPolicy, compile_policies
from frob.strata._report import render_report, summarize
from frob.strata._scenarios import ScenarioResult, evaluate_scenarios
from frob.strata._secrets import (
    SECRET_LABEL,
    SecretExpansion,
    SecretSpec,
    elaborate_secret,
)
from frob.strata._threat import (
    CWE_CATALOG,
    VIEWS,
    BenignCapability,
    OutOfScopeEntry,
    ThreatReport,
    ThreatViolation,
    WeaknessEntry,
    check_capability_completeness,
    check_catalog_completeness,
    check_discharge_completeness,
    evaluate_threats,
)

__all__ = [
    "ANALYZABLE",
    "ANALYZABLE_POLICY_ID",
    "DEFAULT_DESIGN_DIR",
    "MARKER_PREFIX",
    "UNBOUND_REQUIRED_KINDS",
    "CWE_CATALOG",
    "LABELS",
    "SECRET_LABEL",
    "TRUST",
    "VIEWS",
    "AdmitPhase",
    "AtCallRequire",
    "AtomicContractReport",
    "BalancerDecl",
    "BenignCapability",
    "BlastRadius",
    "Boundary",
    "BoundaryDecl",
    "BoundaryDirection",
    "BoundClaim",
    "BreachContract",
    "BreachContractReport",
    "CacheDecl",
    "CanaryStage",
    "CapabilityViolation",
    "Capacity",
    "CdnDecl",
    "ClaimDecl",
    "CodeBinding",
    "CompiledPolicies",
    "CompiledPolicy",
    "ConfineUse",
    "ConformanceReport",
    "CrashContract",
    "CrashContractReport",
    "DeployContract",
    "DeployContractReport",
    "DesignIds",
    "DesignLoadError",
    "EffectPhase",
    "EffectReport",
    "FOREIGN",
    "FactBase",
    "FaultInjectionCase",
    "Claim",
    "ClaimBody",
    "ClaimResult",
    "Flow",
    "FlowCondition",
    "FlowDecl",
    "ForbidCall",
    "ForbidImport",
    "ImportViolation",
    "Independent",
    "InfraExpansion",
    "KernelModel",
    "Lattice",
    "Mediate",
    "Metric",
    "Module",
    "Node",
    "NodeDecl",
    "NoFlow",
    "ObservedEffect",
    "ObserveDecl",
    "OperationDecl",
    "Outcome",
    "OutOfScopeEntry",
    "ParsePhase",
    "PhaseBlock",
    "PlanResult",
    "PlannedTicket",
    "PolicyDecl",
    "PolicyRule",
    "Quantifier",
    "Quantity",
    "QueueDecl",
    "Reach",
    "RecordPhase",
    "RefineDecl",
    "RefusePhase",
    "RemoveDecl",
    "RemoveNode",
    "Rewrite",
    "RewriteDecl",
    "Rung",
    "ScaleDecl",
    "ScaleRate",
    "Scenario",
    "ScenarioDecl",
    "ScenarioResult",
    "ScopeSpec",
    "SecretExpansion",
    "SecretSpec",
    "SetEquality",
    "SetTrust",
    "StoreDecl",
    "StrataError",
    "SurfaceCapacity",
    "ThreatReport",
    "ThreatViolation",
    "TrustDecl",
    "Verdict",
    "WeaknessEntry",
    "bind_code",
    "build_facts",
    "check_capability_completeness",
    "check_capability_conformance",
    "check_catalog_completeness",
    "check_discharge_completeness",
    "check_import_conformance",
    "compile_policies",
    "elaborate",
    "elaborate_infra",
    "elaborate_secret",
    "evaluate_atomic_contracts",
    "evaluate_breach_contracts",
    "evaluate_claims",
    "evaluate_crash_contracts",
    "evaluate_deploy_contracts",
    "evaluate_saga_contracts",
    "evaluate_scenarios",
    "evaluate_threats",
    "extract_effects",
    "generate_fault_injection_cases",
    "load_design_ids",
    "parse_module",
    "plan_obligations",
    "render_report",
    "require_analyzable",
    "summarize",
    "unbound_constructs",
]
